### ISSUE TITLE
Github login not working

### ISSUE THREAD

**Issue by viceice** [artifacthub/hub#1008]
I've tried to login with Github and get `Authentication process failed. Please try again later.` after redirect back.

Can see a 401 for `/api/v1/profile` ajax request.

![image](https://user-images.githubusercontent.com/1798109/104149285-e6c8f080-53d5-11eb-8686-d38eef03fd40.png)

**Comment by tegioz** [comment]
Hi @viceice 👋 

Could you please check that your primary email in Github has been verified?

**Comment by viceice** [comment]
Ok thanks, that was it. I'm not sure why it wasn't verified. I'm using it a long time. 🤷‍♂️

**Comment by tegioz** [comment]
Cool, no worries 👍
