### ISSUE TITLE
Allow override license for helm charts

### ISSUE THREAD

**Issue by viceice** [artifacthub/hub#1013]
It would be nice to allow annotating helm charts with `artifacthub.io/license`, so we can override the SPDX identifier.

eg for https://artifacthub.io/packages/helm/renovate/renovate it detects `deprecated_AGPL-3.0` but we would like to have `AGPL-3.0-only`

It happens because the used license detector can't distingish beween the differen AGPL v3 versions. The text is the same for all.

**Comment by tegioz** [comment]
This is ready, we'll deploy it later today.

**Comment by viceice** [comment]
Thanks, will add the annotation, to it gets pushed on out next release 🙃
