### ISSUE TITLE
Error converting YAML to JSON in Helm

### ISSUE THREAD

**Issue by joshthoward** [artifacthub/hub#1024]
I am getting the following error message when trying to link a [helm chart](https://github.com/joshthoward/charts/tree/gh-pages) on GitHub. 

```
An error occurred adding the repository: invalid input: error converting YAML to JSON: yaml: line 90: mapping values are not allowed in this context
```

The curious thing I am seeing is that there are no files with 90 lines? 

Please help!

**Comment by joshthoward** [comment]
FYI recreating another [chart](https://github.com/joshthoward/ballista-charts/tree/gh-pages) that was previously working is now throwing the same error.

**Comment by tegioz** [comment]
Hi @joshthoward 👋 

Can you share the urls you are using when adding the repos to Artifact Hub?

I've just tried both in my local deployment and they were added and indexed fine.

<img width="1999" alt="Screen Shot 2021-01-14 at 08 11 46" src="https://user-images.githubusercontent.com/1213902/104556764-6eb23300-5640-11eb-9266-9362eb420037.png">

<img width="1999" alt="Screen Shot 2021-01-14 at 08 12 02" src="https://user-images.githubusercontent.com/1213902/104556775-71ad2380-5640-11eb-8b75-6c678d283a68.png">

**Comment by tegioz** [comment]
I've used these urls:

- https://joshthoward.github.io/charts
- https://joshthoward.github.io/ballista-charts

**Comment by joshthoward** [comment]
@tegioz my bad. I was copying the gh-pages branch url rather than the hosted static site. 

Thanks for the quick response.

**Comment by tegioz** [comment]
Cool, no problem 👍
