### ISSUE TITLE
Configuration & cache handling issues with random securityContext

### ISSUE THREAD

**Issue by alexrashed** [artifacthub/hub#1037]
Hello everyone!
Thanks for the great tool you're providing!
We would love to provide an internal ArtifactHub in our OpenShift cluster.
Unfortunately we are facing some issues with the Helm chart and/or ArtifactHub's configuration (and cache) handling in general.

When deploying ArtifactHub in an OpenShift cluster, it gets a random uid, which does not have a home directory in the container and does not have write permissions on `/home/hub`.
This results in the following problems:
* The configuration files are not found (since `$HOME` is not set, but used when loading the configurations).
* The cache cannot be written.
  * Since `$HOME` is not set, it tries to write on `/.cache` (subdirectory of root), which of course fails due to the missing root permissions.
  * Even if `$HOME` is set, the `.cache` folder cannot be written (since the user which is running the container does not have write permissions on `/home/hub`).

In my opinion there are two options:
* The `$HOME` environment variable can be set in the Helm chart (maybe even by providing a generic `extraEnv` value) and `/home/hub/.cache` is mounted as a writable ephemeral volume (`emptyDir`).
* Configurations and cache are not in the home directory. The config could for example be mounted at `/config`, and the cache could be written in the `tmp` folder.

I can provide PRs, I just wanted to discuss the issue first (is it considered a problem, if so which approach would be preferred).

**Comment by tegioz** [comment]
Hi @alexrashed 👋 

Thanks, we are glad you like it 🙂 

A bit of context first:

Artifact Hub runs [a few processes](https://github.com/artifacthub/hub/tree/master/cmd) and each of them has a different configuration file that is expected to be located at `$HOME` at the moment. The path used to look for configuration files could be configurable, adding an extra one in addition to `$HOME` when provided, or we could even add multiple default locations (`/.cfg`, for example). That’s not really a problem, but there is more to keep in mind.

The `.cache` directory you mention is probably created by `trivy` when images are scanned for security vulnerabilities. `opm` also writes some data when exporting catalogs from OCI images, but you may not have hit this one yet if you haven’t added any OCI based OLM repos. These are two external tools we rely on (called from the `scanner` and `tracker` respectively). IIRC `trivy` needs `$HOME` set and uses it for the cache, but I think a cache-dir can be provided as well. `opm`, on the other hand, writes in the directory it's run from.

So I think a combination of the options you suggested would be best. We could:

- Add an extra default search path for config files (maybe `/.cfg`). That should only require adding a line [here](https://github.com/artifacthub/hub/blob/112c2d65c53fc6881ea735bf738044da728ec009/internal/util/config.go#L18).
- Add a configurable `tmpDir` that can be set in the chart.
- Make sure both `trivy` and `opm` write inside that `tmpDir`, maybe each using a subfolder with their respective names.

Hope this helps. I'll keep thinking about this just in case something else comes to mind.

**Comment by alexrashed** [comment]
### Cache
I must have mixed things up during my testing, because it turns out the cache isn't a problem after all.
There currently are different implementations for the cache.

#### Trivy:
Trivy already takes care of the cache folder with a combination of the two suggested approaches:
- The cache directory is set to `/trivy`: https://github.com/artifacthub/hub/blob/master/charts/artifact-hub/templates/trivy_deployment.yaml#L25
- An ephemeral storage (emptyDir) is mounted on `/trivy`.

#### OLM / OPM:
For the execution of the OPM command, a TempDir [here](https://github.com/artifacthub/hub/blob/112c2d65c53fc6881ea735bf738044da728ec009/internal/repo/olm.go#L25) is created by using golang's TempDir function with an empty string for the `dir` parameter.
According to the [documentation](https://golang.org/pkg/io/ioutil/#TempDir) this results in the creation of a new directory in the OS' tmp directory (`/tmp` on linux).
Since the OS specific temp folder is writable per definition, this also works out of the box.

#### Tracker
Actually, the execution of `trivy`, `hub`, and `scanner` don't need the `/home/hub/.cache` folder. It only causes problems during a run of the `tracker`. However, I'm not sure yet where the directory is used.

### Config
Adding another fallback directory which is not bound to the `HOME` variable sounds like a good idea. But I guess I wouldn't introduce a hidden directory on root-level. I'd suggest to name the directory `/hub-config`, `/cfg`, `/hub-cfg` or `/hub/.cfg`.

**Comment by tegioz** [comment]
Awesome, let's just add then another search path for config files. I'd rather not using just `hub` as it can be misleading in the `tracker` or `scanner` containers, but I'm fine with `/artifacthub/.cfg`, `/artifacthub-cfg` or `/artifacthub-config`.

**Comment by alexrashed** [comment]
Great, I will create a PR for that change.
However, unfortunately the "everything's fine with caching" from my previous post isn't correct (as stated below in the exact comment - sorry for the confusion).

So the scanner needs the `/home/hub/.cache` directory, but actually I haven't found the code where it's referenced yet...

**Comment by tegioz** [comment]
https://github.com/artifacthub/hub/blob/dea3a5f9cfe9f94b1af32725a42e923bdfa0c294/internal/scanner/trivy.go#L30.

**Comment by tegioz** [comment]
Given that I did not provide a `--cache-dir` in the client, it must be using that one by default. Trivy allows overriding this using `$TRIVY_CACHE_DIR`, so we could allow this environment variable to be set and make sure it's included in the environment passed to the trivy command by adding it [here](https://github.com/artifacthub/hub/blob/dea3a5f9cfe9f94b1af32725a42e923bdfa0c294/internal/scanner/trivy.go#L38).

**Comment by alexrashed** [comment]
Thanks for the help, I'm already working on a PR.
Actually, while testing my fixes I realized that also the Helm CLI cache needs to be adjusted for the hub (via the environment variable `XDG_CACHE_HOME` as described in the [documentation](https://helm.sh/docs/faq/#how-do-i-put-the-helm-client-files-somewhere-other-than-their-defaults).
So I'll introduce two new values:
- `scanner.trivyCacheDir`
- `hub.deploy.helmCacheDir`

If you don't have any additional comments, I'll push the changes and open the PR later today.

**Comment by tegioz** [comment]
No worries, my pleasure.

That sounds great to me, thanks! 👍
