### ISSUE TITLE
Official tag for Solr Operator

### ISSUE THREAD

**Issue by HoustonPutman** [artifacthub/hub#1047]
Hello, the solr operator has been donated the Apache Solr project.

The official repo is now: https://github.com/apache/lucene-solr-operator

Would you be able to do the following?

1. Give this repository the "Official" tag.
https://artifacthub.io/packages/helm/apache-solr/solr-operator
2. Remove the old repository: https://artifacthub.io/packages/helm/solr-operator/solr-operator

**Comment by tegioz** [comment]
> 1. Give this repository the "Official" tag. https://artifacthub.io/packages/helm/apache-solr/solr-operator

Done! Could you please set up the [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) label as well? Official repositories usually do this first, and it'll also help positioning your package better in search results.

> 2. Remove the old repository: https://artifacthub.io/packages/helm/solr-operator/solr-operator

That repository belongs to the Helm organization at the moment and only its members can remove it. Could you please delete it for him @mattfarina? Thanks!

**Comment by HoustonPutman** [comment]
Thanks @tegioz! I finally got it to show up, didn't realize I had to modify my `index.yaml` for it to get picked up on a refresh. Will have to read the docs more clearly next time!

And @mattfarina, if you are worried about deleting the helm chart for the old solr operator repo (https://github.com/bloomberg/solr-operator), you can see that the repo itself now re-directs to the official repo (https://github.com/apache/lucene-solr-operator). So there is no risk.

**Comment by tegioz** [comment]
> Thanks @tegioz! I finally got it to show up, didn't realize I had to modify my `index.yaml` for it to get picked up on a refresh. Will have to read the docs more clearly next time!

No worries, I've just updated [the docs today to explain this behavior](https://github.com/artifacthub/hub/pull/1048/files), it wasn't there yesterday 😅.

**Comment by HoustonPutman** [comment]
I also just updated my charts to include some metadata for artifactHub. But since the versions haven't changed, it's not picking up the changes. Is it difficult to do a one-time run with `bypassDigestCheck:true` for just this repo?

**Comment by tegioz** [comment]
If you update the digest of the charts versions you've modified they should be processed again, no need to release a new version (just in case it helps). We also have an [open issue](https://github.com/artifacthub/hub/issues/896) to allow triggering this for the whole repo from the control panel.

If you cannot update the charts' digest please let me know and I'll trigger one for you tomorrow morning 🙂

**Comment by HoustonPutman** [comment]
So the digest did change actually.

I [looked at the code](https://github.com/artifacthub/hub/blob/master/internal/tracker/source/helm/helm.go#L205), and it looks like it only checks to see if the version already exists or not. ([The build key is just the name and version](https://github.com/artifacthub/hub/blob/cbe56b380fcaccfba68bbd6118dbf6a7733c9595/internal/pkg/manager.go#L301))

I could be misunderstanding the code though.

**Comment by tegioz** [comment]
I don't think you are misunderstanding it, I suspect it's a regression I introduced [refactoring the trackers last week](https://github.com/artifacthub/hub/pull/1032).

This is how it used to work, that's why I suggested the updating the digest:

https://github.com/artifacthub/hub/blob/dcf501a0217f0556353ff75d4b0cf82234c98e31/internal/tracker/helm/tracker.go#L159-L168

But I've left that check out during the refactor. I'll fix it tomorrow morning, thanks for catching this! The digest is already available on the line you pointed out but it's being ignored, it shouldn't take long.

Thanks again!

**Comment by tegioz** [comment]
Hi @HoustonPutman 

The issue you reported yesterday has been fixed in #1053. I've just deployed it, so the next tracker run should pick your changes (I've also reset your repository digest so that you don't have to modify the `index.yaml` file again).

**Comment by tegioz** [comment]
BTW nice job with the annotations, your package looks great 🏅

**Comment by mattfarina** [comment]
I've removed the old location.

**Comment by tegioz** [comment]
Thanks Matt! Will close this issue then.

**Comment by HoustonPutman** [comment]
Thanks for both of your help!
