### ISSUE TITLE
Official badge for Hazelcast Helm charts

### ISSUE THREAD

**Issue by hasancelik** [artifacthub/hub#1054]
Hi,

We have already added `artifacthub-repo.yml` into the [our chart repo](https://hazelcast-charts.s3.amazonaws.com). Could you add `Official` badge into below repository and its packages?
https://artifacthub.io/packages/search?page=1&repo=hazelcast

Thanks,

**Comment by tegioz** [comment]
Done!

**Comment by hasancelik** [comment]
Thanks for quick action @tegioz 

Icons at `hazelcast` and `hazelcast-enteprise` packages are gone after today's changes. Is it related to `artifacthub-repo.yml` or the badges?

https://artifacthub.io/packages/search?page=1&ts_query_web=hazelcast&verified_publisher=true&official=true
<img width="1583" alt="Screen Shot 2021-01-27 at 22 57 52" src="https://user-images.githubusercontent.com/6005622/106046282-1b85b900-60f3-11eb-8bed-007b52855584.png">

Previously, icons are fetched from URLs at our `Chart.yaml`s:
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/Chart.yaml#L14
https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/Chart.yaml#L14

**Comment by tegioz** [comment]
I think you've hit a bug related to the `ignore` field.

We only load the logo image for the latest version available. But in the case of those two packages, the latest version has been marked to be ignored, so it's not processed. I suspect this is what's causing the problem.

I'll look deeper into it tomorrow, this needs to get fixed. Thanks for raising the issue, I'll keep you posted!

**Comment by tegioz** [comment]
The issue should be now fixed @hasancelik. When a new version of those charts is released the logo should be back. You can also update the digest of the latest version to force it to be reindexed.

Please let me know otherwise. Thanks!
