### ISSUE TITLE
Helm chart defaults: imageTag=latest and imagePullPolicy=IfNotPresent is dangerous

### ISSUE THREAD

**Issue by alexrashed** [artifacthub/hub#1064]
Hi there!

I just stumbled across a problem when upgrading ArtifactHub using the official Helm chart.
Currently the Helm chart by default uses the `imageTag: latest` and the `imagePullPolicy: IfNotPresent`.
This is quite dangerous, since the `latest` tag content changes over time, but the new content is not pulled if it's already present on the node.
In my opinion the `imageTag` should default to the Chart's `appVersion` (which is some kind of best practice I'd say), and the `imagePullPolicy` should stay the same (`IfNotPresent`).
If there are reasons to stay with the `latest` tag (which, however, could cause problems on upgrades as well as downgrades), the `ImagePullPolicy` should be suppressed. By default Kubernetes uses `Always` for the tag `latest`, and `IfNotPresent` otherwise (as described [in the API reference docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/)).

I'd be happy to submit a PR, just wanted to discuss the topic before working on it.

**Comment by tegioz** [comment]
Hi @alexrashed!

Defaulting `imageTag` to the chart's `appVersion` sounds good to me.

Please keep in mind that images publicly available at the Docker Hub are built when [a new release is generated in Github](https://github.com/artifacthub/hub/blob/master/.github/workflows/release.yml). When [this PR](https://github.com/artifacthub/hub/pull/1060) that updates the chart's `appVersion` was created, for example, components' images for version `0.14.0` were not yet available. So the chart testing should probably still use the `latest` tag.

**Comment by tegioz** [comment]
> I just stumbled across a problem when upgrading ArtifactHub using the official Helm chart.

There is something about upgrades that I forgot to mention to you @alexrashed:

We are not generating database migration files for schema changes yet. We decided to go this way until the project was kind of stable, as we were moving fast and it was simpler this way. Database functions changes are applied though, but schema changes are not. We intend to create schema migrations starting with version `0.14.0`. However, if you were upgrading from version `0.13.0`, the following changes will need to be applied manually to the database:

```sql
--- Helm plugins support
insert into repository_kind values (6, 'Helm plugins');

--- Tekton tasks support
insert into repository_kind values (7, 'Tekton tasks');

--- Allow deleting organizations
alter table repository drop constraint repository_organization_id_fkey, add constraint repository_organization_id_fkey foreign key (organization_id) references organization on delete cascade;
```

If you were upgrading from an older version, you'll probably need to apply some more changes. You shouldn't need to worry about this in upcoming versions.

**Comment by alexrashed** [comment]
Thanks a lot for the heads up! Luckily we'll start using it internally with 0.14.0, so we don't have any problems with the upgrades for now. Nevertheless, I'm aware that Artifacthub isn't stable yet and upgrades might cause problems. :)

**Comment by tegioz** [comment]
Awesome, no worries 😊
