### ISSUE TITLE
Sorting?

### ISSUE THREAD

**Issue by boldandbusted** [artifacthub/hub#1080]
Howdy. Thank you for ArtifactHub! It's really a neat way to find Helm Charts, and the styling is very nice!

I'm confused on how I might sort results. For example, I'd like to sort artifacts returned from a Search based on number of Stars. Or sort a list of all publishers by number of charts. How can I do this? I don't see an obvious way on https://artifacthub.io. Thanks in advance. Cheers.

**Comment by tegioz** [comment]
Hi @boldandbusted 👋 

Thanks, we are glad you like it 😊 

At the moment there isn't a way to sort search results other than the default one provided. It's basically a search sorted by relevance, and when the relevance is the same for multiple results we also sort by the following criteria (in this order):

- Official packages
- Packages from verified publishers
- Stars (descending)
- Name (alphabetically, ascending)

The relevance is computed based on the weight of the search terms in the different parts of the package metadata. More details can be found [here](https://github.com/artifacthub/hub/blob/78ef20dd3cc59a9b0cc1ee1f8d3d78f51c3b28c9/database/migrations/functions/packages/search_packages.sql#L157-L171).

Our intention has been to keep it simple to use and try to make the default ordering useful for most users. But if there are any specific improvements that can be applied to it or we can identify some additional sorting alternatives that can provide value, we are definitely open to consider them 🙂 The stars criteria is already being applied, but only when the ranking of the results matching the search criteria is the same. This ranking takes into account where the search term was found in the document (title vs description, for example), among other things, which is often important.

Regarding obtaining a list of publishers by number of packages, or a list of repositories, you can do that from the filters section in the left column:

<img width="316" alt="Screen Shot 2021-02-04 at 08 30 28" src="https://user-images.githubusercontent.com/1213902/106862080-ea931e80-66c6-11eb-9d4d-ddea73df16ae.png">

<img width="316" alt="Screen Shot 2021-02-04 at 08 30 42" src="https://user-images.githubusercontent.com/1213902/106862090-ee26a580-66c6-11eb-90d3-ed0cbf572c0d.png">

Hope this helps. Thanks!

**Comment by boldandbusted** [comment]
Thank you very much for that detailed assistance, @tegioz! I look forward to seeing ArtifactHub and the CNCF continue to make . :)

**Comment by tegioz** [comment]
No worries, thank you! 👍

**Comment by Ashtonian** [comment]
Can you enable users to filter and sort please? In my opinion if the decision isn't obvious from the default sort, it isn't very useful as the user has no visibility into how the list is prioritized until they come into this thread. So if the first couple results don't work then one almost feels obligated to go through multiple pages looking for the right option simple sorting would alleviate this. 

Searching for [redis](https://artifacthub.io/packages/search?ts_query_web=redis+&page=1) is a good example of poor search results. The first result isn't even a redis instance.

**Comment by tegioz** [comment]
Hi @Ashtonian 

You can now sort by stars as well 🙂 This may change in the future, but let's see how it goes and get some feedback from users about it 😉 

About the `redis` search results, please keep in mind that Artifact Hub hosts multiple kinds of artifacts, and many of them may be complements to the software. In this particular case, it's a set of Falco rules for Redis and the package name is an exact match, which makes it relevant. We don't really favor any artifact kind over another. Also, another problem that's affecting the results in this case is that there are multiple clones of the bitnami redis chart. Hopefully the stars sorting alternative will help in situations like this (I think in this case it does actually).

**Comment by Ashtonian** [comment]
@tegioz thank you, works great!
