### ISSUE TITLE
Official tag for StackStorm Helm chart

### ISSUE THREAD

**Issue by armab** [artifacthub/hub#1091]
Hello,

For the ArtifactHub helm chart: https://artifacthub.io/packages/helm/stackstorm/stackstorm-ha we already have `Verified Publisher` and would like to have the `Official` tag.

* Original StackStorm project: https://github.com/stackstorm/st2
* Helm Chart source code: https://github.com/stackstorm/stackstorm-ha
* https://helm.stackstorm.com/ repository refers to https://github.com/StackStorm/stackstorm-ha/tree/gh-pages

Thanks!

**Comment by tegioz** [comment]
Done!
