### ISSUE TITLE
[OFFICIAL] vault

### ISSUE THREAD

**Issue by jasonodonnell** [artifacthub/hub#1100]
*In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by *all* the packages available in the repository. When this status is granted for a repository, all packages available on it will display the `official` badge.*

- **Repository name** *(in `artifacthub.io`)*: hashicorp
- **Project URL:** https://artifacthub.io/packages/helm/hashicorp/vault
- **Source code URL** *(if available)*: https://github.com/hashicorp/vault-helm
- **Other relevant URLs:**
  - https://github.com/hashicorp/vault
  - https://github.com/hashicorp/vault-k8s
  - https://www.vaultproject.io/docs/platform/k8s/helm

**Before submitting this request, please confirm that your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The repository *only* contains `official` packages. A mix of official and non-official packages is not allowed at the moment, but we are considering to allow the `official` status to be set [at the package level](https://github.com/artifacthub/hub/issues/972) and this might change in the future.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] The packages available in the repository provide some documentation, usually in the form of a `README.md` file.

**Comment by tegioz** [comment]
Hi @jasonodonnell 👋 

I've just checked and that repository belongs to the Helm organization. Would you mind [claiming its ownership](https://artifacthub.io/docs/topics/repositories/#ownership-claim) and get the [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status?

@david-yu just filed a related issue (#1099). You could setup an organization and invite multiple members. BTW the official status is set at the repository level, there is no need to claim it per package. But please make sure all packages in the repo are official 🙂 

Please let me know if you run into any trouble.
Thanks!

**Comment by jasonodonnell** [comment]
Great, thank you @tegioz, we'll take a look on our end. 👍
