### ISSUE TITLE
How to reset password?

### ISSUE THREAD

**Issue by nickytd** [artifacthub/hub#1116]
Hi
Is there a way to reset a password? I need to reset mine but was not able to find a way.

Thanks
Niki Dokovski

**Comment by tegioz** [comment]
Hi @nickytd 👋 

We don't have an option to reset the password yet, sorry about that. We have a ticket (#236) opened for that, we'll work on it very soon.

In the meantime, if you have a Github or Google account in which you use the same email you used to register in Artifact Hub, you should be able to log into your account with it. Please note the email in Github/Google must be the primary one and be verified.

**Comment by nickytd** [comment]
Thanks that worked

**Comment by tegioz** [comment]
Hi @nickytd 

You should be able to reset your password now from the sign in modal:

<img width="417" alt="Screen Shot 2021-02-17 at 11 48 29" src="https://user-images.githubusercontent.com/1213902/108196676-ac135000-7119-11eb-8706-fd2c890c8539.png">
