### ISSUE TITLE
[OFFICIAL] Backube Helm charts

### ISSUE THREAD

**Issue by JohnStrunk** [artifacthub/hub#1118]
*In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by *all* the packages available in the repository. When this status is granted for a repository, all packages available on it will display the `official` badge.*

- **Repository name** *(in `artifacthub.io`)*: Backube Helm charts
- **Project URL:** https://github.com/backube
- **Source code URL** *(if available)*:
  - SnapScheduler: https://github.com/backube/snapscheduler
  - Scribe: https://github.com/backube/scribe
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*
  - Chart repo source: https://github.com/backube/helm-charts
  - Github Backube org members: https://github.com/orgs/backube/people (including me)

**Before submitting this request, please confirm that your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The repository *only* contains `official` packages. A mix of official and non-official packages is not allowed at the moment, but we are considering to allow the `official` status to be set [at the package level](https://github.com/artifacthub/hub/issues/972) and this might change in the future.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] The packages available in the repository provide some documentation, usually in the form of a `README.md` file.

**Comment by tegioz** [comment]
Done!
