### ISSUE TITLE
[OFFICIAL] netapp-trident

### ISSUE THREAD

**Issue by adkerr** [artifacthub/hub#1120]
*In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by *all* the packages available in the repository. When this status is granted for a repository, all packages available on it will display the `official` badge.*

- **Repository name** *(in `artifacthub.io`)*: netapp-trident
- **Project URL:** https://github.com/NetApp/trident
- **Source code URL** *(if available)*: https://github.com/NetApp/trident
- **Other relevant URLs:** https://netapp-trident.readthedocs.io

**Before submitting this request, please confirm that your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The repository *only* contains `official` packages. A mix of official and non-official packages is not allowed at the moment, but we are considering to allow the `official` status to be set [at the package level](https://github.com/artifacthub/hub/issues/972) and this might change in the future.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] The packages available in the repository provide some documentation, usually in the form of a `README.md` file.

**Comment by tegioz** [comment]
Hi @adkerr 👋 

> * [ ]  The packages available in the repository provide some documentation, usually in the form of a `README.md` file.

Could you please provide some documentation for the [trident-operator](https://artifacthub.io/packages/helm/netapp-trident/trident-operator) package? Thanks!

<img width="2062" alt="Screen Shot 2021-02-11 at 16 57 57" src="https://user-images.githubusercontent.com/1213902/107662185-4d1d8900-6c8a-11eb-9f43-8c5cbfd0530c.png">

**Comment by adkerr** [comment]
Sure. I wasn't sure if our readthedocs page would be sufficient. I will see about adding readme to the packages themselves.

**Comment by tegioz** [comment]
If you could add a `README.md` file to the [chart](https://helm.sh/docs/topics/charts/#the-chart-file-structure) it'd be great, as we use it to display the package's documentation in Artifact Hub. Thanks again!

**Comment by tegioz** [comment]
We'll make this clearer in the issue template as looking at it now I realize it can be misleading 👍

**Comment by adkerr** [comment]
@tegioz I have updated the charts with the README.md file. Please let me know if you need anything else

**Comment by tegioz** [comment]
Awesome, official badge ready!
