### ISSUE TITLE
Helm repo Issue

### ISSUE THREAD

**Issue by shivakumar-p-sap** [artifacthub/hub#1124]
**Describe the bug**
Getting the error as below

Error 1:
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: read tcp xx.xx.xx.xx:51789->xx.x.xx.xxx:443: wsarecv: An existing connection was forcibly closed by the remote host.

Error 2:
Error: parse error at (postgresql/charts/common/templates/_secrets.tpl:84): function "lookup" not defined

Error 3:
...Unable to get an update from the "bitnami" chart repository (https://charts.bitnami.com/bitnami):
        read tcp xx.xx.xx.xx:53859->xx.xxx.xx.xx:443: wsarecv: An existing connection was forcibly closed by the remote host.

**To Reproduce**

For Error 1: Sometimes it'll work, sometimes no.
 helm repo add bitnami https://charts.bitnami.com/bitnami

For Error 2:
helm install postgresql -n postgresql bitnami/postgresql

For Error 3:
helm repo update

Regards
Shivakumar P

**Comment by tegioz** [comment]
Hi @shivakumar-p-sap 👋 

Unfortunately there isn't much we can do when there is a problem in a specific repository. We provide a means to discover and inspect packages available in many different repositories, but we don't really host them. Could you please file an issue in the [Bitnami charts](https://github.com/bitnami/charts) Github repository?

Thanks!

**Comment by shivakumar-p-sap** [comment]
Sure Thanks :)
