### ISSUE TITLE
Feedback on failure to scan Helm chart's images

### ISSUE THREAD

**Issue by consideRatio** [artifacthub/hub#1129]
**Is your feature request related to a problem? Please describe.**
My Helm chart repository packaged a Chart.yaml with annotation listing images. I was confused for a while why there wasn't any mention from the vulnerability scanner on why some images wasn't getting their security reports. It turned out that the image wasn't available, and there was no feedback about this.

**Describe the solution you'd like**
I'd like for some feedback on the vulnerability scanners failed attempt to scan images part of a Helm chart. I think it would make sense to expose this alongside the other vulnerability ratings.

**Comment by tegioz** [comment]
Hi @consideRatio

Thanks, this makes sense. We already have something similar for the `tracker` at the moment. If something goes wrong when indexing a repository, the errors are stored and made available on the control panel. We also notify the repository publisher that something went wrong by email. We could try to do something similar for the `scanner`.

<img width="945" alt="Screen Shot 2021-02-19 at 11 39 56" src="https://user-images.githubusercontent.com/1213902/108494695-25d94400-72a8-11eb-8cf8-8c0722249774.png">

<img width="1675" alt="Screen Shot 2021-02-19 at 11 40 56" src="https://user-images.githubusercontent.com/1213902/108494709-296ccb00-72a8-11eb-8aee-7f22d6aaadeb.png">
