### ISSUE TITLE
[OFFICIAL] ectobit

### ISSUE THREAD

**Issue by acim** [artifacthub/hub#1133]
*In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by *all* the packages available in the repository. When this status is granted for a repository, all packages available on it will display the `official` badge.*

- **Repository name** *(in `artifacthub.io`)*:  ectobit
- **Project URL:** https://github.com/ectobit/charts
- **Source code URL** *(if available)*: https://github.com/ectobit/container-images
- **Other relevant URLs:** * https://github.com/ectobit/vanity

**Before submitting this request, please confirm that your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The repository *only* contains `official` packages. A mix of official and non-official packages is not allowed at the moment, but we are considering to allow the `official` status to be set [at the package level](https://github.com/artifacthub/hub/issues/972) and this might change in the future.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] The packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @acim 👋 

I've been checking your repository in Artifact Hub but I can't find any reference that shows that Ectobit is the owner of [rspamd](https://rspamd.com). For a `rspamd` chart to be marked as official, it should be published by the rspamd project itself. Sorry if the concept isn't explained properly, happy to make it clearer if you have any suggestions.

**Comment by acim** [comment]
That's completely true and I didn't claim that, I thought this is just about the charts. Like you said, it is not explained well in the requirements. Can you mark separate charts as official? Project vanity is completely mine.

**Comment by tegioz** [comment]
We'll improve them, thanks 👍

No, unfortunately it's not possible at the moment to mark individual packages as official as mentioned in the requirements. But we are considering it and we'd like to address this soon.

**Comment by acim** [comment]
OK, not a big deal, thank you 😊 Some of the older projects like Postfix, Dovecot, Rspamd are still in use but as they come from pre cloud era, their authors or maintainers seem not to be keen on the new technology so there may be no official charts at all. So, some companies or single developers may want to have both official and unofficial charts. But you are obviously aware of this. Thank you once more for your effort.

**Comment by tegioz** [comment]
Thanks @acim! Hopefully we'll be able to handle individual official packages soon. In the meantime it's also possible to have separate repositories for official and non-official packages.

I've just updated the official status issue template (#1136) to make a bit clearer the intent of the official status. Hope this helps as well 🙂.

I'll close this issue for now, please feel free to reopen if needed.

**Comment by tegioz** [comment]
In addition to requesting the `official` status for a repository, it is now possible to request it for individual packages @acim (#1138).

**Comment by acim** [comment]
Then please set https://artifacthub.io/packages/helm/ectobit/vanity to official.

**Comment by tegioz** [comment]
Done!

**Comment by acim** [comment]
Thank you 😊
