### ISSUE TITLE
Image scanner error report: missing info about what chart caused errors

### ISSUE THREAD

**Issue by consideRatio** [artifacthub/hub#1154]
I got a error from the vulnerability scan which is nice feedback, but I lack important information about them origin of these errors. I know they stem from the Helm chart repo, but what Helm chart?

![image](https://user-images.githubusercontent.com/3837114/109275277-d13c4880-7814-11eb-9d6d-d5f56996b983.png)

**Comment by tegioz** [comment]
Done! We'll deploy it a bit later today.

<img width="1672" alt="Screen Shot 2021-02-26 at 11 33 17" src="https://user-images.githubusercontent.com/1213902/109290083-6fd1a500-7827-11eb-9880-0dcb7741f56b.png">

**Comment by consideRatio** [comment]
:tada:!
