### ISSUE TITLE
Detect HTTP(S) links inside JSON schema description field

### ISSUE THREAD

**Issue by eshepelyuk** [artifacthub/hub#1158]
###  context
[Slack thread](https://cloud-native.slack.com/archives/C0103CTR3RB/p1614120608002200)

### description

JSON schema as well as ArtifactHub support `desription` attribute for a Helm value.
It could be useful if ArtifactHub could detect http/https links within `description` and make them `clickabe`.

### example 

[This value](https://artifacthub.io/packages/helm/cmak-operator/cmak-operator?modal=values-schema&path=zk.resources) contains a link within `desription`, i.e. there could be some text and a single or more links inside.
![image](https://user-images.githubusercontent.com/1279477/109312334-9572a480-784f-11eb-87ae-6c6a8fbefe84.png)

Unfortunately, links are not clickable, but in case links are clickable - the usage of schema viewer would be more comfortable.

**Comment by eshepelyuk** [comment]
@cynthia-sg any chance to know when this feature will be public ?

**Comment by cynthia-sg** [comment]
@eshepelyuk We'll probably deploy it on Monday morning

**Comment by eshepelyuk** [comment]
Thnx , worked great
