### ISSUE TITLE
[OFFICIAL] helm/enix/dothill-csi

### ISSUE THREAD

**Issue by abuisine** [artifacthub/hub#1163]
In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by a package. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (HashiCorp in this case), not just the chart.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: ENIX
- **Official packages** *(leave empty if all packages in the repository are official)*: dothill-csi
- **Project URL:** https://github.com/enix/dothill-csi
- **Source code URL** *(if available)*: https://github.com/enix/dothill-csi
- **Other relevant URLs:** https://github.com/orgs/enix/people

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done! 🚀
