### ISSUE TITLE
Additional structured changes annotation

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#1209]
Some users have reported that it'd be nice to be able to provide some more context to the changes entries, like the kind (bug fix, new feature, etc), a related link, etc. The current changes annotation (plain list of strings) is already being used by many packages, but we could introduce an additional more structured changes annotation.

The goal of this issue is to track users' interest on this feature and collect some feedback so that we can define a format that covers most users needs 🙂 

Related: #1039, https://cloud-native.slack.com/archives/C0103CTR3RB/p1616571755016700

**Comment by Polygens** [comment]
Hey! Our team would really love support for more advanced changelogs like: https://keepachangelog.com/en/1.0.0/

It would make breaking changes and traceability of changes to our helm chart and services more visible towards our end users.

We could introduce additional fields to the `changes` annotation e.g.:
- `type`: type/kind of change that was introduced (added, changed, deprecated, ...)
- `issueID`: external issue/ticket reference
- `subject`: the description of the change
- `externalRef`: additional information about the change (link to the PR, documentation)

Ideally the issueID would resolve into a hyperlink that would support any issue tracking system (github, jira, ...) To make this work we might also have to specify the root url somewhere or make it part of the issueID.

**Comment by tegioz** [comment]
Hi @Polygens!

This is ready, we'll deploy it tomorrow 🙂 

<img width="1019" alt="changelog" src="https://user-images.githubusercontent.com/1213902/116917227-a88a6200-ac4e-11eb-8f6d-ab933d0b8953.png">
