### ISSUE TITLE
Support OCI based chart repositories 

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#122]

**Comment by mattfarina** [comment]
To add some details...

The OCI handing within Helm is going to go through a revision. I believe it will be formatted as a downloader and rolled into some of the existing commands and actions. There are also some design patterns we are looking at. I would hold off until things are a little more stable.

**Comment by tegioz** [comment]
Cool, thanks for the heads up 👍

**Comment by tegioz** [comment]
Hi @mattfarina. Any update on this front?
