### ISSUE TITLE
Online API documentation throws error - duplicated mapping key

### ISSUE THREAD

**Issue by danielhass** [artifacthub/hub#1242]
**Describe the bug**
If a user tries to view the online API documentation one will be presented with an error regarding a `duplicated mapping key` on line 1664. This seems to refer to the following definition in the `openapi.yaml`: https://github.com/artifacthub/hub/blob/master/docs/api/openapi.yaml#L1664

**To Reproduce**
1. Go to https://artifacthub.io/docs/
2. Click on API - https://artifacthub.github.io/hub/api/

**Expected behavior**
The API documentation should be valid and displayed correctly.

**Screenshots**
![Screenshot_2021-04-13 Artifact Hub UI](https://user-images.githubusercontent.com/456036/114509479-d4a95900-9c35-11eb-92be-22368158a3a7.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 87.0

**Comment by tegioz** [comment]
Thanks for reporting this @danielhass, we'll look into it right now 👍

**Comment by danielhass** [comment]
@tegioz @cynthia-sg thank you two so much for this lightning fast fix, awesome :blush:
