### ISSUE TITLE
Provide capability to items all items of a given type

### ISSUE THREAD

**Issue by tomkerkhove** [artifacthub/hub#1248]
**Is your feature request related to a problem? Please describe.**
We're considering moving all our KEDA scalers to Artifact Hub, but still want to have all of them listed on our website.

**Describe the solution you'd like**
Provide capability to items all items of a given type.

**Describe alternatives you've considered**
N/A

**Additional context**
Relates to https://github.com/artifacthub/hub/issues/1228

**Comment by tegioz** [comment]
We've just introduced widget groups @tomkerkhove, which should take care of this 🙂 

<img width="1136" alt="widget-group-2" src="https://user-images.githubusercontent.com/1213902/115404190-604e5700-a1ed-11eb-818f-3350f93767c1.png">

It works like the single widget and you can get the code to embed from the search page, using the icon with the three dots on the top right.

**Comment by tomkerkhove** [comment]
Damn you are fast! Thanks a ton.

**Comment by tegioz** [comment]
No worries! 👍
