### ISSUE TITLE
Easy Method To Theme AH

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#1259]
**Is your feature request related to a problem? Please describe.**
I want to run AH in my private environment and would like to style it for my organization. I would like to do that without needing to fork it and have to deal with managing a fork.

**Describe the solution you'd like**
I would like to be able to change the logo and color profile to use ones from my organization.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dirkmueller** [comment]
Its not just colors and logo, also the "name" - currently "ArtifactHub" is hardcoded in various places, and it would be great to have a "sitename" entity instead.

**Comment by tegioz** [comment]
This is ready 🙂 

<img width="1498" alt="theme" src="https://user-images.githubusercontent.com/1213902/120193491-ca124580-c21c-11eb-83ae-bb46dd60f826.png">

For more information about how to style Artifact Hub, please see: https://github.com/artifacthub/hub/blob/012a983b9bfddae1b14c1dcefd7256babb5f14fb/charts/artifact-hub/values.schema.json#L511-L581

As soon as we cut a new release (probably on Wednesday, but maybe tomorrow) you'll also be able to inspect this documentation from the values schema reference in AH: https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=values-schema&path=hub.theme.
