### ISSUE TITLE
[OFFICIAL] vultr

### ISSUE THREAD

**Issue by ddymko** [artifacthub/hub#1267]
In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by a package. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (HashiCorp in this case), not just the chart.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: ... vultr
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** ... https://github.com/vultr/helm-charts
- **Source code URL** *(if available)*: ... 
- **Other relevant URLs:** 
  - https://artifacthub.io/packages/search?page=1&ts_query_web=vultr
  - https://github.com/vultr/vultr-csi
  - https://github.com/vultr/vultr-cloud-controller-manager
  - https://github.com/vultr/cert-manager-webhook-vultr

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by ddymko** [comment]
Not sure if I should submit 3 individual PRs to to get the official status for 

- https://artifacthub.io/packages/helm/vultr/vultr-csi
- https://artifacthub.io/packages/helm/vultr/vultr-ccm
- https://artifacthub.io/packages/helm/vultr/cert-manager-webhook-vultr

If that is the case I can close this PR with 3 new ones

**Comment by tegioz** [comment]
Hi @ddymko 👋 

This ticket works fine, don't worry. We can assign the official status to a repository or to a single package. Given that all the packages in your repository are official, we've just marked the repository as official, so it's done 🙂
