### ISSUE TITLE
[OFFICIAL] cert-manager

### ISSUE THREAD

**Issue by maelvls** [artifacthub/hub#1281]
Hi!

We (the cert-manager team) finally managed to have the "Verified" badge on Artifact Hub. Our next step is to become the "official" chart.

| ↓  |  |
|-|-|
| Repository name | [cert-manager](https://artifacthub.io/packages/search?repo=cert-manager)* |
| Official packages | [cert-manager](https://artifacthub.io/packages/helm/cert-manager/cert-manager), [cert-manager-istio-csr](https://artifacthub.io/packages/helm/cert-manager/cert-manager-istio-csr) |
| Project URL | http://cert-manager.io/ |
| Source code URL | [jetstack/cert-manager](https://github.com/jetstack/cert-manager)*, [cert-manager/istio-csr](https://github.com/cert-manager/istio-csr) |

*the cert-manager project is currently hosted under the `jetstack` org, but we are in our way moving the project to the [cert-manager](https://github.com/cert-manager) org as part of the [CNCF donation process](https://github.com/cncf/toc/issues/557).

**Requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

Related:
- https://github.com/jetstack/cert-manager/issues/3513

FYI @simplyzee

**Comment by tegioz** [comment]
Done!

**Comment by maelvls** [comment]
cc @wallrj

**Comment by maelvls** [comment]
@tegioz Just wondering, is it possible to get the ["Official" badge](https://artifacthub.io/docs/topics/repositories/#official-status) for OLM releases and Krew plugins? Or is it only meant for Helm charts?

- https://artifacthub.io/packages/krew/krew-index/cert-manager:
  ![image](https://user-images.githubusercontent.com/2195781/124259474-d5fc6a80-db2e-11eb-81ce-75887123677b.png)

- https://artifacthub.io/packages/olm/community-operators/cert-manager:
  ![image](https://user-images.githubusercontent.com/2195781/124259364-b82f0580-db2e-11eb-884f-a1b3fc6ab0f9.png)

**Comment by tegioz** [comment]
Hi @maelvls 

Yes, the idea is to be able to grant it for any package kind. Maybe what it means may vary from one kind to another, so we may need to adjust a bit the definition eventually. But yes, it's possible 🙂

**Comment by maelvls** [comment]
Thanks! Let me know when it becomes possible to get the "Official" badge for Krew plugins and OLM releases 😊

**Comment by tegioz** [comment]
I think we can go for it, so please feel free to request it when you have a chance 🙂 The only problem I see right now is the `verified publisher` requirement, but given that's not possible at the moment for the special circumstances of those two repositories we could grant it for now if the others are met until this can be discussed further.
