### ISSUE TITLE
Plan roadmap for v1.0

### ISSUE THREAD

**Issue by caniszczyk** [artifacthub/hub#1293]
We should figure out what we should implement before hitting v1.0, I feel like we are getting close and underselling AH's current status.

**Comment by tegioz** [comment]
Hi @caniszczyk 

Agreed. I can't think of any important feature that's missing for v1.0. The truth is that `artifacthub.io` has been running fine for a long time without any major issue. Some features, like support for certain repository kinds, haven't been thoroughly tested in the real world yet (we have hundreds of Helm charts repositories indexed, but for some other kinds we still have only one or even zero). But maybe when publishers perceive Artifact Hub as a stable solution this will improve. We'll go over the public facing APIs to make sure they are ready for upcoming features without requiring backwards incompatible changes.

We've just created a [milestone](https://github.com/artifacthub/hub/milestone/1) to keep track of some tasks we should complete before releasing version 1.0.0. We'll keep thinking a bit more about it and we'll add more issues if needed. But I think we should be ready to go soon 🙂.

**Comment by tegioz** [comment]
Hi @caniszczyk 

All tasks in [milestone 1.0.0](https://github.com/artifacthub/hub/milestone/1?closed=1) have been completed. Some of those changes are already deployed to production, and the rest of them will be later on today after we test them a bit more in staging.

The plan is to release version `1.0.0` next week. We'll keep you posted!
