### ISSUE TITLE
Add support for Keptn Integrations

### ISSUE THREAD

**Issue by caniszczyk** [artifacthub/hub#1319]
Keptn has services available:
https://keptn.sh/docs/integrations/

It would be great if ArtifactHub supported this

**Comment by jetzlstorfer** [comment]
We are planning a facelift of our integrations website and if ArtifactHub could be the solution that would be great. However, some things need to be clarified first (on the Keptn end).

**Comment by tegioz** [comment]
This is ready (closed in #1459), we've just deployed it to production. Keptn integrations repositories can now be listed on Artifact Hub 🙂
