### ISSUE TITLE
Inaccurate search results for Apache Airflow

### ISSUE THREAD

**Issue by mik-laj** [artifacthub/hub#1363]
**Describe the bug**
We currently have several Charts for Apache Airflow.
https://artifacthub.io/packages/search?page=1&ts_query_web=airflow
Including two that have the same icon but differ by the organization that develops it.
<img width="870" alt="Screenshot 2021-05-31 at 15 44 39" src="https://user-images.githubusercontent.com/12058428/120202650-22e6db80-c227-11eb-8941-be9604153ca0.png">
https://artifacthub.io/packages/search?page=1&ts_query_web=airflow
The second has an official status, has more stars and badges, so it should appear earlier in search results than the non-official ones. This is not the case, because the badge and stars have a low weight and a marginal influence on the results.

> When indexing a package, we build a text search document from some parts of it, like the title, description, keywords, etc. Search results are primarily sorted using a relevance rank obtained from this document and, when they are the same, we consider the following criteria in this order: official, verified and stars.
>. In this particular case, the rank of the other package is slightly better (0.785 vs 0.781), so the rest of the criteria is not taken into account. This may be happening because the term airflow is being used once more in one of those sections, for example.

Slack discussion: https://cloud-native.slack.com/archives/C0103CTR3RB/p1622457654016000

CC: @Kaxil @jedcunningham

**Comment by tegioz** [comment]
We've just applied some adjustments to the search results rankings (#1370). Search results for `airflow` should now be sorted as expected.

**Comment by kaxil** [comment]
Awesome, thanks @mik-laj

**Comment by mik-laj** [comment]
Thanks @tegioz for quick fix. 🐈
