### ISSUE TITLE
[OFFICIAL] Atlassian Data Center

### ISSUE THREAD

**Issue by nanux** [artifacthub/hub#1374]
- **Repository name** *(in `artifacthub.io`)*: [Atlassian Data Center](https://artifacthub.io/packages/search?page=1&repo=atlassian-data-center)
- **Official packages**:
- **Project URL:** https://atlassian-labs.github.io/data-center-helm-charts
- **Source code URL** *(if available)*: https://github.com/atlassian-labs/data-center-helm-charts
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by nanux** [comment]
Dear maintainers, would be possible to add an Official badge to the Atlassian Data Center helm charts? There are 4 charts currently: Jira, Confluence, Bitbucket, Crowd. Please let me know if I can anyhow assist with the verification process.

**Comment by tegioz** [comment]
Hi @nanux 👋 

Your repository has been marked as official 👍
