### ISSUE TITLE
Ability to hide and customize Sample Queries

### ISSUE THREAD

**Issue by dirkmueller** [artifacthub/hub#1385]
**Is your feature request related to a problem? Please describe.**

Thank you for the theming support in the 0.20.0 release, this looks really nice! One issue that I hit in a themed custom installation is that the sample queries on the landing page as defined here: 

https://github.com/artifacthub/hub/blob/95720b74b350595a7906714a04641d6060e81a0b/web/src/layout/home/index.tsx#L120-L123

don't make a whole lot of sense, because most of those queries will lead to no results in my installation (for example the publisher bitnami does not exist, and one of the queries points to all charts from bitnami). 

**Describe the solution you'd like**

I can see a couple of options on this that would help me. one thing would be to replace the landing page with a custom template, which I can modify to my liking, including for exmaple including a custom footer or a custom layout. 

Another option would be to make the sample queries configurable, for example either in the helm chart or as a database stored configuration content. then I could just delete those that don't apply. 

Another, maybe the quickest solution is a flag to hide these sample query sections behind a conditional.

**Comment by tegioz** [comment]
Thanks @dirkmueller! We'll take care of this 👍

**Comment by tegioz** [comment]
Sample search queries can now be customized from the Helm chart. It's also possible to completely remove them from the home and the no results found pages by providing an empty list (the default).

**Comment by dirkmueller** [comment]
awesome, thank you very much!
