### ISSUE TITLE
Something went wrong scanning repository mlohr: Image not found - But image is there

### ISSUE THREAD

**Issue by MatthiasLohr** [artifacthub/hub#1387]
**Describe the bug**
After publishing a new version of one of my helm charts, I got an email "Something went wrong scanning repository mlohr" complaining
```
image not found: quay.io/k8scsi/csi-resizer:v0.3.0 (package hcloud-csi-driver:1.1.1)
image not found: quay.io/k8scsi/livenessprobe:v1.1.0 (package hcloud-csi-driver:1.1.1)
```

However, when I'm doing a manual docker pull, this works without any problems. Therefore, I suspect a problem with the image scanner or something similar. Since wrong warnings can lead to generally being ignored in future, even if then the image really cannot be found, I strongly suggest to take a look into this.

I'm not completely sure if it is actually a bug, but I still wanted to report and discuss with you why this happens and how I or you can prevent this from happen again.

**To Reproduce**
I don't know any reliable way to reproduce this problem. However, I got this warnings for two consecutive version updates of my helm chart.

**Expected behavior**
If I am able to pull the image, the scanner should be able to pull as well. If there are connection problems/rate limitations of the scanner, it should **not** warn the helm chart owner but just try again later.

**Screenshots**
Original mail screenshot:
![image](https://user-images.githubusercontent.com/781926/121852091-42820780-ccef-11eb-96e9-3ed3b1b83e69.png)

**Comment by tegioz** [comment]
Hi @MatthiasLohr 👋 

Thanks for reporting this. Artifact Hub relies on [Trivy](https://github.com/aquasecurity/trivy) to scan containers images for security vulnerabilities. I've been able to reproduce this by running `trivy` from the cli:

```
trivy image quay.io/k8scsi/csi-resizer:v0.3.0                                                                                                         1 ✘  09:04:27 
2021-06-14T09:08:58.018+0200	FATAL	scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
	* unable to inspect the image (quay.io/k8scsi/csi-resizer:v0.3.0): Error: No such image: quay.io/k8scsi/csi-resizer:v0.3.0
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
```

I suspect the reason behind this issue is that the image is using a `v1` schema (3rd point of the cli output), which is not supported by Trivy (please see: https://github.com/aquasecurity/trivy/issues/401#issuecomment-617657184).

**Comment by tegioz** [comment]
I can see how the error we display can be misleading though. We oversimplified the error returned from `trivy` in an attempt to make users' lives easier, but we should probably return it in full to give users a better chance of catching what's going on.

**Comment by MatthiasLohr** [comment]
Most probably, yes. For my understanding, the message "image not found" is just not true. I'm also not a fan of trivy's" "No, we do not support what so many people are using"-approach, so... would also raise the question if trivy is the only way to scan a Docker image - But I guess that's far beyond the scope of this issue.

Summarized: Situation stated by ArtifactHub email ("image not found") does not match real world, this should be improved in my opinion.

**Comment by tegioz** [comment]
This is fixed @MatthiasLohr. Once this is deployed, scanning errors logs should display something like this:

<img width="2009" alt="Screen Shot 2021-06-14 at 10 04 19" src="https://user-images.githubusercontent.com/1213902/121862435-15d3ed00-ccfb-11eb-878a-1a5f67722222.png">

**Comment by tegioz** [comment]
Regarding your question about considering other tools to scan containers images: at the moment we don't have plans for it, as we are quite happy with Trivy, no issues with it so far 🙂

**Comment by MatthiasLohr** [comment]
Thanks for fixing/improving the message so quickly. However, maybe still worth an upstream issue, since I find the Trivy message quite unreadable. Maybe you could also create an Opt-out for image scanning per chart base?

**Comment by tegioz** [comment]
No worries. You can already whitelist specific images so that they are not scanned for security vulnerabilities. This requires to provide the containers images manually using a special annotation in the `Chart.yaml` file. Please see the `artifacthub.io/images` annotation in https://artifacthub.io/docs/topics/annotations/helm/.

**Comment by MatthiasLohr** [comment]
Didn't know about that! Thanks for pointing out!
