### ISSUE TITLE
Enable searching for an exact repo+chart combination

### ISSUE THREAD

**Issue by lindhe** [artifacthub/hub#1392]
**Is your feature request related to a problem? Please describe.**
I think it would be useful to be able to search for an exact chart, i.e. including which repo the chart is from.

Currently, if I search for `grafana` there's [loads of suggestions](https://artifacthub.io/packages/search?page=1&ts_query_web=grafana) (which is good). But if I know that the specific variant of grafana that I want is from the `bitnami` repo, it would be really nice to get there in one go.

**Describe the solution you'd like**
I would like to be able to search for `bitnami/grafana` and get to <https://artifacthub.io/packages/helm/bitnami/grafana> instead of leaving me with [no results at all](https://artifacthub.io/packages/search?page=1&ts_query_web=bitnami%2Fgrafana):

![0 results for "bitnami/grafana"](https://user-images.githubusercontent.com/7773090/121956932-020fa180-cd62-11eb-8abe-0d3e27d9211a.png)

**Describe alternatives you've considered**
Many search engines (DuckDuckGo, Google and others) implement a [syntax](https://help.duckduckgo.com/duckduckgo-help-pages/results/syntax/) for their queries to filter on specific domains or filetypes. That could be an alternative to my main suggestion, and would look something like `grafana repo:bitnami` but I don't like it as much. However, the two styles are compatible, so I'm not against implementing both.

The killer feature with the `foo/bar` style is that it's the same convention that Helm uses for installing charts. So users are likely to already have `bitnami/grafana` in their bash history and can just copy-and-paste that bit into ArtifactHUB.

**Additional context**
This could be a duplicate of #1197, but it's impossible to tell since it has no information it it other than the title. :)

**Comment by tegioz** [comment]
Hi @lindhe 👋 

I think the search you describe is kind of possible right now, although not using exactly that syntax. For every package version, we build a search document that includes the repository name. This makes it possible to create rich queries(*) using multiple search terms.

**Example 1: `grafana bitnami` or `bitnami grafana`**

This search will produce only two results, allowing you to go quickly to the one you're interested in.

<img width="2010" alt="Screen Shot 2021-06-15 at 08 08 50" src="https://user-images.githubusercontent.com/1213902/122001658-f13a4c80-cdb0-11eb-9e3c-a88720be0fff.png">

**Example 2: similar query using the `typeahead`**

This one may be even better for your use case, as it allows you to go directly to the package page you're interested in, skipping the search results view. You just need to start typing the same query and hold on a few milliseconds until it pops up.

<img width="2010" alt="Screen Shot 2021-06-15 at 08 11 41" src="https://user-images.githubusercontent.com/1213902/122001908-53934d00-cdb1-11eb-882c-dd4599dd2597.png">

If possible, I think we should try to handle generic operations (like searching) in a way that's not tied to the conventions of any particular package kind. At the moment we already support 9 kinds (Helm charts would be one of them), with probably more to come soon 🙂 

(*) it's possible to exclude some terms, running queries like this `grafana bitnami - operator`, use double quotes to find packages with an exact combination of terms, etc. You can see some more examples by clicking on the interrogation icon next to the search input box.

**Comment by lindhe** [comment]
Ah, right. I didn't know and/or consider that you support more package types than Helm. Well, that pretty much messes up my main argument.

I guess we'll leave it as-is then. Thanks for the tip about `typeahead`!

**Comment by tegioz** [comment]
Cool, no worries! 👍
