### ISSUE TITLE
CNCF Incubation

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#1418]
This issue is to track proposing the [incubation stage](https://github.com/cncf/toc/blob/main/process/graduation_criteria.adoc#incubating-stage) for AH.

**Comment by mattfarina** [comment]
Here are some examples of projects that have or are going through the incubation process:

- Flux moved last March. https://github.com/cncf/toc/pull/567 Note, this is prior to [the incubation process being streamlined](https://github.com/cncf/toc/pull/640).
- KEDA is currently in flight with issue https://github.com/cncf/toc/issues/621 and PR https://github.com/cncf/toc/pull/622
- Cilium is also in progress with PR https://github.com/cncf/toc/pull/637
- Keptn is in progress with PR at https://github.com/cncf/toc/pull/670
- Cloud Custodian is another example with PR https://github.com/cncf/toc/pull/644

The [incubation process is documented here](https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#incubation-process).

Both Keptn and Cloud Custodian have example PRs that look like a good example. There is no template for incubation PRs.

We need to make sure we meet all the requirements. Need to make sure the following are complete:

- [ ] Clearly documented security processes explaining how to report security issues to the project, and describing how the project provides updated releases or patches to resolve security vulnerabilities
- [ ] A clear versioning scheme. (note, is this documented)
- [ ] Document that it is being used successfully in production by at least three independent end users... (note, we will have a different method for showing this from most other projects so we need to make this clear)

**Comment by tegioz** [comment]
The Artifact Hub incubation proposal has been accepted! 🎉
