### ISSUE TITLE
Create screen to test artifacts before they are uploaded to official locations.

### ISSUE THREAD

**Issue by HoustonPutman** [artifacthub/hub#1428]
**Is your feature request related to a problem? Please describe.**
As a part of the Solr Operator, we have a release process that puts release candidate helm charts into a separate location for users to use and try before the candidate is approved. We don't want to put the candidates into the official helm repo before they are approved, so that users don't start relying on non-official charts.

However the issue arises that we can't then incorporate the ArtifactHub page into the release-candidate validation. Last release we had issues with the formatting of the annotations, which we couldn't see was an issue until the candidate passed and the official release was made. When the release was added to the official helm repo, ArtifactHub was rejecting the new chart. It was a painful process to make changes to the already-released helm chart, to make it validate with ArtifactHub.

**Describe the solution you'd like**
It would be wonderful to be able to have a page on ArtifactHub to load in a helm repo, and browse the available charts (artifacts). This wouldn't store anything in the ArtifactHub website, it would merely show you how a non-stored repo would look if it were added to artifactHub.

**Describe alternatives you've considered**
We would have to create a separate Helm repo in ArtifactHub for each release candidate, and delete it once the candidate passes. This isn't optimal, since we don't want users seeing this repo when looking through ArtifactHub to find the official offerings.

**Comment by HoustonPutman** [comment]
It would also be very cool to be able to upload a local helm chart and test that too.

Both options would be great, but I would certainly settle for either of them.

**Comment by tegioz** [comment]
Hi @HoustonPutman 

I know you've mentioned that you'd rather not putting the candidates in the same repo, but just in case you didn't know there is a way to mark specific chart versions as `pre-release` using an annotation. They still show up in Artifact Hub, but a `pre-release` label is displayed and in the installation modal users are warned that this is a pre-release version non intended for production usage.

I agree that being able to make sure that a given package is Artifact Hub ready before publishing it can be something valuable. However, I think that having a visual tool to handle this can be a bit overkill and will probably add a considerable amount of complexity. At the moment, there are actually a couple of ways you can handle this:

- You can use [staging.artifacthub.io](staging.artifacthub.io) and consider it a playground. Data there is overwritten every now and then, but as a quick way to test how something looks like can be handy.

- Another way is to run an internal Artifact Hub instance. It can be easily installed using the [provided Helm chart](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub). This way you can play around and see how everything works before releasing a specific version.

I'm thinking that another option would be to create a CLI tool for validation, to make sure a given repo (any of the supported kinds) is Artifact Hub ready, letting publishers know about any potential warnings or errors before it's too late. One of the benefits of this approach would be that it'd be easier to automate and integrate in CI workflows. What do you think?

**Comment by HoustonPutman** [comment]
Thanks for the thorough response @tegioz!

Ahh I had hoped that adding a check-UI page would be relatively simple and could re-use a lot of code. That's unfortunate, but the suggestions you gave are definitely feasible!

The staging website is definitely a good option for now. Adding the pre-release charts just really isn't an option for the way that Apache handles release artifacts, or at least the way our project handles ours. I've seen the tag, and it does make sense for the way a lot of projects work though!

I think the CLI would be great for the future! We would certainly include it in our CI workflow and release process. That would _probably_ be even better than the UI option. Especially if you can do things like `hub-check verify`, `hub-check view change-list` or `hub-check view links`. That would be beyond valuable, and really make our PR merges and releases safe and trusted!

**Comment by tegioz** [comment]
> I think the CLI would be great for the future! We would certainly include it in our CI workflow and release process. That would _probably_ be even better than the UI option. Especially if you can do things like `hub-check verify`, `hub-check view change-list` or `hub-check view links`. That would be beyond valuable, and really make our PR merges and releases safe and trusted!

Awesome, I think we'll work on this then, thanks! 👍

**Comment by tegioz** [comment]
Quick sneak peek 🙂 

<img width="1438" alt="success" src="https://user-images.githubusercontent.com/1213902/126212042-10d2032a-9c26-45a3-a452-f65437363d14.png">

<img width="1438" alt="failure" src="https://user-images.githubusercontent.com/1213902/126212055-c6ff2c99-74a2-45e9-b19c-1d04939fc4fb.png">

At the moment, the command does not succeed if errors are found in any of the packages found.

**Comment by HoustonPutman** [comment]
This looks incredible!!

Thanks for the awesome work, can't wait to integrate it into our workflow!

Do you envision publishing a docker image, binary, or both for this?

**Comment by tegioz** [comment]
Awesome! I think this first version is ready to go, I'll probably merge the PR now 🙂 

I was thinking on a docker image, but I'm happy to publish it either way.

**Comment by tegioz** [comment]
I'll integrate it tomorrow with our CI workflow to give it a try 😇 Will let you know when it's done!

**Comment by tegioz** [comment]
It's ready @HoustonPutman 🙂 Please see https://github.com/artifacthub/hub/pull/1449/files for more details.

<img width="2103" alt="ah-lint-ok" src="https://user-images.githubusercontent.com/1213902/126621180-ca8cf14f-71aa-417b-afb1-d241ce59a53e.png">

<img width="2103" alt="ah-lint-error" src="https://user-images.githubusercontent.com/1213902/126621196-85d39275-7370-457f-b8d3-36a6c8d12ba2.png">

**Comment by HoustonPutman** [comment]
This is absolutely amazing. I wanted to include it in local development steps as well, so that it doesn't surprise people when it fails on PRs. You can see the addition here: https://github.com/apache/solr-operator/pull/298

It works like an absolute charm! And it does multiple charts at the same time just like `helm lint`. 🎉 

I'm blown away by how amazing this is and how fast y'all got it done.
I seriously appreciate the awesome work y'all do, thank you so much!

**Comment by tegioz** [comment]
Thank you for your kind words, we are glad you like it 😊

Please let us know if something doesn't work as expected or if you have ideas for future improvements 😉
