### ISSUE TITLE
Error when trying to get values schema from the Official Airflow Helm Chart

### ISSUE THREAD

**Issue by potiuk** [artifacthub/hub#1455]
**Describe the bug**
I get an rrror when trying to get values schema from the Official Airflow Helm Chart. No details about the error, just link to create an issue here,

**To Reproduce**
1. Go to https://artifacthub.io/packages/helm/apache-airflow/airflow
2. Click on "Values Schema"
3. See error

**Expected behavior**
I expect to see the schema

**Screenshots**

![Screenshot 2021-07-27 09 12 47](https://user-images.githubusercontent.com/595491/127111732-2041a622-a8ff-4fa5-9670-0742a821ea39.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 91.0

**Additional context**

Airlfow Helm Chart has Json Schema as part of the package: 

https://github.com/apache/airflow/blob/main/chart/values.schema.json

**Comment by potiuk** [comment]
cc: @kaxil

**Comment by cynthia-sg** [comment]
Thanks for reporting this issue @potiuk. We just fixed it, we’ll deploy it later today :)

**Comment by potiuk** [comment]
Cool :)

**Comment by kaxil** [comment]
Thanks
