### ISSUE TITLE
Easy Install of ah binary

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#1476]
**Is your feature request related to a problem? Please describe.**
I would like an easy method to install the `ah` binary on mac, windows, and linux. This way I can use it as a linter locally during development in addition to using the container image in CI.

**Describe the solution you'd like**
I would like to be able to install the CLI using the common methods. For example,

- Using brew to install `ah` via a [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#creating-a-tap). Something like `brew install artifacthub/cli/ah`
- Using [choco](https://chocolatey.org/) to install `ah` on Windows. Something like `choco install ah`.
- A direct binary download for those cases where there is no general package manager.

**Describe alternatives you've considered**
I've considered downloading and compiling the source to get a binary. This would require someone to have a Go compiler installed and know Go. Many people who work with packages listed on ArtifactHub aren't Go developers.

**Additional context**
N/A

**Comment by tegioz** [comment]
This is ready @mattfarina. Please see the [documentation](https://artifacthub.io/docs/topics/cli/) for more details.
