### ISSUE TITLE
Tekton Pipelines as Category

### ISSUE THREAD

**Issue by oliverbaehler** [artifacthub/hub#1485]
**Is your feature request related to a problem? Please describe.**
Currently on Artifacthub it's supported to register Tekton Tasks. That's already a great. But I can also see the Use-Case, that you would want to publish entire Tekton Pipelines (which implement Tasks):

- https://tekton.dev/docs/pipelines/pipelines/#adding-tasks-to-the-pipeline

I am not sure if it makes sense, since it could be more complex, if a pipeline requires Jobs which are also published on Artifacthub. That would lead to some kind of dependency management for Tekton Pipelines and referenced Tasks. >But you could just simple state in the documentation which Tasks are recommended.

It was just an idea, i don't know if it's that useful. What do you think about it?

**Describe the solution you'd like**
Tekton Pipelines as distinct Artifact Category.

**Describe alternatives you've considered**
Sharing Tekton Pipelines as pure YAML to consumers or as resource on the kubernetes cluster.

**Additional context**

**Comment by tegioz** [comment]
Hi @oliverbaehler 👋

This sounds interesting, we'll look into it 👍

Thanks!

**Comment by tegioz** [comment]
It's ready @oliverbaehler 🙂 Thanks!

<img width="2009" alt="pipelines" src="https://user-images.githubusercontent.com/1213902/133795103-ad4c03a9-e26b-4e61-bb9e-7f1d8093d70a.png">
