### ISSUE TITLE
Nested Helm chart within a Github repo, would we need to create a README.md within the folder where chart exists?

### ISSUE THREAD

**Issue by david-yu** [artifacthub/hub#1486]
**Describe the bug**

This is actually a question instead of bug. Our Helm chart is now nested within a Github repo under a `charts` folder. Our current Chart.yaml is described here: https://github.com/hashicorp/consul-k8s/blob/master/charts/consul/Chart.yaml. I just wanted to confirm, would we just need to create a README.md under that same directory to show up in our Artifhub homepage? https://artifacthub.io/packages/helm/hashicorp/consul

**Comment by tegioz** [comment]
Hi @david-yu 👋 

For Helm charts, Artifact Hub uses the README.md file available in the `.tgz` [chart package file](https://helm.sh/docs/topics/charts/#the-chart-file-structure) referenced in the Helm repository `index.yaml` file. In this case, these would be the latest two versions available in Artifact Hub:

https://helm.releases.hashicorp.com/consul-0.33.0.tgz
https://helm.releases.hashicorp.com/consul-0.32.1.tgz

Version `0.32.1` contains the README.md file but version `0.33.0` doesn't seem to include it anymore.

I think it's a good idea to have a Helm chart specific README.md file under the same directory as you mentioned. But if you prefer keeping it centralized in a different location, please make sure it's included in the chart version `.tgz` file when it's packaged.

**Comment by david-yu** [comment]
Ok got it thank you!
