### ISSUE TITLE
how can i get Most popular charts with stars

### ISSUE THREAD

**Issue by willzhang** [artifacthub/hub#1494]
can you support Sort by stars?
Which application is the most star charts? I want to know. It's very interesting
High quality charts can be obtained by referring to stars

**Comment by tegioz** [comment]
Hi @willzhang 👋 

Artifact Hub already supports sorting by starts 🙂 

When you browse all packages available or you filter them by using the filters on the left column, the results are sorted by stars:

<img width="1285" alt="Screen Shot 2021-08-18 at 08 14 26" src="https://user-images.githubusercontent.com/1213902/129847415-ef2265fd-7469-48a8-b175-caa5161962c4.png">

<img width="2039" alt="Screen Shot 2021-08-18 at 08 14 52" src="https://user-images.githubusercontent.com/1213902/129847427-b0e2464e-e488-459b-b2ae-2b86e40317fc.png">

If you try to search for any term, by default results are sorted by relevance, but you can sort by stars as well by using the selector on the top right:

<img width="2039" alt="Screen Shot 2021-08-18 at 08 15 18" src="https://user-images.githubusercontent.com/1213902/129847578-d1f1857a-ea49-43dc-a50c-a1e56f94355e.png">

Hope this helps 👍
