### ISSUE TITLE
ah container image in GHCR

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#1510]
**Is your feature request related to a problem? Please describe.**
Pulling the the [ah container image from Docker Hub](https://hub.docker.com/r/artifacthub/ah/tags) is a problem due to their rate limiting. This is ok sometimes and causes issues other times.

**Describe the solution you'd like**
It would be wonderful if the ah container image were also available in the GitHub Container Registry.

**Describe alternatives you've considered**
I'd considered Quay and other container registries. But, GHCR would put it alongside our other images and make management similar to the ones we have today.

**Additional context**
N/A

**Comment by tegioz** [comment]
Docker images are now published to ECR Public Gallery too @mattfarina:

https://github.com/artifacthub/hub/releases/tag/v1.2.0

**Comment by tegioz** [comment]
https://gallery.ecr.aws/artifacthub/
