### ISSUE TITLE
SMTP not working for MS O365 accounts

### ISSUE THREAD

**Issue by sknopp** [artifacthub/hub#1517]
**Describe the bug**
When using MS Office365 SMTP-Server credentials within the `values.yaml` one gets an error saying the following:

```
{"level":"error","cmd":"hub","handlers":"user","error":"504 5.7.4 Unrecognized authentication type [REDACTED_HOST.eurprd07.prod.outlook.com]","method":"RegisterUser","time":"2021-08-31T14:33:14Z"}
```

This seems like a problem with missing STARTTLS setting which i'm not able to configure.

**To Reproduce**
1. Configure SMTP-Server as required by Microsoft ([see link here](https://support.microsoft.com/de-de/office/pop-imap-und-smtp-einstellungen-8361e398-8af4-4e97-b147-6c6c4ac95353))
2. register a new user account
3. read error messages from `kubectl logs REDACTED_POD_NAME`

**Expected behavior**
A registration mail should be sent to the new user.

**Screenshots**

**Additional context**
Run from within an Azure Kubernetes Cluster (AKS)

**Comment by tegioz** [comment]
Hi @sknopp 👋

[Outlook.com does not support AUTH PLAIN authentication](https://support.microsoft.com/en-us/office/outlook-com-no-longer-supports-auth-plain-authentication-07f7d5e9-1697-465f-84d2-4513d4ff0145?ui=en-us&rs=en-us&ad=us), which is the only mechanism that Artifact Hub supported until now. We've just added support for `AUTH LOGIN`, which should fix this issue. You can provide this [new smtp auth mechanism to the Helm chart](https://github.com/artifacthub/hub/pull/1525/files#diff-31ec94cd998d4fc96c6b831ab850960d9445ee126653fbdb9d5a0e18808870b3) as usual.
