### ISSUE TITLE
OpenID OAuth not working on Azure AAD

### ISSUE THREAD

**Issue by sknopp** [artifacthub/hub#1527]
**Describe the bug**
When one tries to integrate oauth OIDC feature with Azure AAD the login always fails with the following error message of the callback handler:

```
{"level":"error","cmd":"hub","handlers":"user","method":"OauthCallback","error":"no valid email available for use","time":"2021-09-01T14:51:01Z","message":"oauth code exchange failed"}
```

This seems to be related to the [login function check here](https://github.com/artifacthub/hub/blob/0a76c5afce0e9f2ccd6080340d02d13b4ca5830f/internal/handlers/user/handlers.go#L771).
The handler requires an `email_verified` claim field but this is simply not available within Azure AAD and as far as i can say there is no possibility to add static claim values from Azure's site. Therefore the check is always failing.

**To Reproduce**
1. Create an App registration within your Azure AAD tenant with the following configuration
![openid2](https://user-images.githubusercontent.com/10382820/131695907-aaa4f5d2-d769-4eee-b5d7-af77a1d4c0c6.png)
![openid1](https://user-images.githubusercontent.com/10382820/131695917-22e504e2-cbb7-4c28-aa31-a01326a8b858.png)
![openid3](https://user-images.githubusercontent.com/10382820/131695923-1d6adefe-37ba-4de2-ae41-c70ccf737e09.png)
2. configure your Artifact hub with the following oauth values
![openid5](https://user-images.githubusercontent.com/10382820/131696383-d2a83646-b64e-4e34-97ac-aff6e8dd6e1f.png)
3. try to login
4. see error message in browser and check pod logs

**Expected behavior**
A login should succeed and an new account based on the Azure credentials should be created.

**Screenshots**
![openid4](https://user-images.githubusercontent.com/10382820/131696588-f1191a30-a779-4745-b09f-7a2beb5338cd.png)

**Additional context**
Run from within an Azure Kubernetes Cluster (AKS)

**Comment by tegioz** [comment]
Hi @sknopp 👋 

You can now optionally skip the email verified check. This should help when connecting to OIDC providers that don't support the [`email_verified` claim](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), like Azure AD.

**Comment by sknopp** [comment]
hi @tegioz 
thanks for the fast response and resolve of the issue! When would the change be available on Docker Hub and Artifact Hub? Or do i need to check it out somehow else.

**Comment by tegioz** [comment]
No worries! We'll probably release a new version within the next few days, hopefully before the end of the week.
