### ISSUE TITLE
Request for ownership of organization named `alvearie`

### ISSUE THREAD

**Issue by lmsurpre** [artifacthub/hub#1535]
I am an admin of https://github.com/Alvearie and I want to publish a chart repo at artifacthub.io.

I tried to create an organization by the same name but it turns out this name was already registered by a previous admin of our GitHub org and that user, @eggebraa, is no longer working with us.  We reached out to him but, since he can no longer access the email associated with his account, he was unable to access his account on either Github or ArtifactHub.

Can someone please add me (lmsurpre) as an admin of the organization `alvearie` on artifacthub.io so that I can properly manage this organization?

PS. there is an existing process for claiming ownership over a particular repo, but no process yet for claiming ownership of an org name... hence I reached out on slack and @tegioz recommended I open an issue to manually resolve this one.

**Comment by lmsurpre** [comment]
As proof of ownership for this github org, i've temporarily created a repo at https://github.com/Alvearie/proof-for-artifacthub-hub-issues-1535 ...will delete when the request is processed.

**Comment by tegioz** [comment]
Thanks @lmsurpre. You've just been added to the `alvearie` organization.
