### ISSUE TITLE
[OFFICIAL] SonarQube

### ISSUE THREAD

**Issue by tobias-trabelsi-sonarsource** [artifacthub/hub#1546]
Hello there :wave: 

we (SonarSource, the company behind SonarQube) would like to mark our helm charts official on artifacthub. I hope i filled the requested information correctly :sweat_smile: 

- **Repository name** *(in `artifacthub.io`)*: [sonarqube](https://artifacthub.io/packages/search?repo=sonarqube)
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://www.sonarqube.org/
- **Source code URL**: https://github.com/SonarSource/helm-chart-sonarqube
- **Other relevant URLs:** 
  - https://github.com/SonarSource/docker-sonarqube
  - https://github.com/SonarSource/sonarqube
  - https://jira.sonarsource.com/browse/MMF-2391

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @tobias-trabelsi-sonarsource 👋 

Everything looks great, thanks. The repository has just been marked as official 🙂
