### ISSUE TITLE
Duplicated Bitnami charts by a non-verified user

### ISSUE THREAD

**Issue by carrodher** [artifacthub/hub#1557]
From Bitnami, we are synchronizing the charts present in the Bitnami public Helm repository into the ArtifactHUB, see https://artifacthub.io/packages/search?repo=bitnami&sort=relevance&page=1; those charts are hosted at `https://charts.bitnami.com/bitnami`.

Bitnami charts are also present in other repositories like Azure Marketplace (`https://marketplace.azurecr.io/helm/v1/repo`). Basically, the difference is that charts pushed to this repository use a custom image registry to pull the images from the Azure registry:
```yaml
global:
  imageRegistry: marketplace.azurecr.io
```

Recently we discovered there is a user copying the charts from the Bitnami Azure Marketplace repository, see https://artifacthub.io/packages/search?repo=bitnami-aks&sort=relevance&page=1. We found [this doc](https://artifacthub.io/docs/topics/repositories/#ownership-claim) about claiming ownership of a repository, but in this case, it is not only about the ownership but also the utility to have duplicated charts since the only difference is the image registry.

Is there any way to not show those charts in the Hub? Not sure what is the right process for this kind of issue, if there is another way please let me know.

**Comment by tegioz** [comment]
Hi @carrodher 👋 

Thanks for bringing this up. Listing identical charts multiple times on Artifact Hub may confuse users, so I agree we should do our best to avoid that whenever possible.

If you have control over the `https://marketplace.azurecr.io/helm/v1/repo` repo, you could claim its ownership and then disable it from the Artifact Hub control panel (repositories tab -> edit repository). This way no content from it will be displayed on Artifact Hub and we won't process it anymore until you enable it back.

Hope this helps. Please let me know if you run into any issue during the process.

**Comment by carrodher** [comment]
Thanks for the info @tegioz, I will try to follow the process described [here](https://artifacthub.io/docs/topics/repositories/#ownership-claim) (mainly put an `artifacthub-repo.yml` file at the same level as the _index.yaml_) and then disable it once it belongs to our organization

**Comment by tegioz** [comment]
No worries! Yes, that's right. It's [the same file you added](https://charts.bitnami.com/bitnami/artifacthub-repo.yml) to get the `verified publisher` status for the Bitnami repo, you just need to make sure that the email of the user claiming the ownership from the Artifact Hub UI is listed on it.

**Comment by carrodher** [comment]
Thanks again, we will check what it's needed on our side to follow that process. Thanks for the clarification, I'm closing the issue since no further action is needed

**Comment by tegioz** [comment]
Awesome 👍 Don't hesitate pinging me if you need any help 👋
