### ISSUE TITLE
Access for Public Comment via CNCF TOC PR for Sandbox Status

### ISSUE THREAD

**Issue by dmueller2001** [artifacthub/hub#156]
Let us know when you make the CNCF TOC PR for Sandbox Status for this rebranded helm chart-based hub project and make the code available for public comment. We'll review to ensure it supports all the operator packaging patterns including Operator Framework, Kubebuilder/Kudo, Rudr and others that are currently under development. @mattfarina @dankohn

**Comment by mattfarina** [comment]
Sorry I didn't get around to this sooner. The things have been through the sandbox new process and Artifact Hub has been accepted.

At this point the OLM based operators are supported.

Closing as the Sandbox status is already worked out. If there is something further a new issue would be great.
