### ISSUE TITLE
Become a verifyied publisher with a gitlab repo

### ISSUE THREAD

**Issue by xrow** [artifacthub/hub#1617]
**Is your feature request related to a problem? Please describe.**

In https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml it is mentioned that you become a verified publisher when adding this file to your repo. You can`t add this file to a gitlab helm repo. 

In the gitlab it is documented how you can add charts, but you can`t add anything else.

https://docs.gitlab.com/ee/user/packages/helm_repository/index.html

**Describe the solution you'd like**

I want a failproved way of becoming a publisher. Maybe an alternative.

**Describe alternatives you've considered**

None

**Additional context**

* https://docs.gitlab.com/ee/user/packages/helm_repository/index.html

**Comment by tegioz** [comment]
Hi @xrow 👋

The following Helm repositories are being served from Gitlab and have become verified publishers, maybe you can check them out to see how they've added the repository metadata file.

https://artifacthub.io/packages/search?repo=gitlab
https://artifacthub.io/packages/search?repo=cardano-kstack
https://artifacthub.io/packages/search?repo=av1o-charts

Hope this helps.

**Comment by xrow** [comment]
I have seen how you do it with oci. HAve not testet that with the gitlab internal oci registry. https://medium.com/@msvechla/distributing-helm-charts-via-gitlab-container-registry-a87ed2893647

```
oras push \
  oci://registry/namespace/chart-name:artifacthub.io \
  --manifest-config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
  artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml
```

**Comment by tegioz** [comment]
> @tegioz
> 
> Thanks for the hint. They do it via https://tobiasmaier.info/posts/2018/03/13/hosting-helm-repo-on-gitlab-pages.html and gitlab.io. Which is not the integrated new gitlab helm repository as seen from my link.

No worries 👍 

Unfortunately if the Helm hosting solution used doesn't allow serving arbitrary files, you may not be able to make it work.

**Comment by tegioz** [comment]
> I have seen how you do it with oci. HAve not testet that with the gitlab internal oci registry. 
>
> oras push \
>   oci://registry/namespace/chart-name:artifacthub.io \
>   --manifest-config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
>   artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml
> ```

Cool. We added this feature recently, hope it works fine for you if it's a valid option 👍
