### ISSUE TITLE
Support self-hosted gitlab repo

### ISSUE THREAD

**Issue by erhwenkuo** [artifacthub/hub#1626]
**Is your feature request related to a problem? Please describe.**

For many enterprises, they need to host gitlab repo privately to comply compliance regulation. Artifacthub could be hosted in private, however it only allows to index public github&gitlab repo.

**Describe the solution you'd like**

Allow ArtifactHub to index self-hosted gitlab repo (make the regex for repo url-check configurable). This feature is needed for many enterprise in order to host a private ArtifactHub.

**Comment by tegioz** [comment]
That sounds awesome! 🎉 

Thanks 🙂
