### ISSUE TITLE
Bitnami charts published multiple times

### ISSUE THREAD

**Issue by carrodher** [artifacthub/hub#1653]
**Describe the problem**
Something similar to what we are addressing as part of https://github.com/artifacthub/hub/issues/1557 was found for another repo.

There is an organization called [“riftbit”](https://artifacthub.io/packages/search?repo=riftbit&sort=relevance&page=1) (that appears as a **Verified Publisher**) containing 52 charts in the repo; 46 of them (88%) are copied from Bitnami (same logo, same version, same README, etc, i.e [cert-manager](https://artifacthub.io/packages/helm/riftbit/cert-manager))

In this case, it’s different than the process we started at https://github.com/artifacthub/hub/issues/1557, in the previous case the user is directly using a Helm repo where he is not the owner so we are claiming the ownership; but in this case, we can’t claim the ownership of the repo because the user is pushing the Bitnami charts to his own repo by doing something like
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm fetch bitnami/cert-manager

$ helm repo add riftbit https://charts.riftbit.com/
$ helm push ./cert-manager riftbit
```

Taking a look at one of the charts pushed in that repo we can see that everything points to Bitnami:
```console
$ helm repo add riftbit https://charts.riftbit.com/
$ helm fetch riftbit/cert-manager --untar

$ ag 'bitnami' cert-manager | wc -l
62

$ cat cert-manager/Chart.yaml
...
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: cert-manager
sources:
- https://github.com/bitnami/bitnami-docker-cert-manager
- https://github.com/bitnami/bitnami-docker-cert-manager-webhook
- https://github.com/bitnami/bitnami-docker-cainjector
- https://github.com/jetstack/cert-manager
version: 0.1.20
```

What should we do in this case? It is confusing for users looking for example "Kafka" that several similar charts appear, all of them pointing to Bitnami charts (even some of the as Verified Publisher), while only one is the real bitnami/kafka chart:

![Screenshot 2021-10-25 at 14 43 34](https://user-images.githubusercontent.com/13216600/138702530-d71ab1d0-acdc-474c-9252-661f26d7bf2e.png)

The first three charts appearing in that view are pointing to bitnami/kafka chart but pushed to different repos in one or another way.

**Comment by tegioz** [comment]
Related to #1823

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
