### ISSUE TITLE
JSON Schema fails to render

### ISSUE THREAD

**Issue by No9** [artifacthub/hub#1664]
**Describe the bug**
The JSON schema file for https://artifacthub.io/packages/helm/core-dump-handler/core-dump-handler fails to render.
It validates properly with `helm template validation-test .`
Schema document is available here 
https://github.com/IBM/core-dump-handler/blob/main/charts/core-dump-handler/values.schema.json
**N.B** the file contains conditionals

**To Reproduce**
1. Go to https://artifacthub.io/packages/helm/core-dump-handler/core-dump-handler
2. Click on VALUES SCHEMA button
3. Pop up shows but no data is displayed it just has a single black box with no content.
4. No additional detail in the browser console was found.

**Expected behavior**
The JSON schema document should render

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox 
 - Version 91.2.0esr (64-bit)

**Comment by tegioz** [comment]
Thanks for reporting this issue @No9. It's been fixed by #1665, which has just been deployed.
