### ISSUE TITLE
Helm Gitlab Installtion with External PostgreSQL Database

### ISSUE THREAD

**Issue by SridharRamamoorthy** [artifacthub/hub#1681]
Hi Support team,

I have been trying to install Helm Gitlab with External PostgreSQL Database since few days back. The Gitlab Service pods not getting up. And logs are also not generated because pods does not get running. 
But when I try with embedded Database, Gitlab Service is running.
Kindly provide your support to resolve this issue. Thanking you.

I am using Helm Chart version 5.4.2 and Gitlab Version 14.4.2 and External PostgreSQL Version 11.0

helm upgrade --install --debug gitlab  --values gitlabvalues.yaml gitlab/gitlab --timeout 600s \
--set nginx-ingress.enabled=false \
--set global.ingress.class=azure/application-gateway \
--set postgresql.install=false \
--set global.psql.host=gitlab-ingress-test.postgres.database.azure.com \
--set global.psql.password.useSecret=true  \
--set global.psql.password.secret=db-user-pass \
--set global.psql.password.key=password \
--namespace gitlab --create-namespace

**Comment by tegioz** [comment]
Hi @SridharRamamoorthy 👋 

For issues with the content listed on artifacthub.io it's best to contact the particular project directly. 

Maybe this link helps in this particular case:

https://gitlab.com/gitlab-org/charts/gitlab/-/issues
