### ISSUE TITLE
helm/prometheus-msteams has wrong repo url

### ISSUE THREAD

**Issue by viceice** [artifacthub/hub#1688]
**Describe the bug**
`helm/prometheus-msteams` chart has wrong repo url.

https://artifacthub.io/packages/helm/prometheus-msteams/prometheus-msteams

old: https://prometheus-msteams.github.io/helm-chart/
new: https://prometheus-msteams.github.io/prometheus-msteams

https://github.com/prometheus-msteams/prometheus-msteams/blob/master/chart/prometheus-msteams/README.md#download-the-chart

**To Reproduce**
1. Go to 'https://artifacthub.io/packages/helm/prometheus-msteams/prometheus-msteams'
2. Check the install instructions

**Expected behavior**
It should show the new url and newer releases, currently [v1.3.0](https://github.com/prometheus-msteams/prometheus-msteams/releases/tag/prometheus-msteams-1.3.0)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by viceice** [comment]
I've created a new repo as workaround: https://artifacthub.io/packages/helm/prometheus-msteams-new/prometheus-msteams

**Comment by tegioz** [comment]
Hi @viceice 👋 

Thanks for reporting this. If you don't mind deleting the one you created as a workaround I'll fix it (repo urls must be unique).

If you belong to the `prometheus-msteams` team you could also [claim the ownership](https://artifacthub.io/docs/topics/repositories/#ownership-claim) of the repository and update the url from the control panel.

**Comment by viceice** [comment]
Ok, deleted. I'm just a user of that chart. 🤗

**Comment by tegioz** [comment]
Awesome. I've just updated it 👍 Thanks!
