### ISSUE TITLE
Stars field doesn't populate from the API for a helm chart

### ISSUE THREAD

**Issue by lucasreed** [artifacthub/hub#1691]
**Describe the bug**
When using the API and querying a specific helm package, the stars field is not populated despite the package having stars in the artifacthub UI.

**To Reproduce**
1. Have `jq` installed before running the next command
2. `curl --silent https://artifacthub.io/api/v1/packages/helm/fairwinds-stable/goldilocks |jq .stars`
returns:
```
null
```
3. Navigate to https://artifacthub.io/packages/helm/fairwinds-stable/goldilocks which shows stars > 0

I also verified I was getting data back by simply running:
`curl --silent https://artifacthub.io/api/v1/packages/helm/fairwinds-stable/goldilocks |jq .` which shows the returned data, but no `stars`

**Expected behavior**
I would expect the stars API field to be populated with the number shown in the UI

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Monterey 12.0.1

**Additional context**
N/A

**Comment by tegioz** [comment]
Hi @lucasreed 👋 

This seems to be a problem with the documentation, as it shows the `stars` field in the example when this endpoint is not really supposed to return it (it's working as expected). We'll that care of it, thanks 👍 

Please note that there is a separate point to get the package's stars:

https://artifacthub.io/docs/api/#/Packages/getPackageStars

One of the reasons they are separate endpoints is that they follow different caching rules. The endpoint to get the stars also returns if the user (when logged in) has starred the package.

Hope this helps.

**Comment by lucasreed** [comment]
It does, thanks @tegioz !

**Comment by tegioz** [comment]
Awesome, no worries. We'll update the doc, thanks!
