### ISSUE TITLE
 No private IPv4 address found

### ISSUE THREAD

**Issue by wdhanhuan** [artifacthub/hub#1717]
**Describe the problem**
 No private IPv4 address found

**Additional context**
06:45:26.98 
 06:45:26.99 Welcome to the Bitnami consul container
 06:45:26.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-consul
 06:45:26.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-consul/issues
 06:45:27.00 
 06:45:27.00 INFO  ==> ** Starting Consul setup **
 06:45:27.04 INFO  ==> Validating settings in CONSUL_* env vars..
 06:45:27.08 INFO  ==> Initializing Consul...
 06:45:27.09 INFO  ==> Deploying consul from scratch...
 06:45:27.09 INFO  ==> No injected configuration files found. Creating default config files...
 06:45:27.11 INFO  ==> ** Consul setup finished! **

 06:45:27.15 INFO  ==> ** Starting Consul **
==> No private IPv4 address found

myconsul-0                   0/1     CrashLoopBackOff   3          97s
myconsul-1                   0/1     CrashLoopBackOff   3          97s
myconsul-2                   0/1     CrashLoopBackOff   3          97s

**Comment by tegioz** [comment]
Hi @wdhanhuan 👋 

For issues with the content listed on artifacthub.io it's best to contact the particular project directly. 

This link may help if you are using the Consul chart provided by Bitnami:

https://github.com/bitnami/charts/issues
