### ISSUE TITLE
CRDS view doesn't respect lowercase and capital characters in the fields of the examples

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [artifacthub/hub#1722]
**Describe the bug**
CRDS view doesn't respect letter register for CRDS examples.

**To Reproduce**
1. Go to released Eclipse Che operator page 'https://artifacthub.io/packages/helm/eclipse-che/eclipse-che?modal=crds&file=checlusters.org.eclipse.che'

2. Select CheCluster item
3. Scrop to the field k8S.

![screenshot-artifacthub io-2021 12 03-14_04_40](https://user-images.githubusercontent.com/6873095/144600817-2aea154d-66c0-473f-ae64-6af78ad77fed.png)

Actual result: CRDS view should display ***k8s***, but you can see ***k8S*** - with capital letter at the end. Server side returns valid data, in the Chrome dev console, I got request : https://artifacthub.io/api/v1/packages/helm/eclipse-che/eclipse-che

![screenshot-nimbus-capture-2021 12 03-13_44_10](https://user-images.githubusercontent.com/6873095/144599829-2b644eb6-e01b-43d5-af13-37997267ec5b.png)

<img width="1786" alt="Screenshot 2021-12-03 at 13 50 16" src="https://user-images.githubusercontent.com/6873095/144599986-38f36bd1-f0ad-4f5e-b00c-4a11fe79f7d4.png">

I'm not sure, but looks like CRDS widget has enabled some camel-case mode...

> Notice: this bug breaks installation flow for our helm package....

**Expected behavior**
CRDS view shouldn't change letter register for CRDS examples.

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Mac OS 12.0.1
 - Browser [e.g. Google Chrome]
 - Version 96.0.4664.55 (Official Build) (x86_64)

**Additional context**

**Comment by tegioz** [comment]
Thanks for reporting this @AndrienkoAleksandr, we'll take care of it soon 👍

**Comment by tegioz** [comment]
The fix has just been deployed to production @AndrienkoAleksandr.
