### ISSUE TITLE
Dispatch Event to GitHub repository / Add additional headers to a webhook configuration

### ISSUE THREAD

**Issue by 300481** [artifacthub/hub#1775]
**Is your feature request related to a problem? Please describe.**
I want to be able to implement GitOps as automated as possible.
F.e. I am using ArgoCD for my application deployments. This is using the Helm Chart configuration stored in a GitHub code repo.
Currently I get notification emails or can configure webhooks to a defined endpoint when there is a new chart version available.
But to automate the update of chart definitions in my code repo I need additional compute resources/servers,
which receive the webhooks and do their things.
My current idea is to use a serverless function like [this one](https://github.com/300481/artifacthub2github/tree/main/gcp-cloud-function), which receives the webhook and forward it as a dispatch event to my GitHub repo. In the GitHub repo the dispatch workflow will do all the needed things.

**Describe the solution you'd like**
The ideal solution would be, when I could configure ArtifactHUB to send this dispatch event directly to GitHub.
Just a webhook is not working, because it needs authentication and a special request body.
The request body could be adjusted by the body template, but for the autentication I see no settings.
Adding custom headers to the webhook would be the best and most flexible solution.

**Describe alternatives you've considered**
Have no idea for an alternative.

**Additional context**
No additional context.

**Comment by tegioz** [comment]
Hi @300481 👋 

The ability to add custom headers to the webhook configuration sounds like a nice addition 👍

However, I'm a bit concerned about it being used for credentials, like in this particular use case. We'd need to store those credentials in clear text in the database, which is not a good idea. Should there be a security issue in Artifact Hub, this could potentially be a risk for multiple projects depending on the scope of those credentials.

**Comment by 300481** [comment]
Hi @tegioz 

you are so right! That's an issue nobody wants.
Maybe this could be achieved with the GitHub App integration of ArtifactHub?
Sorry, I don't have insides in the code of ArtifactHub. Maybe someone else has an idea? 
In my imagination it is just a checkbox "GitHub Repository Dispatch" and a string field for the repositories name
and optionally the owner of the repo (user/organization).

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed.
