### ISSUE TITLE
Readme files not displaying images

### ISSUE THREAD

**Issue by Johannestegner** [artifacthub/hub#1798]
Hi!

I just published my first container image to Artifact hub and noticed that images in the referenced README file are not displayed.  

**To Reproduce**

Easiest would be for me to refer to the public readme on artifact hub https://artifacthub.io/packages/container/alpine/alpine

_minor note: I noticed that I accidentally "stole" the alpine namespace, and I will happily remove the image if requested from either anyone of you or from the alpine maintainers._

The actual readme can be found at gitlab: https://gitlab.com/jitesoft/dockerfiles/alpine/-/raw/master/README.md

**Expected behavior**
Images showing up in the readme on artifact hub.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Tested in Firefox, Chrome, Edge
 - Version: All

**Additional context**

The images that are not displayed uses HTML type link/image tags in the README, which might be the issue:

```
<a href="https://fosshost.org/">
  <img src="https://raw.githubusercontent.com/jitesoft/misc/master/sponsors/fosshost.png" height="128" alt="Fosshost logo" />
</a>
<a href="https://www.aarch64.com/">
  <img src="https://raw.githubusercontent.com/jitesoft/misc/master/sponsors/aarch64.png" height="128" alt="Aarch64 logo" />
</a>
```

Viewing the HTML on the artifact hub page, it seems like the whole block is just stripped away.

**Comment by tegioz** [comment]
Hi @Johannestegner 👋 

Thanks for adding your first container image to Artifact Hub 🎉 

HTML is not supported in the README content, but you can add images using markdown syntax and they should be displayed fine 🙂 

Regarding the namespace, thanks for the heads up 👍

**Comment by Johannestegner** [comment]
Thank you for the swift response @tegioz !

I was guessing that the HTML was the issue, and I'll see if I can fix that in my repositories! :)

I will close this issue while still ask a quick question about the namespace, what is the proffered way to name container images in artifact hub? In most registries, the `org/name` standard is used, which does not seem to work on artifact hub. I have a lot of images that I would love to publish, but I really don't want to take all the names of actual official images! :)

Should I go with `jitesoft-alpine` or is there some other better way to do this? :)

**Comment by tegioz** [comment]
No worries!

That's a great question. We still need to discuss this a bit, but naming your repository `jitesoft-alpine` sounds great 👍

**Comment by Johannestegner** [comment]
Deleted it and created jitesoft-alpine, the display name is still alpine (from the labels I would expect), which is perfect, and it doesn't reserve the name that I would prefer to see the official image to take, so jitesoft-alpine works perfect for me!

Discussing it would probably be a good idea, maybe even oversee the submission process a bit to make sure that "official" images either are reserved or takes over namespaces, but I leave that to you guys! :D 

Also, great job/idea to allow container images on there, I have been looking for somewhere to have my images published with all alternative locations and such, and artifact hub is a perfect place <3

**Comment by tegioz** [comment]
Awesome, thanks! 😊
