### ISSUE TITLE
API: support search by repo URL

### ISSUE THREAD

**Issue by brsolomon-deloitte** [artifacthub/hub#1813]
I see that `/repositories/search` takes a `name` but not a `url`. Is it possible to search by URL to locate a repository and its metadata?

For example:

- I have `https://charts.bitnami.com/bitnami` as URL
- I want to be able to `/repositories/search` with `url=https://charts.bitnami.com/bitnami` and see in result that the repo is `bitnami`
- and then execute `/packages/helm/bitnami/keycloak`

**Comment by tegioz** [comment]
Maybe the endpoint below can be of help 🙂 

https://artifacthub.io/docs/api/#/Integrations/getHelmExporterDump

It was created for a tool with a similar purpose actually. It'll give you a short summary of all repositories, that includes the url for a fast local lookup.

Hope it helps.

**Comment by brsolomon-deloitte** [comment]
Nice, here's what I put together (could also just pipe curl to jq):

```bash
$ curl -fsSL \
  -o helm-export.json \
  'https://artifacthub.io/api/v1/helm-exporter' \
  -H 'accept: application/json'
$ jq -M '.[] | select(.repository.url == "https://charts.bitnami.com/bitnami" and .name == "keycloak")' helm-export.json 
{
  "name": "keycloak",
  "version": "6.1.4",
  "repository": {
    "name": "bitnami",
    "url": "https://charts.bitnami.com/bitnami"
  }
}
```
