### ISSUE TITLE
Display Signature badges

### ISSUE THREAD

**Issue by cpanato** [artifacthub/hub#1832]
**Is your feature request related to a problem? Please describe.**
Similar to the security scanning will be good to add a badge that shows if the image/package is signed

we can use cosign to check if the images were signed with this tool and maybe we can add other tools as well as fallback 

**Describe the solution you'd like**
Display a badge to indicate if the image/package is signed

**Describe alternatives you've considered**
n/a

**Additional context**
I can help on that :)

/cc @mattfarina

**Comment by tegioz** [comment]
Hi @cpanato 👋 

We are already displaying a badge when a package is signed, but at the moment we are only reading the signature information for Helm charts (supporting both provenance files and cosign -the later when the charts repo is OCI based-). It'd be nice to start reading the signatures for the container image kind as well 🙂 

<img width="839" alt="cosign" src="https://user-images.githubusercontent.com/1213902/155108819-96854fee-63b9-4521-8563-28c62ce8bcda.png">

<img width="1295" alt="provisioning-file" src="https://user-images.githubusercontent.com/1213902/155108842-3d5e889c-2ae9-4112-be92-986910393ed8.png">

**Comment by cpanato** [comment]
that is great news, i did not know that, thanks so much! @tegioz

**Comment by tegioz** [comment]
This is ready @cpanato, we'll deploy it a bit later today. Thanks! 🙂

**Comment by tegioz** [comment]
<img width="695" alt="container-image-cosign" src="https://user-images.githubusercontent.com/1213902/157226188-7585d0a8-5483-49a3-887b-d24e75f0aaa9.png">

**Comment by cpanato** [comment]
cool, thanks @tegioz
