### ISSUE TITLE
Improved pop-up window for reading helm chart values/templates

### ISSUE THREAD

**Issue by FotiadisM** [artifacthub/hub#1870]
**Is your feature request related to a problem? Please describe.**
Being able to comfortably read the default values and the templates of a helm chart is very crucial. In my opinion, the current pop-up window could be improved to maximize vertical space for displaying bigger chunks of code.

![image](https://user-images.githubusercontent.com/47476275/160119840-fff4139a-3398-499d-a946-60070124508c.png)

**Describe the solution you'd like**

To improve the user experience, the bottom row (underneath the code) could be deleted since it only contains a redundant close button,
reduce the font size of the top row (containing the header 'Default Values'), reduce vertical padding/margin, and maybe even move the search bar in the top row.

Example: 

![image](https://user-images.githubusercontent.com/47476275/160590918-3e45260c-5ed4-4e72-9c04-fd45cb472a68.png)

**Comment by tegioz** [comment]
Hi @FotiadisM 👋 

Maybe we could apply some of these improvements when the height of the browser window goes below some point.

We'll look into it and get back to you 🙂
