### ISSUE TITLE
no security scanning for deactivated and/or removed packages

### ISSUE THREAD

**Issue by hairmare** [artifacthub/hub#1882]
**Is your feature request related to a problem? Please describe.**
We used to maintain a Helm chart that is failing security scanning due to it being based on outdated images:

> error scanning image [quay.io/k8scsi/csi-attacher:v1.2.1](http://quay.io/k8scsi/csi-attacher:v1.2.1): schema v1 manifest not supported by trivy (package huawei-csi-plugin:0.3.0)

We have deprecated and removed the chart from our repo, but the security scanner still send mails complaining multiple times per day. We don't plan on updating the chart, hence it being deprecated and removed.

**Describe the solution you'd like**
Deprecated and/or removed packages should not get security scanned, or they should not send mails.

**Describe alternatives you've considered**
An alternative solution would be to allow ignoring individual charts rather than just being able to deactivate security scanning on full repositories.

**Additional context**
The affected Helm chart is [here on artifacthub](https://artifacthub.io/packages/helm/adfinis/huawei-csi-plugin). The affected `huawei-csi-plugin ` chart was deprecated in https://github.com/adfinis-sygroup/helm-charts/pull/516 and removed in https://github.com/adfinis-sygroup/helm-charts/pull/616.

**Comment by tegioz** [comment]
Hi @hairmare 👋 

Helm charts are automatically removed from Artifact Hub when they are removed from the repository's `index.yaml` file. In the case of the chart you linked, it's still present on the [index file](https://charts.adfinis.com/index.yaml). Once it's removed, it won't be visible on Artifact Hub and it won't be scanned again (we'll delete it actually).

**Comment by tegioz** [comment]
Regarding not scanning deprecated packages, I'm not sure if that would be the right thing to do by default. Many users may still rely on a deprecated package, and having some extra information about security issues may be of help for them.

Please note that you can disable security scanning for some or all of the package's images by whitelisting them using the `artifacthub.io/images` [annotation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations).

Hope this helps 🙂

**Comment by hairmare** [comment]
Hi @tegioz 

Thanks for the feedback.

I'm a bit wary of removing it from the index right now since that would lead to users that haven't updated the chart in a long time potentially not getting the deprecation message.

Adding the annotation seems like a workable alternative although i would have to reinstate the deprecated chart in our repo to add the annotation via CI.

Maybe i can just add the annotation to index.yaml directly. I'm not sure if changing metadata for an already released Chart via index would work though. This depends on Artifact Hub reading from index.yaml and not from the charts `Chart.yaml`.

**Comment by hairmare** [comment]
> Updating it only in the index won't be enough, you'd need to update both the chart's tgz package and the index. We process the index to get a view of what's available in the repo and, when we detect a chart that needs to be processed (new, updated, etc), we download the full package as there is some information on it that we need not available in the index.

Ah, thanks for the info, i'll reinstate the chart so i can add the annotation and then remove it again as that seems like the most straigth forward way to get rid of the trivy mails for now.

An option to deactivate security scanning on individual charts might still be of value though, reviving a chart to add an annotation just to delete it again seems a bit overkill.

**Comment by tegioz** [comment]
No worries! You can also opt-out of the scanner notifications from the control panel, but it works at the repository level, not per package. We'll think a bit about adding an additional way to disable security scanning for a given package, thanks.

Will close this issue for now, please feel free to reopen it if needed.
