### ISSUE TITLE
Add `_helpers.tpl` to the UI, so that they are discoverable, explorable, and searchable

### ISSUE THREAD

**Issue by spkane** [artifacthub/hub#1945]
**Is your feature request related to a problem? Please describe.**
Sometimes Helm charts make extensive use of `_helpers.tpl` and without access to these, it can be very difficult to follow the logic of a Helm chart's templating.

As an example, if you are looking at this:

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-configs/argocd-cm.yaml#L14-L15

It can be hard to determine that this actually comes from here:

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/_helpers.tpl#L236-L243

It would be great if ArtifactHub could be used to make these more visible.

**Describe the solution you'd like**
Add the helper templates to the UI, like the rest of the templates, and values, so that they can be searched and used to piece together the flow of data through the templating process.

**Comment by tegioz** [comment]
Hi @spkane 👋 

The UI should be already displaying `_helpers.tpl` files (please see the screenshot below from the [argo-cd Helm chart](https://artifacthub.io/packages/helm/argo/argo-cd?modal=template&template=_helpers.tpl)). Is it possible that you've found a particular chart for which this is not working as expected?

<img width="1618" alt="templates" src="https://user-images.githubusercontent.com/1213902/167363238-dedfba0c-103a-4f74-8376-328e2e64744e.png">

We were thinking that maybe we could try to link *include calls* in templates to the helper template definition whenever possible. We could display some sort of popover detailing the file and line the template is defined in and a link to it, to make it easier jumping to it. What do you think?

<img width="1618" alt="templates2" src="https://user-images.githubusercontent.com/1213902/167364825-b0343ac3-3788-4fc7-8eb2-ed84189901c7.png">

**Comment by spkane** [comment]
@tegioz Oh. That makes sense. I must have just missed it in the list.

The lack of connectivity (discoverability) was really the issue, in this case, so the idea of linking the include calls is very appealing. Something that makes it easier to follow the login and figure out where various values come from.

**Comment by tegioz** [comment]
This is ready, we'll deploy it shortly 🙂 

<img width="698" alt="named_templates_definition" src="https://user-images.githubusercontent.com/1213902/172363701-122a40ae-1adc-4b57-b383-0583f6917012.png">

**Comment by spkane** [comment]
Thanks! That is great!!
