### ISSUE TITLE
automatically recognize pre-release semver versions.

### ISSUE THREAD

**Issue by STRRL** [artifacthub/hub#2050]
**Is your feature request related to a problem? Please describe.**

Artifact Hub would recognize a version as a pre-release if it contains an annotation `artifacthub.io/prerelease: "true"`.

A prerelease version would appear as the default on Artifact Hub, but would not appear on helm cli unless use `--devel`

**Describe the solution you'd like**

It's would be much better to automatically treat it as a prerelease like what `helm search repo -l --devel` does.

We could follow this spec: https://semver.org/#spec-item-9

**Describe alternatives you've considered**

No other alternatives.

**Comment by tegioz** [comment]
Hi @STRRL 👋 

Please see this related discussion: https://github.com/artifacthub/hub/issues/973#issuecomment-745220868

**Comment by STRRL** [comment]
I totally agree with not breaking existing things. :)

Thanks for your explanation.
