### ISSUE TITLE
Add Kubewarden Policy tracker

### ISSUE THREAD

**Issue by flavio** [artifacthub/hub#2065]
**Is your feature request related to a problem? Please describe.**

Kubewarden is a policy engine for Kubernetes.  Kubewarden policies are WebAssembly modules that are distributed using regular container registries.

Kubewarden has just been accepted inside of CNCF Sandbox :partying_face: 

Currently Kubewarden policies can be found via Kubewarden's [Policy Hub](https://hub.kubewarden.io). We would like to use Artifact Hub instead.

**Describe the solution you'd like**

We would like Policy Authors to list their Kubewarden policies via Artifact Hub. Policies would still be hosted by 3rd party container registries owned by the Policy Authors.

**Describe alternatives you've considered**

Since we were not yet a CNCF Sandbox project, we couldn't use Artifact Hub. Instead we built [Policy Hub](https://hub.kubewarden.io) to allow the community to find and share their policies.
Artifact Hub however is a better place for doing that. This was also raised by the CNCF TOC during the CNCF Sandbox review process.

**Additional context**

Nothing special to be added.

**Comment by flavio** [comment]
@tegioz : thanks for the detailed explanation. I'll think more about how to proceed and get back to you!

**Comment by flavio** [comment]
Sorry for the late response, it has been a busy time... :sweat: 

I like the idea of reusing the [Artifact hub metadata file](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml). I also think the custom annotations mechanism is perfect for storing some kubewarden-specific data that currently lives inside of the `hub.yml` file. The goal would be to completely get rid of the `hub.yml` files.

It's good to know we could have multiple policies defined inside of the same Git repository, however this is not something common.
I would focus on the current scenario: 
   * A policy source code is stored inside of a dedicated Git repository
   * The compiled policy is stored inside of an OCI registry as an OCI artifact

Looking at the Git repository:
   * The source code of the policy lives in there
   * The Git repository contains just one policy
   * There's a `main` branch that keeps the development code
   * Each release of the policy has its own dedicated Git tag

Looking at the OCI registry:
   * Each policy release has an OCI artifacts
   * OCI artifacts are tagged using the same tags specified inside of Git
   * There's a `latest` tag pointing to the most recent version of the policy

How are we going to handle the `artifacthub-pkg.yml` file?
  * Are we going to commit that to the Git repository?
  * Are we going to keep just one file inside of the root of the Git repository and then make it evolve together with the policy (Git `v0.1.0` tag would have the `artifacthub-pkg.yml` referencing the `v0.1.0` policy)?

If we are going to handle the `artifacthub-pkg.yml` in this way, changes to the file will necessarily lead to the creation of the new Git tag -> a new OCI artifact. This is not optimal, but we would live with that.

**Comment by tegioz** [comment]
Hi @flavio

Yes, the Artifact Hub metadata file should be committed to the git repository. 

One option would be to keep just one and make it evolve like you described. In that case it's important to keep in mind how Artifact Hub will behave. If you keep a single metadata file, AH will process it every time the *version* defined in the metadata file changes or the *digest* changes. You could use the latter to have an existing version reindexed, for example. That way you wouldn't need to push a new version when the metadata file gets updated. However, when you update the version from let's say 0.1.0 to 0.2.0, AH will detect that there is a new version in the repository, 0.2.0, but that 0.1.0 does no longer exist, so it'll be *removed* and won't be listed on AH anymore.

The other option would be to have multiple metadata files, [one per version on a different directory](https://artifacthub.io/docs/topics/repositories/#keda-scalers-repositories). Please note that the generic tracker doesn't support git tags and it expects all versions to be available in the head of the branch defined in AH following the structure linked above.

Users listing Kubewarden policies will have both options available, so they can pick the one that fits their needs best.

Regarding the OCI artifacts, they could be referenced in the metadata file by using the [containersImages](https://github.com/artifacthub/hub/blob/7eeb7076164799b1f81e7b1bdf9215779a95e16e/docs/metadata/artifacthub-pkg.yml#L13-L16) field to have them scanned for security vulnerabilities by Trivy (not sure how relevant may this be at the moment for this particular case, but new features are added often so it could be helpful eventually).

We'll start working on this and prepare a basic integration for you. Then we can discuss what Kubewarden specific pieces of data could be also interesting to display 🙂

**Comment by tegioz** [comment]
We've just added support for Kubewarden policies! 🚀

You can see it in action in staging (please see link below), we'll deploy it to production early next week.

- Kubewarden policy package*: <https://staging.artifacthub.io/packages/kubewarden/kubewarden-test/capabilities-psp>
- Source (policy repo fork): <https://github.com/tegioz/capabilities-psp-policy>
- Metadata file: <https://github.com/tegioz/capabilities-psp-policy/blob/main/artifacthub-pkg.yml>

*(\*) There is a small issue in the url we've just noticed -it shows `null` instead of `kubewarden` when opening the package details from the search results-, we'll fix it shortly.*

Please feel free to add some repos and experiment a bit with them 🙂

We've added a couple of sample [Kubewarden specific annotations](https://github.com/tegioz/capabilities-psp-policy/blob/0c40c1c059489427315e45214ce2840fafde8b19/artifacthub-pkg.yml#L29-L31) that the UI knows how to render nicely. We can add some more or update them as needed. Once they are properly defined we'll [add them to the docs](https://artifacthub.io/docs/topics/annotations/keptn/).

![kubewarden](https://user-images.githubusercontent.com/1213902/178096740-cb833542-6295-46bc-a959-fe4d7f0723b7.png)

**Comment by flavio** [comment]
I've played a bit with it by creating a this forked repository: https://github.com/flavio/allowed-fsgroups-psp-policy
The policy is then visible on Artifact Hub [here](https://staging.artifacthub.io/packages/kubewarden/allowed-fsgroups-psp-policy/allowed-fsgroups-psp).

Overall, everything has been extremely simple. I wanted to have multiple versions of the same policy inside of the same repository, you can see I've put all the Artifact Metadata under the [`artifact-hub`](https://github.com/flavio/allowed-fsgroups-psp-policy/tree/main/artifact-hub) directory. That worked pretty smoothly.

I've just one note... Kubewarden policies are pulled from container registries. If you look at the Kubewarden [Policy Hub](https://hub.kubewarden.io), the pull link (like `ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11`) is prominent.
On Artifact Hub this is is not visible. There's a link that points to the https location of a policy, which is nice, but this isn't how 99% of the users are going to reference a policy.

The information is available inside of the Artifact Hub metadata via the:

```yaml
containersImages:
  - name: policy
    image: ghcr.io/kubewarden/policies/allowed-fsgroups-psp:v0.1.3
```

Is there some way to make it more prominent?

Otherwise I was thinking about using the `install` section of the yaml file :thinking:

**Comment by tegioz** [comment]
Awesome, that's great!

We could add something Kubewarden specific to the UI, but I think the best approach would be to use the `install` section as you mentioned. Artifact Hub users are used to it, as it's used by the rest of the artifacts kinds, so it should be intuitive even for new Kubewarden users. You can use markdown on it to format it nicely ([Keptn example](https://artifacthub.io/packages/keptn/keptn-integrations/dynatrace-service?modal=install)).

We'll probably deploy it to production later on today, I'll let you know when it's done 🙂

**Comment by tegioz** [comment]
Deployed to artifacthub.io! 🥳

(The sample repo I added to staging hasn't been added this time, so there aren't any Kubewarden policies repos listed yet)

**Comment by flavio** [comment]
One last question, I've noticed the UI shows `version` instead of `appVersion`. For example [here](https://github.com/flavio/allowed-fsgroups-psp-policy/blob/main/artifact-hub/allowed-fsgroups-psp-policy/0.1.3/artifacthub-pkg.yml) the policy version is `0.1.3` (tracked via `appVersion`), but the [UI](https://staging.artifacthub.io/packages/kubewarden/allowed-fsgroups-psp-policy/allowed-fsgroups-psp/0.1.0) shows only the `0.1.0` version.

I'm fine using just `version`, but I wonder how we should handle the case when the `artifacthub-pkg.yml` file has to be updated (let's say there's a typo) but we don't want to update the version of the actual policy.

**Comment by flavio** [comment]
> Deployed to artifacthub.io! partying_face
> 
> (The sample repo I added to staging hasn't been added this time, so there aren't any Kubewarden policies repos listed yet)

Awesome! We will start porting all our policies from Kubewarden's policy hub over there :partying_face: :heart:

**Comment by tegioz** [comment]
> One last question, I've noticed the UI shows `version` instead of `appVersion`

At the moment that field is only displayed in the UI for packages of kind Helm (where both versions are displayed), but we should probably do it for some more kinds, including Kubewarden policies.

We'll take care of it so that both are displayed. That way you should be able to use appVersion for the policy version and version for the package in Artifact Hub 🙂
