### ISSUE TITLE
Helm OCI Error Getting Repository Remote Digest

### ISSUE THREAD

**Issue by bman46** [artifacthub/hub#2165]
**Describe the bug**
When processing an OCI Helm repo from GHCR, the following error is returned:
```
error getting repository remote digest: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: bman46/ctfd/ctfd 
```

**To Reproduce**
1. Create a GitHub repo
2. Use the following GitHub Action to upload the chart to GHCR. [Action file.](https://github.com/bman46/CTFd-Helm/blob/main/.github/workflows/helm.yml)
3. Add the chart to Artifacthub using the following format:
  a. `oci://ghcr.io/user/repo/chart`
  b.  Ex: `oci://ghcr.io/bman46/ctfd/ctfd`
4. Wait for Artifacthub to process the repo and an error will display

**Expected behavior**
The repo is successfully parsed.

**Additional Notes:**
The following command working with helm
```bash
$ helm show chart oci://ghcr.io/bman46/ctfd/ctfd
apiVersion: v2
appVersion: 3.5.0
dependencies:
...
```

**Comment by tegioz** [comment]
Hi @bman46 👋 

It looks like you added the url to Artifact Hub with a space in the end. If you remove it the repository should be processed fine 🙂

<img width="1500" alt="ctfd" src="https://user-images.githubusercontent.com/1213902/181181113-0838b62e-b8ae-4887-ad5b-2eceb3b8c9ce.png">
