### ISSUE TITLE
[OFFICIAL] Camunda

### ISSUE THREAD

**Issue by aabouzaid** [artifacthub/hub#2182]
- **Repository name** *(in `artifacthub.io`)*: [Camunda](https://artifacthub.io/packages/search?repo=camunda)
- **Official packages**: All packages are official
- **Project URL:** [Camunda Platform](https://github.com/camunda/camunda-platform-helm)
- **Source code URL**: [Camunda Platform](https://github.com/camunda/camunda-platform-helm)
- **Other relevant URLs:**: [My account in Camunda Github org](https://github.com/orgs/camunda/people?query=aabouzaid)

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!
