### ISSUE TITLE
Google Analytics loaded without user consent

### ISSUE THREAD

**Issue by lukma99** [artifacthub/hub#2184]
**Is your feature request related to a problem? Please describe.**
When visiting https://artifacthub.io/ I noticed, that the website loads Google Analytics without asking the user if he agrees to this (lack of cookie banner or something similar). According to GDPR this is a heavy violation, as personal data is being transferred to a third party (Google). Non essential things like this must be __opt-in__. 

**Describe the solution you'd like**
As long as there are no measures taken, I would like to ask you to disable Google Analytics completely from the website.

If you want to use Google Analytics in the future, you have to ask the user if he agrees when visiting the website for the first time. Furthermore a notice in a privacy policy is mandatory.

Speaking of this, I am not able to find a privacy policy from artifacthub in the footer. Don't you have any?

**Describe alternatives you've considered**
See above. Regarding the need to inform and ask the users about data-collecting, there is no alternative except removing Google Analytics from the code or keeping it and correctly ask the user for consent .

If you care about privacy and want to help reducing surveillance by Google, but still need data about usage of the website, an even better alternative to Google Analytics would be [Matomo](https://github.com/matomo-org/matomo). It is open source, and you even can self-host it if you want, so no data gets transferred to third party companies. An alternative would be the fairly cheap cloud solution by them.

**Additional context**
![Screenshot of dev console](https://user-images.githubusercontent.com/47565816/183490825-1592acdd-6e44-480f-a320-04a33c268534.png)

Regardless of the issue: Thank you for your work regarding artifacthub. It is a great platform and I hope this issue leads to improvement for all your users privacy :)

**Comment by tegioz** [comment]
Hi @lukma99 👋 

Thanks for raising this issue. We'll disable GA temporarily until we decide how we'd like to move forward with this 👍

Regarding the privacy policy, we don't have one yet but we'll take care of it.

Thanks!

/cc @caniszczyk @mattfarina

**Comment by tegioz** [comment]
Google Analytics is now disabled on `artifacthub.io`. Will close this one for now, feel free to reopen if needed.
