### ISSUE TITLE
[OFFICIAL] k8tz

### ISSUE THREAD

**Issue by yonatankahana** [artifacthub/hub#2202]
- **Repository name**: [k8tz](https://artifacthub.io/packages/helm/k8tz/k8tz)
- **Official packages**: k8tz
- **Project URL:** http://k8tz.io
- **Source code URL**:  https://github.com/k8tz/k8tz
- **Other relevant URLs**: [org membership](https://github.com/orgs/k8tz/people?query=yonatankahana)

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!
