### ISSUE TITLE
Ability to filter on fixable vulnerabilities

### ISSUE THREAD

**Issue by sozercan** [artifacthub/hub#2221]
**Is your feature request related to a problem? Please describe.**
Artifact Hub reports vulnerabilities for artifacts such as images or binaries. 

However, in some cases, these vulnerabilities are not fixable/actionable as there are no upstream patches available. 
Example: 
```
mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.2.3
TARGET:debian 11.4
```
https://artifacthub.io/packages/helm/csi-secrets-store-provider-azure/csi-secrets-store-provider-azure?modal=security-report&image=mcr.microsoft.com%2Foss%2Fkubernetes-csi%2Fsecrets-store%2Fdriver%3Av1.2.3&target=secrets-store-csi
At the time of this writing, this image has no fixable vulnerabilities.

**Describe the solution you'd like**
It would be nice to have a checkbox to filter only fixable vulnerabilities to see if it's actionable as project maintainers may not be able to fix these vulnerabilities.
Example: https://quay.io/repository/argoproj/argocd/manifest/sha256:1dbd9c885d3036f84bb4ddae0a5027b86a43801ef9af7c68092c2192451bc65c?tab=vulnerabilities

**Comment by tegioz** [comment]
Hi @sozercan 👋 

This sounds like a nice addition, we'll look into it 🙂 

Thanks!

**Comment by tegioz** [comment]
This is ready @sozercan, we'll deploy it to production a bit later today. We've applied some more related improvements in addition to the switch to filter out vulnerabilities that are not fixable 🙂

<img width="1490" alt="Screen Shot 2022-09-30 at 13 44 48" src="https://user-images.githubusercontent.com/1213902/193263541-3b58b001-98bb-4d4f-afd1-adc1b3c22740.png">
