### ISSUE TITLE
Add Git-Based Versioning for Tekton Packages

### ISSUE THREAD

**Issue by QuanZhang-William** [artifacthub/hub#2326]
**Is your feature request related to a problem? Please describe.**
Today Tekton catalog follows [directory-based versioning structure](https://github.com/tektoncd/catalog#catalog-structure), where each version of the resource is located in a dedicated folder like ```/task/argocd/0.1/argocd.yaml```.

The Tekton community is working on add [git-based versioning](https://github.com/tektoncd/community/blob/main/teps/0115-tekton-catalog-git-based-versioning.md#git-based-versioning) to Tekton catalog, where directories - ```0.1...0.n``` will be removed, and versioning will be supported via git tags (i.e. the tags in the catalog repo will map to versions in the Hub e.g. tag "v0.7" in a Catalog maps to version "0.7" in the Hub).

Currently, Artifact Hub fetches Tekton Task and Pipelines based on the directory-based versioning, we would like to have Artifact Hub to support git-based versioning for Tekton Tasks and Pipelines.

**Describe the solution you'd like**
We would like Artifact Hub to surface all Tekton package versions that follows the git-based versioning as it is in the directory-based versioning today.

As an example, I registered a [Tekton package](https://artifacthub.io/packages/tekton-task/quan-demo-git-versioning/git-simple-1) from this [repo](https://github.com/QuanZhang-William/ah-test-catalog-git-versioning) that follows git-based versioning (with 2 tags: ```v0.1``` and ```v0.2```) . However, only the latest version is detected:
![image](https://user-images.githubusercontent.com/26396370/190185334-8c0f3165-54bb-40ee-9e27-e881f21e2e7c.png)

**Describe alternatives you've considered**

**Additional context**
The Tekton community now encourage users to create Catalogs in their own repos and share them through the Hub instead of using a [centralized catalog](https://github.com/tektoncd/catalog). This is naturally supported in Artifact Hub.

The existing [centralized catalog](https://github.com/tektoncd/catalog) will remain as it is using the directory-based contract. It will be read-only and will encourage owners of the resources to move them to their own repositories in their own GitHub organizations. After 9 months, we will archive the tektoncd/catalog repository. ~~At the same time, we will remove support for the directory-based versioning in the Tekton Hub.~~

**Comment by tegioz** [comment]
Hi @QuanZhang-William 👋 

Thanks for the heads up, we'll look into it 👍

**Comment by vdemeester** [comment]
@tegioz note that we are also looking to help the artifact hub community to maintain the tekton provider part if need be or if we can 👼🏼 😉

**Comment by tegioz** [comment]
Thanks @vdemeester! 👍

**Comment by QuanZhang-William** [comment]
cc @jerop, @bendory

**Comment by tegioz** [comment]
Hi 👋 

We've just added experimental support for git based versioning for Tekton packages (#2337). You can see it in action in the [staging environment](https://staging.artifacthub.io/packages/search?repo=test-git&sort=relevance&page=1) (we added the [repo](https://github.com/QuanZhang-William/ah-test-catalog-git-versioning) you shared above @QuanZhang-William). We can now continue iterating over this first implementation 🙂

When adding a Tekton tasks or pipelines repository, you can now select what versioning model applies to it (to keep backwards compatibility with existing repos):

<img width="602" alt="Screen Shot 2022-09-20 at 17 28 22" src="https://user-images.githubusercontent.com/1213902/191301902-d089d32d-fa7d-49d4-a5c2-eca90490e804.png">

There are a couple of points I'd like to mention:

- Versions: at the moment the version in the tag file **must** match the one in the manifest file. If you'd like a different behavior please let us know. In catalogs with a lot of packages, this may require a bit of work I guess, touching quite a few manifest files every time a bump is needed. Maybe you plan to eventually remove the version in the manifest, not sure (from: [Versioning will move from the resources themselves to the Catalog as a whole](https://github.com/tektoncd/community/blob/main/teps/0115-tekton-catalog-git-based-versioning.md#versioning-in-a-catalog)).

- This one is also related to versions. In Artifact Hub, every package (a task or pipeline in this case) must have a version. Given that all tasks in a catalog will share the same version, I understand that sometimes the version for a task will be bumped even though that particular task may not have changed at all. Users in Artifact Hub can subscribe to new releases notifications and, in cases like the one just mentioned, they may be notified about a new package release when nothing actually changed, which could be a bit annoying for users. I've already discussed this concern with @QuanZhang-William in Slack, and he mentioned that you were moving to smaller repos with fewer (or even one) packages per repo, which would definitely help.

When you have a chance please give it a try on staging and let us know your thoughts 🙂

**Comment by vdemeester** [comment]
Waw nice and quick 😻 

> * This one is also related to versions. In Artifact Hub, every package (a task or pipeline in this case) must have a version. Given that all tasks in a catalog will share the same version, I understand that sometimes the version for a task will be bumped even though that particular task may not have changed at all. Users in Artifact Hub can subscribe to new releases notifications and, in cases like the one just mentioned, they may be notified about a new package release when nothing actually changed, which could be a bit annoying for users. I've already discussed this concern with @QuanZhang-William in Slack, and he mentioned that you were moving to smaller repos with fewer (or even one) packages per repo, which would definitely help.

Yes, that's the idea for the git versionning, smaller repositories *and* sharing the version for all the content in those, where it make sense. For example, we may have a `golang` task repository that has a bunch of task (`golang-build`, `golang-test`, …) that, do make sense to bump each time 👍🏼.

> * Versions: at the moment the version in the tag file **must** match the one in the manifest file. If you'd like a different behavior please let us know. In catalogs with a lot of packages, this may require a bit of work I guess, touching quite a few manifest files every time a bump is needed. Maybe you plan to eventually remove the version in the manifest, not sure (from: [Versioning will move from the resources themselves to the Catalog as a whole](https://github.com/tektoncd/community/blob/main/teps/0115-tekton-catalog-git-based-versioning.md#versioning-in-a-catalog)).

Indeed, this is something I was wondering about as well. Ideally, the "version" is present when the user fetche/install the task but not necessarily *in* the repository. This "would" mean, however, that artifacthub (or another thing) would be responsible for adding this (and thus, *kind-of* mutating the source "live", which might or might not be something artifacthub wants ?)

**Comment by QuanZhang-William** [comment]
This is amazing! Thanks for the great work! 💯 💯 

> * Versions: at the moment the version in the tag file **must** match the one in the manifest file. If you'd like a different behavior please let us know. In catalogs with a lot of packages, this may require a bit of work I guess, touching quite a few manifest files every time a bump is needed. Maybe you plan to eventually remove the version in the manifest, not sure (from: [Versioning will move from the resources themselves to the Catalog as a whole](https://github.com/tektoncd/community/blob/main/teps/0115-tekton-catalog-git-based-versioning.md#versioning-in-a-catalog)).

I think this assumption is valid and ok (at least for this iteration of integration). In the directory-based versioning in Tekton Hub, we also have such assumption that version in the manifest file **must** matches the directory path. We can further investigate the improvement and contribute in the future 🙂.

> When you have a chance please give it a try on staging and let us know your thoughts 🙂

I just played around it and looks great! Will collect more feedback in the Tekton community and loop back ASAP!

**Comment by tegioz** [comment]
Thanks @vdemeester @QuanZhang-William, we are glad you like it so far 😄

> This "would" mean, however, that artifacthub (or another thing) would be responsible for adding this (and thus, _kind-of_ mutating the source "live", which might or might not be something artifacthub wants ?)

Artifact Hub has always opted for *not* hosting or serving the artifacts themselves since the beginning, so it'd probably be better if it stays out of the way. The main goal is to offer exploring and discoverability capabilities for multiple kinds of artifacts, that both users and CNCF (and other open source) projects can leverage. But the intention is that installation instructions always point directly to an external repository.

**Comment by vdemeester** [comment]
> Artifact Hub has always opted for _not_ hosting or serving the artifacts themselves since the beginning, so it'd probably be better if it stays out of the way. The main goal is to offer exploring and discoverability capabilities for multiple kinds of artifacts, that both users and CNCF (and other open source) projects can leverage. But the intention is that installation instructions always point directly to an external repository.

Fair enough 👼🏼

**Comment by QuanZhang-William** [comment]
Hi @tegioz, sorry for the delay~ I have shared the prototype and collected some feedbacks in the Tekton Community and everything looks good 😄 . One feedback we have is about the versioning selection in the repo registration process:

In the future we want to enforce publishers to follow git-based versioning; we will **Only** support directory-based versioning for the current [centralized catalog repo](https://github.com/tektoncd/catalog) (which will be archived in the next 9 month), so could you please help remove the versioning selection button in the UI and hardcode to "git" in production? 

Thanks!

![image](https://user-images.githubusercontent.com/26396370/192633690-2c0cd026-5466-4b38-9a12-38ecb79b3359.png)

**Comment by tegioz** [comment]
Hi @QuanZhang-William

Sure, no problem, we can do that 👍

We'll leave existing Tekton repos using the versioning they selected at creation time to avoid breaking anything. Although most seem to be tests (maybe from the Tekton Community), there are some like https://artifacthub.io/packages/search?repo=startx-tekton-catalog that look like valid repos.

**Comment by vdemeester** [comment]
> In the future we want to enforce publishers to follow git-based versioning; we will **Only** support directory-based versioning for the current [centralized catalog repo](https://github.com/tektoncd/catalog) (which will be archived in the next 9 month), so could you please help remove the versioning selection button in the UI and hardcode to "git" in production?

@QuanZhang-William I missed that discussion, but I am not sure to understand *why* we would want to completely drop directory-based versioning. I understand that we would want to maintain git-based catalogs, in the tektoncd/tektoncd-catalog org, but I am not sure I understand why force others to switch to git-based. If this layout work for some teams, people, companies, why would we force them to change ?

**Comment by tegioz** [comment]
We were going to do this right away but we'll hold on a bit until you can finish the discussion and confirm 🙂

If you opt for not removing it, maybe instead we could default it to `git` versioning for new repos and add a note below explaining that the Tekton community now recommends using this new layout (or something similar).

**Comment by vdemeester** [comment]
> If you opt for not removing it, maybe instead we could default it to `git` versioning for new repos and add a note below explaining that the Tekton community now recommends using this new layout (or something similar).

That would definitely be my suggestion 🙃. I still think the "legacy" (folder is a better word probably) layout can have some benefit for some organizations.

**Comment by PuneetPunamiya** [comment]
> @QuanZhang-William I missed that discussion, but I am not sure to understand why we would want to completely drop directory-based versioning. I understand that we would want to maintain git-based catalogs, in the tektoncd/tektoncd-catalog org, but I am not sure I understand why force others to switch to git-based. If this layout work for some teams, people, companies, why would we force them to change ?

Yep, I do agree on @vdemeester, on not removing the support for directory based versioning

**Comment by QuanZhang-William** [comment]
> We were going to do this right away but we'll hold on a bit until you can finish the discussion and confirm 🙂
> 
> If you opt for not removing it, maybe instead we could default it to `git` versioning for new repos and add a note below explaining that the Tekton community now recommends using this new layout (or something similar).

@tegioz I apologize for the back and forth :hot_face: . We had another WG meeting today and revisited [TEP-0115](https://github.com/tektoncd/community/blob/main/teps/0115-tekton-catalog-git-based-versioning.md#from-directory-based-to-git-based) about directory-based versioning.

In summary: going forward, we will support both directory-based and git-based versioning; however git-based versioning is what we highly recommended ([TEP-0115](https://github.com/tektoncd/community/blob/main/teps/0115-tekton-catalog-git-based-versioning.md#from-directory-based-to-git-based) needs to be updated). And thanks @vdemeester and @PuneetPunamiya for the suggestion!

In this case, I agree we should default to `git` and add an explanation that git-based versioning is what we recommended (maybe we can even show a badge in the UI saying this repo uses legacy layout, but we can address this later 😄 )

**Comment by tegioz** [comment]
No worries @QuanZhang-William, we'll take care of that 👍

**Comment by tegioz** [comment]
Done 🙂 

<img width="566" alt="tekton-git" src="https://user-images.githubusercontent.com/1213902/193287286-0821786c-991d-4114-b530-afaee56280aa.png">

**Comment by QuanZhang-William** [comment]
Hi @tegioz , thanks for the help~

I tried to add a new repo with Tekton Pipeline Kind (id: c4ed8c98-628e-422d-92fd-0f8bbba33486; name: quan-demo-pipeline-git-versioning). In the control panel it shows a green checkmark, but it does not seem to be surfaced in the UI when I searched it, could you please help take a look? 🙏 

![image](https://user-images.githubusercontent.com/26396370/193355128-505dd0d0-8ac9-452d-9801-a1b77c0289ae.png)

**Comment by tegioz** [comment]
Hi @QuanZhang-William

The problem was that the tasks in your sample pipeline didn't include a `taskRef` section, which we were expecting. We've realized it's actually optional, so we are not using it anymore to get the task's name. Your pipeline is now visible on the UI 🙂
