### ISSUE TITLE
Add a new status indicating repos are provided by the official organization of its kind

### ISSUE THREAD

**Issue by QuanZhang-William** [artifacthub/hub#2328]
**Is your feature request related to a problem? Please describe.**
As an official `Tekton` Catalog maintainer, I would like to differentiate `Tekton` Catalog repos provided by the official Tekton organization (official catalog) from other `Tekton` Catalog repos(community catalog) in the Artifact Hub.

However, this definition of the above `official` does not align with the [official status](https://artifacthub.io/docs/topics/repositories/#official-status) in Artifact Hub. Such inconsistency in the definition of "official" could bring a lot of confusion to both Tekton and Artifact Hub users.

**Describe the solution you'd like**
I would like to request another label/status (like "`Trusted`", "`Official Source`"...)to indicate that a specific repo is provided by official provider of the repo kind technology (e.g. **only** the official Tekton catalog provider can claim such label/status)

**Describe alternatives you've considered**
Technically this request can be supported in the current definition of `official status` (in a hacky way) as it is granted manually, where Tekton official catalog provider can explicitly ask Artifact Hub maintainers to reject any Tekton kind official status request from other repo providers. However such inconsistency in the definition of `official` could bring a lot of confusion to both `Tekton` and Artifact Hub users.

**Additional context**
The `Tekton` community is working on adding support tier to Tekton catalog tasks/pipelines. In summary, we plan to only mark catalog repos in [this specific org](https://github.com/tektoncd-catalog) as “official” catalog. Other contributors are welcome to bring their own catalog repo, and such catalog will be treated as “community” catalog.

This new label/status would also be beneficial for other repository kinds that are in a similar situation, like `Keda`, `Keptn`, `Kubewarden`, etc.

**Comment by tegioz** [comment]
Thanks for creating the issue @QuanZhang-William!

Now we just need to come up with a good name for this new status 😇

**Comment by tegioz** [comment]
Hi @QuanZhang-William 

We've been thinking a bit more about this and have some ideas for the new status/badge 💡 

However.. once we "saw" it, we realized that maybe it was a bit redundant. Let me explain.

In the end, what we'd like to convey with this badge is that this content has been provided by the Tekton organization in this case. But we already have a mechanism to display that information, that it's not yet being leveraged in the case of the Tekton catalog repository.

<img width="1010" alt="Screen Shot 2022-09-16 at 09 04 59" src="https://user-images.githubusercontent.com/1213902/190577362-c25063c2-8d91-4ed5-a1d1-68c8a59de3f7.png">

When we added support for Tekton tasks, we listed the Tekton catalog ourselves under the Artifact Hub organization, [suggesting that you could claim its ownership at any time](https://github.com/tektoncd/catalog/issues/626#issue-794184216). When we chatted yesterday I assumed this was already done. So it'd be great if you could complete the process, as it's probably one of the things users check out when they inspect a package. A Tekton task directly provided by the Tekton organization is more likely to be trusted by users 🙂

Other organizations behind some of the supported kinds are already doing that:

<img width="1010" alt="Screen Shot 2022-09-16 at 09 19 41" src="https://user-images.githubusercontent.com/1213902/190580317-358cb3dd-6ad6-4bbc-a15e-6903896eb965.png">

<img width="1010" alt="Screen Shot 2022-09-16 at 09 20 04" src="https://user-images.githubusercontent.com/1213902/190580331-0fc0bfdc-84d3-4559-b73e-e1b785e0afd4.png">

You can also update the display name of the repository once you claim its ownership and make clear it's official, like KEDA did (please see screenshot above).

So we could definitely add another badge, that's not a problem. But if its meaning will be very similar to something that we are already displaying in a generic way, maybe we should reconsider it.

Hope this helps!

**Comment by tegioz** [comment]
And of course, when the ownership claim process is complete, you can also get the the [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status for both the tasks and pipelines repositories 😉

**Comment by vdemeester** [comment]
Thanks @tegioz, I think that does, indeed make sense. The org would become `Tekton` (or `tektoncd`) for resources coming from our set of *official* tasks, and by being a verified publisher, I think it's enough 👍🏼.

One naive additional question is, I see the that currently the "main" Tekton task coming from the catalog are "managed" by ArtifactHub itself. If we (tekton commmunity) create an account and make it verified, and index our "official" images, I think it would then make sense for the artifacthub configuration to be removed. Am I right or am I making no sense ? 🙃

**Comment by tegioz** [comment]
Awesome! 

You can claim the ownership of both repositories (Tekton tasks and pipelines) from the Artifact Hub control panel. It's a [fully automated and simple process](https://artifacthub.io/docs/topics/repositories/#ownership-claim).

It'd be better if we do it that way because a lot of the Tekton packages in AH have stars, subscriptions and possibly quite a few links out there. If we remove it from the AH org that information would be lost, whereas if it's transferred to your organization everything will stay as it is.

Please let me know if you have any problem with the process, happy to help 🙂

**Comment by vdemeester** [comment]
I started the "ownership" process for the current catalog 👼🏼 https://github.com/tektoncd/catalog/pull/1073. I created an org tektoncd and I'll add owners from the catalog there.
For new ones (the git based), we'll know how to do it as well, thanks @tegioz 🤗

**Comment by tegioz** [comment]
No worries, my pleasure 😊 

Can you hold on one min sec before you merge? I'll be back right now 😉

**Comment by tegioz** [comment]
It isn't common to have two AH repositories using the same git repository as source (actually I can't recall any other case), but it's definitely possible.

**Comment by vdemeester** [comment]
@tegioz Ah I see, I wondered how it would work, it does make sense. Long term, we'll have more granular repositories for this so it will be easier to manage.

**Comment by QuanZhang-William** [comment]
Thanks @tegioz @vdemeester , and it sounds good to me!

@vdemeester currently the ```tekton``` org indexes our [centralized catalog repo](https://github.com/tektoncd/catalog). I think we can create another org like ```tekton-official``` indexing the repos in the [official catalog org](https://github.com/tektoncd-catalog) (once we set it up), and remove the ```tekton``` org after 9 month when the centralized catalog repo is archived?

I feel like we'd better make the word "official" explicit in the AH org name.

**Comment by QuanZhang-William** [comment]
Hi @tegioz, I have another question about the [official status](https://artifacthub.io/docs/topics/repositories/#official-status). It is by definition "the publisher owns the software deployed by a package". I was wondering that do Tekton official catalogs actually fit to this requirement and can we request "official status" badge for Tekton official catalogs? This is just to confirm my understanding of "official status" is correct in Artifact Hub :)

**Comment by tegioz** [comment]
Hi @QuanZhang-William 👋 

That text was written with Helm charts and OLM operators in mind, and probably needs to be extended to make it more comprehensive and cover new cases 😇

I think we can better answer this (or at least what that definition tries to convey) with a few examples.

If HashiCorp was to publish and maintain a Tekton task with the same functionality as [terraform-cli](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/terraform-cli), published by Tekton, which one should be the official one? Or if Aqua security did the same for the [trivy-scanner](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/trivy-scanner) one? Those are the organizations behind that software, the ones who actually own it. And IMHO they deserve the option of claiming the official status for a package that's focused on their software.

The current definition may fit better for Helm charts like I said. But let's look at it the other way around. If there were two Helm charts to install the Tekton dashboard, one provided by the Tekton organization and one provided by the Helm organization, which one should be the official? According to the current definition, it'd be the one provided by the Tekton organization, regardless the Helm organization is behind the charts technology.

Maybe we can consider redefining what `official` means for each repository kind, but I'm concerned this may end up confusing both users and organizations.

Hope this helps and makes sense 🙂

**Comment by vdemeester** [comment]
@tegioz I do think artifacthub definition of "official" make sense (at least to me), and I don't really see any reason for changing this specifically for Tekton or something else.

**Comment by tegioz** [comment]
Thanks @vdemeester 👍

I'll close this issue for now then, please feel free to reopen if needed 🙂
