### ISSUE TITLE
Falco rules and OPA policies sections in control panel

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#240]
In addition to tracking the Falco rules and OPA policies maintained by the Falco project automatically (#239), other organizations and users should be able to create and maintain their own rules and policies.

One way of doing this would be by providing some sort of editor/forms in the control panel.

Another way would be to allow users to add repositories where to get rules and policies from. It could be something similar to what we do for Helm charts repositories. That way anyone could manage their rules outside of the Artifact Hub and add them to the Hub for discovery. If the format used to describe those configurations was the same used by the [Cloud Native Security Hub](https://github.com/falcosecurity/cloud-native-security-hub), the tool described in #239 would be generic.

**Comment by mattfarina** [comment]
This could get complicated. For example, if the hub hosts the rules then where do people file issues or suggest changes? These types of burdens become the hubs. I don't think we want to do that.

I would instead suggest we either:

1. Try to work with those communities on a spec we can read from
2. Create a general spec people can implement to have their things listed

Then they can host the things where they like, get issues where they like, and own the process to manage them.
