### ISSUE TITLE
[OFFICIAL] smarter

### ISSUE THREAD

**Issue by ericvh** [artifacthub/hub#2469]
In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by a package. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (HashiCorp in this case), not just the chart.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: smarter
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://getsmarter.io
- **Source code URL** *(if available)*: https://gitlab.com/smarter-project

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @ericvh 👋 

Could you please add some more content to the README files in the `cni`, `device-manager` and `dns` charts? There is [a lot of useful information in the source repos](https://gitlab.com/smarter-project/smarter-cni/-/blob/main/README.md) that may be handy to users in AH as well. The `cloud` one looks great! 👍

**Comment by ericvh** [comment]
Okay, I've pushed updates to add a bit more to the README for each of the
component parts.

     -eric

**Comment by tegioz** [comment]
Thanks, the repo has been marked as official 👍
