### ISSUE TITLE
Break number of vulnerabilities further down -> Image/TARGET

### ISSUE THREAD

**Issue by hpvd** [artifacthub/hub#2487]
**Is your feature request related to a problem? Please describe.**
Just working with your great security overview (modal), **to identify the priorities to work on** within a complete helm chart.
e.g. https://artifacthub.io/packages/helm/apache/pulsar?modal=security-report

For this it would be pretty handy, to have the break-down of the severity of the vulnerabilities further down till the "Target"-layer (it's already down to image-layer, see attachment).
Having this, one would not have to count in each target-layer the number of vulnerabilities for each severity-level.

**Describe the solution you'd like**
showing the sums of vulnerabilities per severity-level for each target-layer (total and fixable).
This would save the process of manual counting, which may occur several times for each helm chart, since numbers change over time...

**Describe alternatives you've considered**
manual counting...

**Additional context**

![2022-11-06_17h25_22](https://user-images.githubusercontent.com/5681880/200184287-647707d9-dc2e-4fc5-9c92-ded78a0d4b0a.png)

**Comment by tegioz** [comment]
Hi @hpvd 

Thanks! Let us think a bit where this information could fit nicely. We'd rather not to add more entries to the summary table as it's already quite long in some cases.

**Comment by hpvd** [comment]
Hi @tegioz

fully agree, that a detailed information like this not fits nicely into the main table.
Maybe there is a some space in the head of the unfolded area when you click the `show vulnerabilities` button...

**Comment by tegioz** [comment]
This is ready @hpvd 🙂 

<img width="1404" alt="Screenshot 2022-12-05 at 09 35 09" src="https://user-images.githubusercontent.com/1213902/205590963-b51527d8-dc5d-47f3-ba96-209c930244e1.png">

**Comment by hpvd** [comment]
wow looks and works great :-)
Many thanks for implementing this!!
