### ISSUE TITLE
Lowercase readme.md not found in Helm

### ISSUE THREAD

**Issue by deepy** [artifacthub/hub#2510]
**Describe the bug**
Lowercase `readme.md` in helm package leads to UI saying "This package version does not provide a README file"

**Expected behavior**
If `helm show readme` works then artifacthub should also pick up the readme.
The casing of README files should not affect them being picked up or not, both `readme.md` and `README.md` should be valid

**Screenshots**
[Example repository](https://artifacthub.io/packages/helm/mastodon/mastodon/2.1.0)

**Comment by tegioz** [comment]
Hi @deepy

At the moment Artifact Hub requires the readme file to be named `README.md` as specified in the [Helm chart structure documentation](https://helm.sh/docs/topics/charts/#the-chart-file-structure). It looks like the [Helm show command](https://github.com/helm/helm/blob/a27c468c82fe2cb9a4e07d7c82c9df6b6fed9ed7/pkg/action/show.go#L49) is a bit more permissive though. But this command also supports `.txt` files, whereas AH requires the content to be markdown to render it nicely in the UI (they don't really need to match).

In general I'd recommend to follow the casing used in the docs, as in other situations even Helm (or other tools) can be more strict (see [templates/NOTES.txt](https://github.com/helm/helm/blob/f08db5c899c4e312c72ae863acbb90ac8a4747ed/pkg/action/install.go#L61), for example).

Said that, I think adding support for lowercase `readme.md` files should cause any harm, so we'll take care of it 👍
