### ISSUE TITLE
readme not from selected chart version

### ISSUE THREAD

**Issue by brightdroid** [artifacthub/hub#2552]
**Describe the bug**
The chart information (readme) always show the current version, not from the selected chart version.

**To Reproduce**
1. Go to https://artifacthub.io/packages/helm/bitnami/postgresql
2. Click on chart version 11.7.0
4. Compare with real readme from chart

**Expected behavior**
The readme should be from the selected chart version.

**Comment by tegioz** [comment]
Hi @brightdroid

I've just tested the chart you mentioned in your report but everything seems to be fine, the readme corresponding to the selected version is displayed:

<img width="2559" alt="readme-comparison" src="https://user-images.githubusercontent.com/1213902/204215266-a09d79d8-d0d3-45f6-84a7-8c6f7ccc3d8c.png">

If you download the packages for those versions ([12.1.2](https://charts.bitnami.com/bitnami/postgresql-12.1.2.tgz) and [11.7.0](https://charts.bitnami.com/bitnami/postgresql-11.7.0.tgz)) and inspect the readme files, the `image.tag` field in the table matches the corresponding value in the screenshot attached for each version.

The `TL;DR` section also seems to have changed between versions:

<img width="2559" alt="readme-comparison-2" src="https://user-images.githubusercontent.com/1213902/204217081-428437b4-89a0-442a-9720-39b537b8bb92.png">

I can't see any issue here, maybe you can provide some more details.

**Comment by brightdroid** [comment]
Oh didn't noticed this works, but if you scroll down (old version selected) you'll see the the new parameters are shown.

E.g. the following parameters are new and didn't existed in the tested previous version:
- primary.*
- readReplicas.*
- ...

Most of the bottom page seem to be change, which is not shown.

**Comment by tegioz** [comment]
All the `primary.*` and `readReplicas.*` parameters are available in the readme file of the chart package version `11.7.0` <https://charts.bitnami.com/bitnami/postgresql-11.7.0.tgz>, so Artifact Hub is displaying what it gets from the Bitnami repo 😇

You can download that file and double check it yourself. Maybe there is a problem with the content in the source repo, but unfortunately we can't help with that 🙂.

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂

**Comment by brightdroid** [comment]
Sorry you're right. The root-cause for this bugreport was the gitlab chart which uses bitnami helm chart, but as I now rechecked they use the old versions from https://github.com/bitnami/bitnami-docker-postgresql which does not have the new paramaters.

Sorry and Thank you

**Comment by tegioz** [comment]
Cool, no problem 👍
