### ISSUE TITLE
Support markdown in Helm chart changes annotations

### ISSUE THREAD

**Issue by stevehipwell** [artifacthub/hub#2689]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to build the Helm chart changes annotations (`artifacthub.io/changes`) from my CHANGELOG but as Artifact Hub doesn't support markdown in the Helm chart changelog view this looks ugly unless the formatting is removed.

**Describe the solution you'd like**
I'd like Artifact Hub to render markdown in the Helm chart changelog view, even if this only supports a subset of formatting.

**Describe alternatives you've considered**
I currently manually strip out the formatting.

**Additional context**
n/a

**Comment by tegioz** [comment]
Hi @stevehipwell 👋

Please see [this Slack thread](https://cloud-native.slack.com/archives/C0103CTR3RB/p1616571755016700) for a related discussion 🙂

**Comment by tegioz** [comment]
Using the structured changes annotation format makes it look nicer on AH. You can even include links in you'd like.

<img width="819" alt="changelog" src="https://user-images.githubusercontent.com/1213902/213216550-a6114212-44ed-4d0b-a778-a89603e3300b.png">

**Comment by stevehipwell** [comment]
@tegioz I don't agree it looks better, markdown allows us to add correct emphasis for `code`, _items_ or **IMPORTANT**; as well as inline links. But the main reason why this doesn't work is that it isn't portable and requires everything to be double handled if you have a CHANGELOG; please note that the CHANGELOG content can be show on the GitHub release so it's already serving multiple purposes.

**Comment by tegioz** [comment]
I think I didn't explain myself well. I meant that it looks nicer than the other plain text option we offer, not better than markdown 🙂 

I understand what you mean, and it makes sense. But we need to keep in mind the other use cases for that information, as discussed in the Slack thread I shared above. Those changes entries are passed to the webhooks, for example, which may prefer not having the content mixed with the styling and format. We provide the structured changes to them as well, which allows them to quickly identify the kind of the change entry when available (fix, addition, etc). This can be used to take action only on some specific kinds without having to parse markdown content that may not follow any convention.

But having to handle the changelog twice isn't nice, I agree. Not sure if it may help if your case, but AH has an endpoint to generate a markdown version of your changelog that uses the [keepachangelog](https://keepachangelog.com/en/1.0.0/) conventions. You can see an example [here](https://artifacthub.io/api/v1/packages/helm/artifact-hub/artifact-hub/changelog.md) for the changelog screenshot I shared before (where you can see a button as well to download it). This endpoint could be used to automate the markdown version of your changelog if that's an option. Maybe it'd be interesting to have a tool that also does the reverse: from a markdown changelog that follows some convention (i.e. keepachangelog), generate some entries that could be included in the AH metadata automatically.

**Comment by stevehipwell** [comment]
I've seen the endpoint to create the changelog but I already have a changelog in keep a changelog format. Even if I didn't have a changelog the current format doesn't have the formatting to render the changes back into markdown.

On further reflection what I'd ideally like would be an annotation to pass up a raw markdown changelog and let Artifact Hub choose how to render it (e.g. `artifacthub.io/changlog`). If this isn't possible having then Artifact Hub accept markdown in the existing changes string and either show or remove the formatting would also be workable.

**Comment by tegioz** [comment]
Stripping the markdown format from the text in the changes entries sounds good, we can do that 👍 

Out of curiosity, I've been taking a look at how others are addressing this problem and I've found some cool stuff. ENIX, the publisher of x509-certificate-exporter, maintains a [nice changelog in AH](https://artifacthub.io/packages/helm/enix/x509-certificate-exporter?modal=changelog) that's [automatically generated from the changelog in the GitHub release in their release workflow](https://github.com/enix/x509-certificate-exporter/blob/2022fd36b941c5cb2aa405011e8b62b2edcf6d00/.github/workflows/release.yml#L549-L705). It'd be awesome to have a generic version of that packaged in a GitHub action that could be easily reused 🙂
