### ISSUE TITLE
New resource type Knative Client Plugin

### ISSUE THREAD

**Issue by dsimansk** [artifacthub/hub#2714]
Hi folks, 

I'm Client WG lead in Knative project. Currently I'm looking at adding Knative Client CLI `kn` plugins to the Artifact Hub. In a nutshell they're similar to `kubectl` plugins, executable binary added to $PATH with a specific name to be recognized by `kn`. We don't leverage krew a delivery/download mechanism, only Homebrew and GH releases for now. 

We have a set of curated plugins under Knative Sandbox org with `kn-plugin-*` name pattern. I went through KEDA scalers issues, it seems quiet similar to our needs. My assumption is that adding generic type with install instructions for homebrew and pointer to Github release page should be sufficient for our needs.

Knative Client: https://github.com/knative/client
Plugin example: https://github.com/knative-sandbox/kn-plugin-source-kafka
Homebrew tap: https://github.com/knative-sandbox/homebrew-kn-plugins

1. Would it be possible to have "Knative Client Plugin" as a type? Should it be rather specific name? Or more generic e.g. only "Knative"?
  - In the future there might be ask for additional type of resources, e.g. "Knative Eventing Source" 

2. There's a plan to capture different Knative metadata in a specific repository e.g. knative-sandbox/catalog (doesn't exist yet)? Is it a good place to start with `artifacthub-pkg.yml` for our curated plugins for  auto indexing? Hence external plugins can be listed

**Comment by dsimansk** [comment]
@tegioz thanks sounds great to me! :) I'll go through the links to get familiar with the metadata. :)

**Comment by tegioz** [comment]
This is ready @dsimansk! You can see a [sample package in action at staging](https://staging.artifacthub.io/packages/knative-client-plugin/knative-test/kn-plugin-source-kafka) 🙂

<img width="1548" alt="knative" src="https://user-images.githubusercontent.com/1213902/216022643-b186e3c2-10d6-4eaf-9195-bf794cfa7120.png">
