### ISSUE TITLE
Invalid change: description not provided

### ISSUE THREAD

**Issue by bianchi2** [artifacthub/hub#2787]
Hi! Even though docs say that `artifacthub.io/changes` annotation can be in a simple format of a list of strings, it does not work and the scanner says it failed to parse the new version:

```
error preparing package: error enriching package from annotations: 1 error occurred:

* invalid change: description not provided
```

So, the following format does not work:

```
  artifacthub.io/changes: |-
    -  Stop supporting 1.19-1.20 k8s
    -  Fix 1 exit code when fetching PRs
```

Is there anything wrong with such a format? Changing it to:

```
artifacthub.io/changes: |
  - kind: fixed
    description: Stop supporting 1.19-1.20 k8s
  - kind: fixed
    Fix 1 exit code when fetching PRs
```
fixes it. But using strings is preferable for us, as it's easier to generate annotations from git log.

**Comment by bianchi2** [comment]
Turned out that strings were unquoted. Just the error message was misleading.

**Comment by tegioz** [comment]
Hi @bianchi2 👋 

Just in case it helps, you can use the [ah lint](https://artifacthub.io/docs/topics/cli/) tool in your [CI workflows](https://github.com/artifacthub/hub/blob/0347caccf0d1b3a6dca93b012ab89f1b33cbcb07/.github/workflows/ci.yml#L40-L50) to catch issues with AH metadata earlier 🙂

**Comment by bianchi2** [comment]
thanks @tegioz yeah, I have discovered it a bit later :)
