### ISSUE TITLE
Hardcoded ImagePullpolicy

### ISSUE THREAD

**Issue by maxpaynebeck** [artifacthub/hub#2791]
**Describe the problem**
Currently the imagepullpolicy is hardcoded as NotPresent. Can we add it a template so that we can modify it in the values file.

**Additional context**
We want imagepullpolicy as a configurable value.

**Comment by tegioz** [comment]
Hi @maxpaynebeck 👋

The image pull policy can already be provided from the values file (please see: <https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=values-schema&path=pullPolicy>). However, I've just noticed that this value isn't used [in one place, where it is hardcoded](https://github.com/artifacthub/hub/blob/3d293189d569ce2f6549e108446eb26df7eb75d6/charts/artifact-hub/templates/hub_deployment.yaml#L44). We'll take care of that one soon, thanks!

**Comment by maxpaynebeck** [comment]
Thanks
