### ISSUE TITLE
Setup CDN for staging and production deployments

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#284]

**Comment by mattfarina** [comment]
Follow-up from the meeting today... Here is cloudflare... https://www.cloudflare.com/. Note, there is a free tier at https://www.cloudflare.com/plans/. It may not work well with our integration through. You need to have them manage your DNS.

**Comment by tegioz** [comment]
AWS CloudFront has been setup for the staging and production environments for now. Happy to revisit this in the future and explore some other options in more depth.
