### ISSUE TITLE
[OFFICIAL]  wsugarman-keda-scalers

### ISSUE THREAD

**Issue by wsugarman** [artifacthub/hub#2841]
In Artifact Hub, the `official` status means that the publisher **owns the software deployed** by a package. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (HashiCorp in this case), not just the chart.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: wsugarman-keda-scalers
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://github.com/wsugarman/charts
- **Is the publisher a CNCF project?:** No. I am a developer publishing OSS KEDA scalers
- **Source code URL** *(if available)*: https://github.com/wsugarman/durabletask-azurestorage-scaler
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @wsugarman 👋 

I'm not sure if the `official` status applies to this case. I think we are not doing a great job with the `official` status definition, which can lead to misunderstandings. We need to find some better wording to make the intent clearer, both in the Artifact Hub UI and in the official status request issue template.

IMHO, for the `Durable Task KEDA External Scaler` package to be marked as official, it would need to be published by Microsoft/Azure. I've seen that you belong to the Microsoft organization in GitHub, so if you could move this repository to the Azure org in GitHub and get it published from the [Azure organization in AH](https://artifacthub.io/packages/search?org=azure&sort=relevance&page=1), we'd be happy to mark it as official.

Hope this makes sense 🙂

**Comment by wsugarman** [comment]
That makes perfect sense. I was thinking that because I owned the software in addition to the chart, that I should apply for "official," but your description makes sense.

Thanks!

**Comment by tegioz** [comment]
We've just updated the `official` definition. Hope this one makes the intent clearer 😇 Thanks!

> In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.
