### ISSUE TITLE
[OFFICIAL] deeploy-core

### ISSUE THREAD

**Issue by TimKleinloog** [artifacthub/hub#2870]
We would like to request the `official` status for our repository `deeploy-core/deeploy` Since we should be considered owner of the software: the chart installs the official Deeploy software.

- **Repository name** *(in `artifacthub.io`)*: deeploy-core
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** : https://artifacthub.io/packages/helm/deeploy-core/deeploy
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://gitlab.com/deeploy-ml/deeploy-core
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*: https://deeploy.ml

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ x ] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [ x ] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [ x ] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @TimKleinloog 👋 

Could you please take a look at why the table in the values section isn't rendered nicely? I can see it looks fine on GitLab though. Lots of packages in AH use tables in the README and they are rendered correctly, not sure if it's related to some sort of markdown flavor difference. AH's UI uses [react-markdown](https://github.com/remarkjs/react-markdown), just in case you need to run any test. Thanks!

<img width="1074" alt="deeploy" src="https://user-images.githubusercontent.com/1213902/224009529-1848faeb-e773-42e2-9aea-248e49b332f5.png">

**Comment by TimKleinloog** [comment]
Hi @tegioz ,

Formatting should be fixed now.

Best,
Tim

**Comment by tegioz** [comment]
Thanks @TimKleinloog, official status granted!
