### ISSUE TITLE
[OFFICIAL] Promhippie

### ISSUE THREAD

**Issue by tboerger** [artifacthub/hub#2871]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: promhippie
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://github.com/promhippie
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/promhippie
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @tboerger 👋

I'm not sure if the official status applies to this case. As an example, IMHO for the `prometheus-vcd-sd` package to be marked as official it'd need to be published by VMware. The same would apply to the GitHub, Jenkins or Hetzner Prometheus exporters.

Hope this makes sense 🙂

**Comment by tboerger** [comment]
But these are projects developed by me, and not authored by these companies. If I compare this with the vault example I thought this is similar to that.

**Comment by tegioz** [comment]
I understand. We've recently updated the official definition a bit as well as the examples provided as it wasn't very clear, to be honest ([last week there was a similar case, for example](https://github.com/artifacthub/hub/issues/2841#issuecomment-1455106630)). But I still think it doesn't make the intent clear enough, so we'll need to keep working on it 😅

Let's imagine I write an operator for MySQL, all written from scratch by me. Then I'd like to publish a chart on AH to install it. The software to install would be authored by me, as well as the package that installs it. However, my software primarily focuses on MySQL, which I do not own. If my version was marked as official, what would happen if MySQL/Oracle were to publish a Kubernetes operator themselves on AH? Having multiple official artifacts for the same "thing" would probably confuse users, as it wouldn't be helpful for them when deciding between multiple options. And in this case I'd say that status probably fits them better than me.

**Comment by tboerger** [comment]
I get your point, but in your example it's just a wrapper which launches software written by somebody else while my projects only communicate with an api provided by a company.

If this project won't get an official badge it's no problem, I just interpret the defined requirements differently.

**Comment by tegioz** [comment]
I see what you mean, and I understand how it can be interpreted differently. There are many different repository and artifacts kinds and it's tricky to define this properly in a short description. If you can think of any way we could clarify this in the documentation we'd really appreciate it, any help is welcome! 🙂

Please note that there is already [another GitHub exporter chart in AH](https://artifacthub.io/packages/helm/jkroepke/github-exporter) and even more options searching out of AH. In my example, one of the things I was trying to highlight is that ideally there should be only an official option for a given "thing". In the end the goal of that status is to help users picking among multiple choices. And IMHO neither of the current options should have that status over the other.

But again, this is tricky and it'll probably lead to some more interesting conversations that will help us improve how this status works. Thanks!

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
