### ISSUE TITLE
[OFFICIAL] kubewarden-crds helm chart

### ISSUE THREAD

**Issue by viccuad** [artifacthub/hub#2873]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: [kubewarden-crds](https://artifacthub.io/packages/helm/kubewarden/kubewarden-crds)
- **Official packages** *(leave empty if all packages in the repository are official)*:  all
- **Project URL:** https://www.kubewarden.io/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** yes, sandbox
- **Source code URL** *(if available)*: https://github.com/kubewarden/helm-charts/tree/main/charts/kubewarden-crds
- **Other relevant URLs:** https://www.cncf.io/projects/kubewarden/

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it 
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by viccuad** [comment]
Hi, I would like to mark all the Kubewarden ArtifactHub packages published by us the Kubewarden Maintainers as official.
These list is ~30 packages:

Helm charts:
- [kubewarden-crds ](https://artifacthub.io/packages/helm/kubewarden/kubewarden-crds) (this issue)
- [kubewarden-controller](https://artifacthub.io/packages/helm/kubewarden/kubewarden-controller)
- [kubewarden-defaults](https://artifacthub.io/packages/helm/kubewarden/kubewarden-defaults)

Policies:
- https://artifacthub.io/packages/kubewarden/allowed-fsgroups-psp-policy/allowed-fsgroups-psp
- https://artifacthub.io/packages/kubewarden/disallow-service-loadbalancer/disallow-service-loadbalancer
- https://artifacthub.io/packages/kubewarden/environment-variable-policy/environment-variable-policy
- https://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures
- https://artifacthub.io/packages/kubewarden/volumemounts-policy/volumemounts
- https://artifacthub.io/packages/kubewarden/allowed-proc-mount-types-psp/allowed-proc-mount-types-psp
- https://artifacthub.io/packages/kubewarden/allow-privilege-escalation-psp/allow-privilege-escalation-psp
- https://artifacthub.io/packages/kubewarden/apparmor-psp/apparmor-psp
- https://artifacthub.io/packages/kubewarden/capabilities-psp/capabilities-psp
- https://artifacthub.io/packages/kubewarden/deprecated-api-versions-policy/deprecated-api-versions
- https://artifacthub.io/packages/kubewarden/disallow-service-nodeport/disallow-service-nodeport
- https://artifacthub.io/packages/kubewarden/echo/echo
- https://artifacthub.io/packages/kubewarden/env-variable-secrets-scanner/env-variable-secrets-scanner
- https://artifacthub.io/packages/kubewarden/flexvolume-drivers-psp/flexvolume-drivers-psp
- https://artifacthub.io/packages/kubewarden/host-namespaces-psp/host-namespaces-psp
- https://artifacthub.io/packages/kubewarden/hostpaths-psp/hostpaths-psp
- https://artifacthub.io/packages/kubewarden/ingress-policy/ingress-policy
- https://artifacthub.io/packages/kubewarden/pod-privileged-policy/pod-privileged-policy
- https://artifacthub.io/packages/kubewarden/pod-runtime/pod-runtime
- https://artifacthub.io/packages/kubewarden/readonly-root-filesystem-psp/readonly-root-filesystem-psp
- https://artifacthub.io/packages/kubewarden/safe-annotations/safe-annotations
- https://artifacthub.io/packages/kubewarden/safe-labels/safe-labels
- https://artifacthub.io/packages/kubewarden/seccomp-psp/seccomp-psp
- https://artifacthub.io/packages/kubewarden/selinux-psp/selinux-psp
- https://artifacthub.io/packages/kubewarden/sysctl-psp/sysctl-psp
- https://artifacthub.io/packages/kubewarden/trusted-repos/trusted-repos
- https://artifacthub.io/packages/kubewarden/user-group-psp/user-group-psp
- https://artifacthub.io/packages/kubewarden/volumes-psp/volumes-psp

Essentially, [everything published under the org=kubewarden](https://artifacthub.io/packages/search?org=kubewarden&sort=relevance&page=1).

I was thinking, maybe it is preferable to have 1 issue for marking all of them as official. If instead it is preferred to have 1 issue per ArtifactHub package, I'm happy opening them.

I would also welcome the feature proposed in https://github.com/artifacthub/hub/issues/1258.

Please tell me if I can be of more help.
Thanks in advance :sweat_smile: .

**Comment by tegioz** [comment]
Hi @viccuad 👋

All repositories published by Kubewarden have just been marked as official!

Please note that it's possible that eventually a package published by Kubewarden may not be considered official in some cases (for more information about this you can see [this comment](https://github.com/artifacthub/hub/issues/2328#issuecomment-1251172226) in a related issue). I've gone through your packages and I don't think this is a problem at the moment though. We are trying to improve the official definition and make its intent more clear, but it's tricky to get it right for all cases so the more eyes and opinions we've on it, the better 😅

Thanks!
