### ISSUE TITLE
[OFFICIAL] athens-charts/athens-proxy

### ISSUE THREAD

**Issue by DrPsychick** [artifacthub/hub#2874]
- **Repository name** *(in `artifacthub.io`)*: https://artifacthub.io/packages/helm/athens-charts/athens-proxy
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://github.com/gomods/athens-charts
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/gomods/athens-charts
- **Other relevant URLs:** https://github.com/gomods/athens

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!
