### ISSUE TITLE
[OFFICIAL] werf

### ISSUE THREAD

**Issue by alexey-igrychev** [artifacthub/hub#2875]
- **Repository name** *(in `artifacthub.io`)*: werf
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://werf.io/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** sandbox
- **Source code URL** *(if available)*: https://github.com/werf/werf
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Hi, @alexey-igrychev! 

Could you please share the Artifact Hub link of your repository? I can't find it.

**Comment by alexey-igrychev** [comment]
https://artifacthub.io/packages/container/werf/werf

p.s. it was not listed due to lack of required metadata 🙏🏼.

**Comment by cynthia-sg** [comment]
Done!

**Comment by alexey-igrychev** [comment]
❤️
