### ISSUE TITLE
[OFFICIAL] OpenFGA Official Helm Charts

### ISSUE THREAD

**Issue by jon-whit** [artifacthub/hub#2876]
- **Repository name** *(in `artifacthub.io`)*: openfga
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://openfga.dev, https://openfga.github.io/helm-charts
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** OpenFGA is a CNCF Sandbox project.
- **Source code URL** *(if available)*: https://github.com/openfga/openfga, https://github.com/openfga/helm-charts
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

https://openfga.dev
https://openfga.github.io/helm-charts
https://www.cncf.io/projects/openfga/
https://artifacthub.io/packages/helm/openfga/openfga

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
