### ISSUE TITLE
Ignored container image metadata

### ISSUE THREAD

**Issue by alexey-igrychev** [artifacthub/hub#2889]
**Describe the bug**

Following the guide (https://artifacthub.io/docs/topics/repositories/container-images/), I used extra labels to set the category and logo for my container image, but nothing changed (https://artifacthub.io/packages/container/werf/werf). 

**Expected behavior**

The package has an official logo and is added to the `integration-delivery` category.

**Additional context**

```
docker inspect registry.werf.io/werf/werf:latest --format "{{ .Config.Labels | json }}" | jq
{
  "io.artifacthub.package.category": "integration-delivery",
  "io.artifacthub.package.logo-url": "https://werf.io/assets/images/werf-logo.svg",
  "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/werf/werf/main/README.md",
  "org.opencontainers.image.created": "2023-03-14T14:47:27Z",
  "org.opencontainers.image.description": "Official image to run werf in containers",
  "org.opencontainers.image.source": "https://github.com/werf/werf/tree/main/scripts/werf-in-image",
  "org.opencontainers.image.url": "https://github.com/werf/werf/tree/main/scripts/werf-in-image"
}
```

**Comment by tegioz** [comment]
Hi @alexey-igrychev 👋

I've just tested your container image locally and both your logo and the category were processed fine.

<img width="1483" alt="werf" src="https://user-images.githubusercontent.com/1213902/225310524-543b3ee1-a092-4fc0-b447-c090ad6ce3d1.png">

All tags listed in your repository configuration are declared as *immutable*, and immutable tags are only processed once by AH as they are not supposed to change. Is it possible that that metadata wasn't on the image yet the first time Artifact Hub processed it? Being immutable, it won't be processed anymore and you won't see any changes reflected. I'd recommend to mark the `latest` tag as mutable, as it usually is likely to change over time.

**Comment by alexey-igrychev** [comment]
I see. Thank you @tegioz
