### ISSUE TITLE
"Reduce motion" accessibility support

### ISSUE THREAD

**Issue by abh** [artifacthub/hub#2900]
The new animated menu (For example the settings panel) that swipes into the screen from the right and swipes back out makes me very dizzy and feeling sick to the point that I can't safely click on anything on artifacthub anymore.

Please implement "reduce motion" support to disable these animations when the user has indicated a preference for less motion: https://webkit.org/blog/7551/responsive-design-for-motion/

**Comment by tegioz** [comment]
Thanks for reporting this @abh! We'll take care of it soon 👍

Do you remember any other animations that can be problematic? (Just the ones you can remember off the top of your head please)

**Comment by abh** [comment]
Thanks for looking into it, @tegioz!

A few others I noticed quickly clicking around:
- A similar animation when activating the menu in the top left corner.
- The "spinner" when loading search results (this isn't so bad for me now; but 5 years ago when my head injury was more recent it'd have been enough to put me off doing anything for a few hours so some people might really see it).

**Comment by tegioz** [comment]
Hi @abh

We've just deployed the changes described in #2921. Could you please give it a try when you have a chance? I'd suggest to clean up the cache before, to make sure you're using the latest web application version (to avoid causing you any unnecessary problems with older versions 🙂).

Thanks!

**Comment by tegioz** [comment]
Hi @abh 👋 

Will close this for now. Please feel free to reopen if something isn't still fine and we'll gladly look into it 🙂

**Comment by tegioz** [comment]
No worries, that's great to hear! ❤️
