### ISSUE TITLE
Signed Kubewarden policies are show as not signed.

### ISSUE THREAD

**Issue by jvanz** [artifacthub/hub#2922]
**Describe the bug**
Recently, the Kubewarden team released some policies signed with cosign. But artifacthub is not able to detect the signarture. Thus, the policies are show as not signed. However, we can verify the signatures using the cosign command:

```
cosign verify ghcr.io/kubewarden/policies/user-group-psp:v0.4.6 \
  --certificate-identity-regexp 'https://github.com/kubewarden/*' \
  --certificate-oidc-issuer https://token.actions.githubusercontent.com
```

**Expected behavior**
Mark the latest release of the Kubewarden policies as signed.

**Screenshot**
![Screenshot from 2023-03-22 15-17-29](https://user-images.githubusercontent.com/1514798/227000159-7d6c7361-f510-427d-af47-b89c0ed28fb1.png)

**Additional context**
You can see the command used to sign the policies [here](https://github.com/kubewarden/github-actions/blob/v3.0.4/policy-release/action.yaml).

**Comment by tegioz** [comment]
Hi @jvanz 👋 

I've just run a test locally for that repo and the policy's signature was detected.

<img width="1006" alt="kubewarden-test" src="https://user-images.githubusercontent.com/1213902/227135871-dcfcab0d-ac74-4974-a7f1-d20b2ab4131b.png">

I've forced the same package in `artifacthub.io` to be processed now and the [signature was detected as well](https://artifacthub.io/packages/kubewarden/user-group-psp/user-group-psp).

Is it possible that the containers were signed *after* AH indexed that package version?

Please note that AH won't process an existing package version again unless its digest changes. So ideally, by the time AH detects a new version in the git repo, the containers should already be signed.

**Comment by viccuad** [comment]
Hi @tegioz, (Kubewarden maintainer here too)

> Is it possible that the containers were signed after AH indexed that package version?

Yes, it's possible there was some minutes of difference. Our process is:
1. Repo HEAD with new upcoming version (eg: 0.5.0),  `artifacthub-pkg.yml`'s `version` field being also `0.5.0`.
1. Tag HEAD with `v0.5.0`. I suppose AH's webhook triggers here, and AH indexes the `artifacthub-pkg.yml` with the new version `0.5.0`. There wasn't time yet for GHA to build, sign, and push the release.
1. GHA triggers with the tag, builds, signs, and push the release. This is done for [example with this reusable workflow](https://github.com/kubewarden/github-actions/blob/main/.github/workflows/reusable-release-policy-rust.yml).


Question: does AH re-index packages after a while?
This problem is also happening for signed packages that have been released weeks prior, and I was hoping that AH would eventually re-index them and mark them as signed.

Example of another Kubewarden policy, released a while ago, that is marked also as unsigned:
https://artifacthub.io/packages/kubewarden/verify-image-signatures/verify-image-signatures
```
cosign verify ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.5 \
  --certificate-identity-regexp 'https://github.com/kubewarden/*' \
   --certificate-oidc-issuer https://token.actions.githubusercontent.com
```

**Comment by tegioz** [comment]
Hi @viccuad 👋

> Question: does AH re-index packages after a while?

No, it doesn't, unless we receive a signal they've changed. There are >178k releases at the moment and growing, we'd run into rate limiting problems soon 😅 And honestly, even if it did, I don't think it'd look nice to display a package unsigned for one day or week, when it's actually signed from the beginning. We have the digest at both the repository and package level to signal the need for processing, and we ping repos every 30 mins to detect those changes. AH trackers run twice an hour, at mins 0 and 30 approximately, so depending on when your workflows run, this will likely be a problem often.

Some possible workarounds off the top of my head (none super nice TBH, trying to think harder 💆🏻‍♂️):

- Use a different branch to publish on AH. The release workflow could cherry pick commits from the source branch at the end (when containers have already been signed).
- Update digest in AH metadata once the release workflow is done (this one is worse IMHO, as even it'd work, it'd require AH to always process packages twice, and it'd appear unsigned for at least 30 mins).

**Comment by tegioz** [comment]
> Honest question: did AH change behaviour here? I had the feeling that in the past it re-indexed packages with a cron.

I think you edited while I was replying, hope to not have missed anything 🙂 No, this hasn't changed, it's always worked like that (still a cron job though 😉). It's just that it depends on the timing like I mentioned in my previous comment.

**Comment by tegioz** [comment]
> 3. GHA triggers with the tag, builds, signs, and push the release.

Please note that this can be a problem beyond the signature detection: we may be publishing a package on AH that might actually not exist yet (for a few seconds, minutes, or longer if GHA is slow or down). It should be most of the time just a few seconds or minutes, but users could try to install the package following your instructions as soon as they receive the new release notification from AH.

**Comment by viccuad** [comment]
Thanks @tegioz!

Been thinking about workarounds, and the best one for our fits is using a different branch to publish to AH. WIll solve on our end that way.

This can be closed :).
