### ISSUE TITLE
[OFFICIAL] Kyverno Helm Chart

### ISSUE THREAD

**Issue by chipzoller** [artifacthub/hub#2929]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: Kyverno Helm Chart, Kyverno Policies
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://kyverno.github.io/kyverno/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Incubating
- **Source code URL** *(if available)*: https://github.com/kyverno/kyverno/tree/main/charts
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*: https://kyverno.io/

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by chipzoller** [comment]
Hi all 👋 I am a Kyverno maintainer and member of the Kyverno organization on Artifact Hub. I am requesting Official status designation for the following Helm charts published under the Kyverno project:

Kyverno Helm Chart (https://kyverno.github.io/kyverno/)

**Comment by cynthia-sg** [comment]
Done!

**Comment by tegioz** [comment]
Hi @chipzoller 

Thanks for reporting this @chipzoller! The CNCF icon doesn't seem to be rendered correctly on Firefox. We'll fix this shortly. We've just noticed it while looking into this because that badge was enabled yesterday at the same time than the official one. Actually, the tooltip message in your screenshot is correct (is says the package comes from a CNCF project) 😅
