### ISSUE TITLE
[OFFICIAL] Kyverno Policies

### ISSUE THREAD

**Issue by chipzoller** [artifacthub/hub#2946]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: Kyverno Policies
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://github.com/kyverno/policies
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Incubating
- **Source code URL** *(if available)*: https://github.com/kyverno/policies
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*: https://kyverno.io/policies

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [ ] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by chipzoller** [comment]
Related to #2929 except now we have enabled the official Kyverno Policies repository in Artifact Hub and would like to get it marked as official.

**Comment by tegioz** [comment]
Hi @chipzoller

Could you add a README file to the policies? It's a requirement for official packages as described above 🙂 It doesn't have to be something super long, maybe just a few lines that explain what the policy does. We usually expect a shorter description, so one option could be to use the description as the README content and add a shorter description.

Once that's ready, we can mark the policies available in the repo at the moment as official (not the repository itself). Please note that it's possible that eventually a Kyverno policy published by Kyverno may not be considered official in some cases (for more information about this you can see [this comment](https://github.com/artifacthub/hub/issues/2328#issuecomment-1251172226) in a related issue). For the current ones I don't think this is a problem at the moment though. We are trying to improve the official definition and make its intent more clear, but sometimes it's tricky to get it right for all cases 😅

Thanks!

**Comment by chipzoller** [comment]
Hi @tegioz, yes, you can see we have done so to these few test policies here: https://github.com/kyverno/policies/pull/547

After doing so, it's not picking up the changes though. Is this because it doesn't see any changes to those (or any) policies, or no new creation of metadata files?

**Comment by tegioz** [comment]
I see, cool. As soon as they are available on AH we can proceed 🙂

The reason why they are not picked up is because existing versions are only indexed again if their digest is updated. Ideally a published version should never change, but we provide this mechanism to help publishers fix minor issues without having to publish a new release. Just updating the digest field in the AH metadata files should do the trick.

**Comment by chipzoller** [comment]
@haoyuguo please create an issue for this in kyverno/policies and address in a new PR.

**Comment by guohaoyu110** [comment]
@chipzoller https://github.com/kyverno/policies/issues/549#issue-1652712353 working on it now.

**Comment by chipzoller** [comment]
@tegioz Complete.

**Comment by tegioz** [comment]
Done!

**Comment by chipzoller** [comment]
Based on the interesting [discussion thread over on Slack](https://cloud-native.slack.com/archives/C0103CTR3RB/p1680706759249349), it seems it would be best to walk this back.
