### ISSUE TITLE
[OFFICIAL] kubeservice-stack Helm Chart

### ISSUE THREAD

**Issue by dongjiang1989** [artifacthub/hub#2951]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: kubeservice-stack Helm Chart
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** [https://kubeservice-stack.github.io/kubservice-charts/](https://kubeservice-stack.github.io/kubservice-charts/)
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** incubating
- **Source code URL** *(if available)*:  [https://github.com/kubeservice-stack/kubservice-charts](https://github.com/kubeservice-stack/kubservice-charts)
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*
[https://stack.kubeservice.cn/](https://stack.kubeservice.cn/)

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @dongjiang1989 👋 

We've been looking carefully into this, but we're not sure if the official status applies to this case. The main reason is that `Kubeservice` doesn't seem to own the software/technology these packages primarily focus on, like PingMesh or eBPF. Any other organization could publish similar Prometheus exporters, and we need to be careful to not favor any particular option unless it's clear users would recognize it as being official.

Regarding the CNCF `incubating` status you claimed in the request, it looks like Kubeservice is not yet a CNCF project ([sandbox application](https://github.com/cncf/sandbox/issues/15)). So we cannot grant the CNCF status at the moment, but we'd be happy to enable that one once your application is approved 🙂
