### ISSUE TITLE
harbor-helm release of 1.11.1, 1.10.4, 1.9.6 are NOT sync-ed to artifacthub.io

### ISSUE THREAD

**Issue by zyyw** [artifacthub/hub#2953]
We recently noticed that the harbor-helm release of 1.11.1, 1.10.4 and 1.9.6 are not synced to artifacthub.io:
<img width="609" alt="Screen Shot 2023-04-04 at 18 29 58" src="https://user-images.githubusercontent.com/6709992/229765100-288c84ff-d700-4637-9a68-0b7bff6232fe.png">

But it does hold on this page: https://helm.goharbor.io/index.yaml

Could you please help us with this out-of-sync issue? Thanks

**Comment by tegioz** [comment]
Hi @zyyw 👋

It looks like the tracker run into some issues processing some of your packages (please see below). I would recommend you to [claim the ownership](https://artifacthub.io/docs/topics/repositories/#ownership-claim) of the Harbor repository on Artifact Hub and publish it under the Harbor organization. That way, when something goes wrong, you'll get notified and you'll be able to inspect the errors from the control panel in the UI and take action when needed 🙂

```
error preparing package: error loading chart (https://helm.goharbor.io/harbor-1.10.4.tgz): gzip: invalid header (package: harbor version: 1.10.4)+
error preparing package: error loading chart (https://helm.goharbor.io/harbor-1.11.1.tgz): gzip: invalid header (package: harbor version: 1.11.1)+
error preparing package: error loading chart (https://helm.goharbor.io/harbor-1.3.16.tgz): gzip: invalid header (package: harbor version: 1.3.16)+
error preparing package: error loading chart (https://helm.goharbor.io/harbor-1.3.17.tgz): gzip: invalid header (package: harbor version: 1.3.17)+
error preparing package: error loading chart (https://helm.goharbor.io/harbor-1.3.18.tgz): gzip: invalid header (package: harbor version: 1.3.18)+
error preparing package: error loading chart (https://helm.goharbor.io/harbor-1.9.6.tgz): gzip: invalid header (package: harbor version: 1.9.6)
```

**Comment by tegioz** [comment]
I've just done a quick check and this doesn't seem to be a common problem across many repositories: only 2 more Helm repositories in AH have this problem in their logs out of ~2.4k. Has something changed in your release process recently that may be causing this issue reading the chart's package files?

**Comment by zyyw** [comment]
Thanks @tegioz for the comments. I believe there is no process change regarding harbor-helm releases.

**Comment by tegioz** [comment]
Hi @zyyw

I think I know what's going on. The charts tgz files are fine, but when they are served by Netlify they are compressed using Brotli, when we expect the raw tgz. This extra compression requires some extra computing to *increase* the package size 4 bytes, so not really helpful in this case. We should probably restrict that on our end [by not accepting that encoding](https://github.com/artifacthub/hub/blob/61701344a7478190fdbece705e19a44d774d0d33/internal/tracker/source/helm/helm.go#L412), but we need to review this carefully to make sure it doesn't have any undesired side effect.

In the meantime, if you can disable compression on your end for those files, or disable Brotli, that would fix it temporarily. Please note that this is affecting all versions, not just the ones you listed. It's just that the previous ones were already processed when they were being served differently.

Will keep you posted!

**Comment by tegioz** [comment]
The missing versions are now available on Artifact Hub 🙂
