### ISSUE TITLE
[OFFICIAL] rego

### ISSUE THREAD

**Issue by drorIvry** [artifacthub/hub#2973]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: rego
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** : https://drorivry.github.io/rego/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** not yet
- **Source code URL** *(if available)*: https://github.com/drorivry/rego
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Hi @drorIvry,

could you please update this?

<img width="1230" alt="rego" src="https://user-images.githubusercontent.com/1440981/231264220-dd5e210d-5dd2-482e-bd0d-a4fd43478452.png">

**Comment by drorIvry** [comment]
@cynthia-sg Sorry about that 😓 fixed!

thank you!

**Comment by cynthia-sg** [comment]
Done!
