### ISSUE TITLE
Add documentation on how to embed artifacthub on a website

### ISSUE THREAD

**Issue by caniszczyk** [artifacthub/hub#2979]
e.g., https://keptn.sh/docs/integrations/

I think something should be linked from the README or just a simple section on the README how to do this

**Comment by tegioz** [comment]
Sure, we'll take care of this 👍

In the meantime, just in case some needs it right now, I'll leave here some screenshots that show how to generate the embedding code from the UI 🙂 (both for a single package or a group of them).

<img width="1528" alt="Screenshot 2023-04-13 at 16 12 56" src="https://user-images.githubusercontent.com/1213902/231787104-1f57a8b3-3819-41d2-bcd2-bdafccb04a04.png">

<img width="1528" alt="Screenshot 2023-04-13 at 16 13 03" src="https://user-images.githubusercontent.com/1213902/231786851-20de2910-13f6-4ecd-854a-44eddfc496b4.png">

<img width="1528" alt="Screenshot 2023-04-13 at 16 13 14" src="https://user-images.githubusercontent.com/1213902/231786867-1ab53b65-fe1b-4fbf-9197-e6b080f08c91.png">

**Comment by tegioz** [comment]
Deployed! https://artifacthub.io/docs/topics/embedding_artifacts/
