### ISSUE TITLE
[OFFICIAL] it-at-m

### ISSUE THREAD

**Issue by eidottermihi** [artifacthub/hub#2984]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: `it-at-m`
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://it-at-m.github.io/helm-charts/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: <https://github.com/it-at-m/helm-charts>
- **Other relevant URLs:**
  - ad2image source: https://github.com/it-at-m/ad2image
  - appswitcher-server source: https://github.com/it-at-m/appswitcher-server

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!

**Comment by eidottermihi** [comment]
@cynthia-sg we have a new official package in the repo, can this be marked as "official" as well?

https://artifacthub.io/packages/helm/it-at-m/ezldap

Source: https://github.com/it-at-m/ezLDAP

**Comment by cynthia-sg** [comment]
Done!

**Comment by eidottermihi** [comment]
Hi @cynthia-sg - we have another new official package in the repo:

https://artifacthub.io/packages/helm/it-at-m/wjh-rechner

Source: https://github.com/it-at-m/wjh-rechner

can this be marked as "official" as well?

**Comment by cynthia-sg** [comment]
Hi @eidottermihi ,

could you please translate the chart description to English? Once it's done we'd be happy to mark the chart as official :slightly_smiling_face:

**Comment by eidottermihi** [comment]
> Hi @eidottermihi ,
> 
> could you please translate the chart description to English? Once it's done we'd be happy to mark the chart as official 🙂

@cynthia-sg Done!

and just asking for possible future "official" addtions - is it OK if i keep pinging you in this issue or would you rather prefer new issues?

**Comment by cynthia-sg** [comment]
Done! 

> and just asking for possible future "official" addtions - is it OK if i keep pinging you in this issue or would you rather prefer new issues?

New issues would be better, thanks 🙂
