### ISSUE TITLE
icons do not show up in Hub despite successful tracking and present icon in Chart metadata

### ISSUE THREAD

**Issue by eidottermihi** [artifacthub/hub#2985]
**Describe the bug**

Similiar to #1873 the Charts in repo `it-at-m`(https://artifacthub.io/packages/search?repo=it-at-m&sort=relevance&page=1) do not have an icon in ArtifactHub, however the metadata includes an icon:

![grafik](https://user-images.githubusercontent.com/2780736/232519423-b16daef5-b8f4-4c2e-9563-5adf69c43dfa.png)

icon source: https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png
metadata:
- https://github.com/it-at-m/helm-charts/blob/gh-pages/index.yaml#L10
- https://github.com/it-at-m/helm-charts/blob/gh-pages/index.yaml#L28

I have gotten some emails concerning "errors while tracking repository it-at-m", with errors like:

```
error getting logo image https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png: image: unknown format (package: ad2image version: 1.0.4)

error getting logo image https://raw.githubusercontent.com/it-at-m/helm-charts/main/images/logo.png: image: unknown format (package: appswitcher-server version: 1.0.0)
```

but if i take a look at the latest tracking state in ArtifactHub it all seems to be OK:

![grafik](https://user-images.githubusercontent.com/2780736/232520130-82bf8128-c50a-412c-86bf-bcbc32933f80.png)

**To Reproduce**

-

**Expected behavior**

ArtifactHub should show the icon if tracking was successful.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 110.0 (64bit)

**Additional context**

**Comment by tegioz** [comment]
Hi @eidottermihi 👋 

The logo file doesn't seem to be using the PNG format like the extension suggests. Instead it uses WebP, which isn't supported unfortunately. You can also use SVG if you'd like.

```
% file logo.png                                                                                                       
logo.png: RIFF (little-endian) data, Web/P image
```

**Comment by eidottermihi** [comment]
doh, my bad. Sorry, should not have trusted provided files are what the extension suggests... Thanks for pointing that out, @tegioz !

**Comment by tegioz** [comment]
No worries! 👍
