### ISSUE TITLE
[OFFICIAL] piped

### ISSUE THREAD

**Issue by samip5** [artifacthub/hub#2986]
- **Repository name** *(in `artifacthub.io`)*: Piped-Kubernetes
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://github.com/TeamPiped/Piped-Kubernetes
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No.
- **Source code URL** *(if available)*: Chart repo: https://github.com/TeamPiped/Piped-Kubernetes, App source code is available under the TeamPiped org in Github.
- **Other relevant URLs:** https://github.com/TeamPiped/

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
