### ISSUE TITLE
[OFFICIAL] Kubeshark

### ISSUE THREAD

**Issue by alongir** [artifacthub/hub#3010]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name:** kubeshark-helm-charts
- **Official packages:** 
- **Project URL:** https:/github.com/kubeshark/kubeshark
- **Is the publisher a CNCF project?** No
- **Source code URL:** https:/github.com/kubeshark/kubeshark
- **Other relevant URLs:** https://kubeshark.co
**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ ] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [ ] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [ ] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!

**Comment by GeiserX** [comment]
Please @cynthia-sg could you add as well the following URL, which contains the source code of Kubeshark? It would be really helpful to have it too, even if it's located in the same repository as it's currently the source Helm chart:
https://github.com/kubeshark/kubeshark/
