### ISSUE TITLE
[OFFICIAL] Ortelius

### ISSUE THREAD

**Issue by sbtaylor15** [artifacthub/hub#3026]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **ortelius** *(in `artifacthub.io`)*: ...
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL: https://ortelius.io** ...
- **Is the publisher a CNCF project? (graduated, incubating or sandbox): No** ...
- **Source code URL: https://github.com/ortelius/ortelius** *(if available)*: ...
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Hi @sbtaylor15,

Could you extend a bit the package description please? Once that's ready, we can mark it as official.

Thanks!

**Comment by sbtaylor15** [comment]
@cynthia-sg - let me know if you need something longer or shorter.

Ortelius is a Supply Chain Evidence Catalog that tracks and aggregates the software composition, SBOMs, CVEs, and supply-chain evidence into a logical application for easy impact analysis and risk assessment.

**Comment by sbtaylor15** [comment]
Please use `Supply Chain Evidence Catalog` for the description.  

Also, we have tried to claim ownership using the artifacthub-repo.yml file but we can't select the repository.  Its greyed out.

![image](https://user-images.githubusercontent.com/14826572/236265326-189870d7-58eb-472f-be62-44fd81f5ae12.png)

**Comment by sbtaylor15** [comment]
We have updated the description and transferred the repo to the Ortelius org.  Anything else that we need to take care of?

**Comment by tegioz** [comment]
Everything looks great @sbtaylor15, thanks!

We've just granted the official status to the package, it should be visible in a few minutes 🙂
