### ISSUE TITLE
[OFFICIAL] vbouchaud/k8s-ldap-auth

### ISSUE THREAD

**Issue by vbouchaud** [artifacthub/hub#3034]
- **Repository name**: vbouchaud
- **Official packages**: k8s-ldap-auth
- **Project URL**: https://github.com/vbouchaud/k8s-ldap-auth/blob/master/README.md
- **Is the publisher a CNCF project?**: No
- **Source code URL**: https://github.com/vbouchaud/k8s-ldap-auth
- **Other relevant URLs**: Chart repository is hosted on github here https://github.com/vbouchaud/chartrepo

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
