### ISSUE TITLE
[OFFICIAL] argo

### ISSUE THREAD

**Issue by jmeridth** [artifacthub/hub#3052]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: argo
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://github.com/argoproj/argo-helm
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Yes, gradauted.  [Argo](https://www.cncf.io/projects/argo/)
- **Source code URL** *(if available)*:
  - [argo-cd](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd)
  - [argo-events](https://github.com/argoproj/argo-helm/tree/main/charts/argo-events)
  - [argo-rollouts](https://github.com/argoproj/argo-helm/tree/main/charts/argo-rollouts)
  - [argo-workflows](https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows)
  - [argocd-apps](https://github.com/argoproj/argo-helm/tree/main/charts/argocd-apps)
  - [argocd-image-updater](https://github.com/argoproj/argo-helm/tree/main/charts/argocd-image-updater)
- **Other relevant URLs:**
  - [My membership in argoproj GitHub organization](https://github.com/orgs/argoproj/people?query=jmeridth)
  - [artifacthub-repo.yml](https://github.com/argoproj/argo-helm/blob/gh-pages/artifacthub-repo.yml)

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Hi @jmeridth,

Could you add a README file to the [argo-lite](https://artifacthub.io/packages/helm/argo/argo-lite) chart please? The other packages have already been marked as official  🙂

Thanks.

**Comment by jmeridth** [comment]
@cynthia-sg thank you for marking the current ones as official. 😄 

We do not maintain that chart anymore.  We have one instance of it [here]([argo-lite-0.1.0.tgz](https://github.com/argoproj/argo-helm/blob/gh-pages/argo-lite-0.1.0.tgz)).  I'm going to look into removing the `argo-lite` package from the argo project on artifacthub.  Does deleting that file in our repository do it? Or is there a mechanism through the UI we can do that I'm missing.  Thank you for any assistance on this.

**Comment by tegioz** [comment]
Hi @jmeridth

Yes, when the chart is not available in the Helm repository Artifact Hub will delete it as well. You can also mark it as `deprecated` if you prefer (AH will mark it that way too), or even leave it there as it is, whatever works better for you.

**Comment by tegioz** [comment]
There is one more option that may suit better your needs: you can [ask AH to ignore it](https://github.com/artifacthub/hub/blob/80897251783447d398f2aa8aeb7ed9a5259d49f5/docs/metadata/artifacthub-repo.yml#L18-L21).

But like I said, it's not a problem to leave it there as it is (actually it'd be better that way as users may still use AH to inspect it). It was just that we couldn't mark that one as official without the README file.

Hope this helps 🙂

**Comment by jmeridth** [comment]
@tegioz done [here](https://github.com/argoproj/argo-helm/blob/gh-pages/artifacthub-repo.yml#L6-L7). Thank you.

**Comment by tegioz** [comment]
Awesome, thanks!

**Comment by tegioz** [comment]
BTW a bit off topic but I wanted to share with you [this](https://github.com/argoproj-labs/argo-workflows-catalog/issues/27) @jmeridth 😇

Thanks again!

**Comment by jmeridth** [comment]
@tegioz that is AWESOME.  I noticed that in the [README](https://github.com/artifacthub/hub/blob/80897251783447d398f2aa8aeb7ed9a5259d49f5/README.md?plain=1#L17) and was going to ask in CNCF slack.

Love everything you and @cynthia-sg and other contributors are doing.  Thank you.
