### ISSUE TITLE
[OFFICIAL] Meilisearch

### ISSUE THREAD

**Issue by alallema** [artifacthub/hub#3109]
### Request for official status,

Hello team! We applying to have the official status on your platform.
Thank you

- **Repository name** *(in `artifacthub.io`)*: Meilisearch
- **Official packages** *(leave empty if all packages in the repository are official)*: -
- **Project URL:** https://meilisearch.github.io/meilisearch-kubernetes
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/meilisearch/meilisearch
- **Other relevant URLs:** https://github.com/meilisearch/meilisearch-kubernetes

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ ] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [ ] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [ ] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
