### ISSUE TITLE
[OFFICIAL] argo-watcher

### ISSUE THREAD

**Issue by shini4i** [artifacthub/hub#3111]
Hello!

- **Repository name** *(in `artifacthub.io`)*: shini4i
- **Official packages** *(leave empty if all packages in the repository are official)*: argo-watcher
- **Project URL:** https://github.com/shini4i/argo-watcher
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: Same as the project URL above
- **Other relevant URLs:** None

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @shini4i 👋

I'm not sure if the official status applies to this case. IMHO for a package named `argo-watcher` to be marked as official, it should probably be owned and published by the [Argo Project](https://artifacthub.io/packages/search?org=argoproj). argo-watcher seems to be primarily focused on Argo CD, which is owned by a different organization.

Hope this makes sense 🙂

**Comment by shini4i** [comment]
Hi @tegioz

I see. In that case, the description of the `official` package seems a bit misleading.

`In Artifact Hub, the official status means that the publisher owns the software a package primarily focuses on` fully applies to this case IMO. 

For example, will a postgres-operator that is developed by developers that has nothing to do with an organization that owns the database itself be treated as an official package? It seems that it should, as it's a separate project.

But "no" means "no". No hard feelings. :)

**Comment by tegioz** [comment]
I agree it's not clear sometimes, and we've love to improve it further. But it's not easy to cover so many different use cases and artifacts kinds 😅

Regarding your postgres-operator example, we've tried to cover that particular case as an example if the definition actually (please see last sentence):

*In Artifact Hub, the official status means that the publisher owns the software a package primarily focuses on. If we consider the example of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the official status the publisher should be the owner of the Consul software (HashiCorp in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by Google to be marked as official.* **In the case of a MySQL operator, only one published by MySQL/Oracle would be considered official.**

> For example, will a postgres-operator that is developed by developers that has nothing to do with an organization that owns the database itself be treated as an official package? It seems that it should, as it's a separate project.

The problem going that route is that it'd be possible to have multiple official versions of the same "thing", making it harder for users to make a decision about what package to choose among multiple options.

Thanks for understanding! 🙂
