### ISSUE TITLE
Search relevance has some issues

### ISSUE THREAD

**Issue by HoustonPutman** [artifacthub/hub#3122]
**Describe the bug**
When searching for "Solr", one would expect the [official Solr helm chart](https://artifacthub.io/packages/helm/apache-solr/solr) to be sorted first by relevance. (and the [official Solr Operator helm chart](https://artifacthub.io/packages/helm/apache-solr/solr-operator) to be ranked close to the top)

- It's name is an exact match for the query string
- It has the most stars out of all "Solr" charts
- It has the "official" flag
- It's organization ("Apache Solr") contains the query "Solr"

However, the Solr Operator helm chart ranks 8/12 and the Solr helm chart ranks 9/12.

**To Reproduce**
1. Go to https://artifacthub.io/packages/search?ts_query_web=solr&sort=relevance&page=1

**Expected behavior**
I would expect that Apache Solr's Solr and Solr Operator chart would be highly ranked. With Solr being ranked first, and ideally the Solr Operator being ranked close to the top, although I understand it's less of a match. If the Solr Operator was ranked first, that would be fine as well.

**Comment by tegioz** [comment]
Thanks for reporting this @HoustonPutman!

We've applied some adjustments (#3125) and the official Apache Solr's chart is now ranked first. The Solr Operator, however, appears after all the other exact `solr` matches (but it appears the first one after them 🙂). And if you search for `solr operator` it appears first.
