### ISSUE TITLE
[OFFICIAL] Rook

### ISSUE THREAD

**Issue by galexrt** [artifacthub/hub#3123]
- **Repository name** *(in `artifacthub.io`)*: `rook`
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://rook.io/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Yes, graduated.
- **Source code URL** *(if available)*: https://github.com/rook/rook
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

/cc @travisn @jbw976

**Comment by cynthia-sg** [comment]
Done!
