### ISSUE TITLE
[OFFICIAL] oxyno-zeta

### ISSUE THREAD

**Issue by oxyno-zeta** [artifacthub/hub#3127]
# Request for official status

Hello team! 
I'm applying for the Official status on my helm registry and my projects.
Thank you & have a great day!

- **Repository name** *(in `artifacthub.io`)*: oxyno-zeta
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://github.com/oxyno-zeta/helm-charts-v2/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/oxyno-zeta/helm-charts-v2/
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*
  - https://github.com/oxyno-zeta/s3-proxy
  - https://oxyno-zeta.github.io/s3-proxy/
  - https://github.com/oxyno-zeta/kubernetes-tagger
  - https://github.com/oxyno-zeta/prometheus-cachethq

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @oxyno-zeta 👋

I'm not sure if the official status applies to this case. For a package named S3 proxy to be marked as official, it should probably be published by AWS. The same applies to the Cachet package, or the Kubernetes tagger.

Please note that ideally there should be a single official option for the same "thing" as, in the end, the goal of that status is to help users picking among multiple choices. In this case there are [more s3 proxy packages available in Artifact Hub](https://artifacthub.io/packages/search?ts_query_web=s3+proxy) and, IMHO, neither of the current options should have that status over the other.

Hope this makes sense 🙂

**Comment by oxyno-zeta** [comment]
Hello,

Oh I see. No problem, I can understand your position :) .
I will close this then.

Thanks for your time !

Have a nice day !

Oxyno-zeta

**Comment by tegioz** [comment]
Thank you for understanding! And have a great day you too! 🙂
