### ISSUE TITLE
[OFFICIAL] Epinio

### ISSUE THREAD

**Issue by enrichman** [artifacthub/hub#3144]
- **Repository name** *(in `artifacthub.io`)*: epinio
- **Official packages**: 
- **Project URL:** https://github.com/epinio/epinio
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/epinio/epinio
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*
   - https://github.com/epinio/helm-charts

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
`epinio` chart has been marked as official
