### ISSUE TITLE
Repository details are invisible in dark mode

### ISSUE THREAD

**Issue by NotMyFault** [artifacthub/hub#3156]
**Describe the bug**
The repository details use the same font color like the background in dark mode.

**To Reproduce**
Go to your profile and select "Repositories"

**Expected behavior**
The repository details shouldn't be the same color as the background. It works fine in light mode.

**Screenshots**
![Screenshot 2023-06-30 at 22 02 01](https://github.com/artifacthub/hub/assets/13383509/eb457a9c-cd4f-4488-b24d-214dee07373b)

**Comment by tegioz** [comment]
Thanks for reporting this @NotMyFault! I think it's a regression we introduced in #3145. We'll take care of it very soon! (It seems to be affecting some other parts of the UI as well)
