### ISSUE TITLE
[OFFICIAL] (Inspektor Gadget) gadget

### ISSUE THREAD

**Issue by mqasimsarfraz** [artifacthub/hub#3170]
- **Repository name** *(in `artifacthub.io`)*: gadget (https://artifacthub.io/packages/helm/gadget/gadget)
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://github.com/inspektor-gadget/inspektor-gadget
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** [sandbox](https://www.cncf.io/projects/inspektor-gadget/)
- **Source code URL** *(if available)*:  https://github.com/inspektor-gadget/inspektor-gadget
- **Other relevant URLs:** https://www.inspektor-gadget.io

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
