### ISSUE TITLE
[OFFICIAL] twingate/connector

### ISSUE THREAD

**Issue by ekampf** [artifacthub/hub#3213]
- **Repository name** *(in `artifacthub.io`)*: https://artifacthub.io/packages/helm/connector/connector
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://www.twingate.com
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/Twingate/helm-charts

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
