### ISSUE TITLE
[OFFICIAL] vmonitor-platform

### ISSUE THREAD

**Issue by tantm3** [artifacthub/hub#3231]
- **Repository name** *(in `artifacthub.io`)*: vmonitor-platform
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://github.com/vngcloud/helm-charts-vmonitor
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*:  https://github.com/vngcloud/vmonitor-metrics-agent/archive/refs/tags/1.26.0-2.0.1.tar.gz
- **Other relevant URLs:** https://github.com/influxdata/telegraf

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

Thanks for your help!

**Comment by cynthia-sg** [comment]
Hi @tantm3 ,

Could you add a README file to the chart please?

Thanks.

**Comment by tantm3** [comment]
Hi @cynthia-sg,

I have trouble when adding the README file to the chart.
I already created a README file here: https://github.com/vngcloud/helm-charts-vmonitor/blob/main/charts/vmonitor-metric-agent/README.md, but I have no idea why the artifact hub UI is unable to get the README file.

![image](https://github.com/artifacthub/hub/assets/112939454/f5874c80-4e3a-46ea-b3f9-d597dacd7173)


I follow the documentation here: https://helm.sh/docs/howto/chart_releaser_action/.
I don't know what is missing here.

**Comment by tantm3** [comment]
Hi @cynthia-sg,

The README file is updated. It turns out that I need to wait for the need check period from Artifact Hub.
Could you please check it again?

**Comment by cynthia-sg** [comment]
Done!
