### ISSUE TITLE
Support setting sensible credentials via environment variables

### ISSUE THREAD

**Issue by tibuntu** [artifacthub/hub#3252]
**Is your feature request related to a problem? Please describe.**
We started to onboard ArtifactHub using the official Helm-Chart. However, in the middle of the onboarding we noticed, that several credentials, e.g.: the DB password, or the OIDC client secret, can only be set in plaintext in the Helm-Chart.

**Describe the solution you'd like**
It would be awesome if the Chart / Artifachub would support setting them via environment variables. The chart could contain another functionality to consume environment variables from another secret.

**Describe alternatives you've considered**
Our possible solution for this will result in overwriting the existing secret which also contains non-sensitive information as it holds the whole artifacthub configuration. But this introduces issues when upgrading the chart to new releases, because one would always need to check if the secret / the config is still valid.

**Comment by tegioz** [comment]
Will close this issue for now, please feel free to reopen if needed 🙂

**Comment by dlahn** [comment]
Can this be re-opened? It would be good if these things could be set from secrets or environment. The above solution isn't really feasible.

**Comment by tegioz** [comment]
Hi @dlahn 👋

I misunderstood @tibuntu's original request, my bad 😅

Have you considered using [helm-secrets](https://github.com/jkroepke/helm-secrets)?
