### ISSUE TITLE
[OFFICIAL] epmdedp

### ISSUE THREAD

**Issue by SergK** [artifacthub/hub#3269]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: epmdedp
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://epam.github.io/edp-helm-charts/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** none
- **Source code URL** *(if available)*: https://github.com/epam/edp-helm-charts
- **Other relevant URLs:** https://epam.github.io/edp-install/

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @SergK 👋

We've just marked the [edp-install package](https://artifacthub.io/packages/helm/epmdedp/edp-install) as official.

Unfortunately, we can't apply it for all the packages in the repository. In cases like the Argo CD operator, Headlamp, Gerrit, Sonar, Tekton, Keycloak, Jenkins, Nexus, etc, the package would have to be published by the company or organization which owns that software to be marked as official. Hope this makes sense 🙂

Just in case it helps, you can create an organization and transfer the repository to it from the control panel in the UI if you'd like.
