### ISSUE TITLE
scanner error

### ISSUE THREAD

**Issue by christiancadieux** [artifacthub/hub#3276]
**Describe the bug**
I see this error in the scanner log

Also, I get this error in the scanner log. 
In my case, the pods do not have access to the internet. Not sure if that's the reason that the scanner fails.
the repos that artifacthub need to scan are all in the internal network of the company.
not sure if failed access to artifacthub.github.io/helm-charts/index.yaml is important.
Is it possible for artifacthub to use a proxy for access to artifacthub.github.io

```
2023-08-21 21:40:01.077554: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
{"level":"info","cmd":"tracker","pid":1,"time":"2023-08-21T21:40:01Z","message":"tracker started"}
{"level":"info","cmd":"tracker","svc":"authorizer","time":"2023-08-21T21:40:01Z","message":"preparing policies queries"}
2023-08-21 21:40:01.397360: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: ./ml/category/model
2023-08-21 21:40:01.400576: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2023-08-21 21:40:01.400610: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: ./ml/category/model
2023-08-21 21:40:01.400685: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-21 21:40:01.442902: I tensorflow/cc/saved_model/loader.cc:229] Restoring SavedModel bundle.
2023-08-21 21:40:01.483987: I tensorflow/cc/saved_model/loader.cc:213] Running initialization op on SavedModel bundle at path: ./ml/category/model
2023-08-21 21:40:01.543748: I tensorflow/cc/saved_model/loader.cc:305] SavedModel load for tags { serve }; Status: success: OK. Took 146396 microseconds.
{"level":"error","cmd":"tracker","repo":"artifact-hub","kind":"helm","error":"error getting repository remote digest: Get \"https://artifacthub.github.io/helm-charts/index.yaml\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","time":"2023-08-21T21:40:11Z"}
{"level":"info","cmd":"tracker","time":"2023-08-21T21:40:11Z","message":"tracker finished"}

```

**To Reproduce**

**Expected behavior**
Does artifactHub support running off the internet.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [ chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tegioz** [comment]
Hi @christiancadieux 👋

Yes, that's the problem. The tracker component needs to be able to connect to the repositories registered. But you don't really need to have that repository registered in your Artifact Hub instance, so I would suggest to remove it and leave only the ones in your internal network.

Hope this helps 🙂

**Comment by christiancadieux** [comment]
thanks for the info.
a few questions: 
- how would I remove this artifacthub.github.io/ from the list of registered instances.
- Also I have maybe related problem with trivy:
    github.com/aquasecurity/trivy/pkg/commands/operation.DownloadDB
        /home/runner/work/trivy/trivy/pkg/commands/operation/operation.go:119
  - OCI artifact error:
    github.com/aquasecurity/trivy/pkg/db.(*Client).Download
        /home/runner/work/trivy/trivy/pkg/db/db.go:155
  - OCI artifact error:
    github.com/aquasecurity/trivy/pkg/db.(*Client).initOCIArtifact
        /home/runner/work/trivy/trivy/pkg/db/db.go:205
  - OCI repository error:
    github.com/aquasecurity/trivy/pkg/oci.NewArtifact
        /home/runner/work/trivy/trivy/pkg/oci/artifact.go:70
  - Get "https://ghcr.io/v2/": dial tcp 140.82.112.34:443: i/o timeout


So first, what is trivy , also does it need to reach ghcr.io/v2/ - or can I setup a proxy for it. 

thanks

**Comment by tegioz** [comment]
No worries!

> * how would I remove this artifacthub.github.io/ from the list of registered instances.

You can remove it from the `repository` table in the database. If you added it from the control panel in the UI, you can remove it from there as well.

> So first, what is trivy , also does it need to reach ghcr.io/v2/ - or can I setup a proxy for it.

[Trivy](https://aquasecurity.github.io/trivy/v0.44/) is a security scanner that Artifact Hub uses to generate security reports like [this one](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=security-report). Security reports are the result of scanning the containers images in the package.

In the same way the `tracker` needed to communicate with the source repository to fetch the content, the `scanner` component needs to be able to talk to the registry where the images are hosted. There is no way in AH to setup a proxy for the tracker or scanner at the moment.

Will close this one for now, feel free to reopen if needed :)

**Comment by christiancadieux** [comment]
ok - great - I will just turn-off that trivy daemonset.
thanks again

**Comment by tegioz** [comment]
Awesome 👍

I would suggest disabling the scanner as well (`scanner.enabled` in the chart). Otherwise it'll keep trying to contact the Trivy deployment to scan images.
