### ISSUE TITLE
GLPI Artifacthub Chart Problem

### ISSUE THREAD

**Issue by mohitthakur3** [artifacthub/hub#3293]
Hey Team,

I am trying to deploy the https://artifacthub.io/packages/helm/glpi-chart/glpi?modal=install on my EKS Cluster. But looks like there is some problem with the chart. I tried with multiple ways, but it didn't work. After installing the chart, glpi pod always crashing. And when I tried to check with kubectl describe command. It is not providing the much information related to the issue. 

Chart Reference Link:-  https://artifacthub.io/packages/helm/glpi-chart/glpi?modal=install
<img width="821" alt="glpi" src="https://github.com/artifacthub/hub/assets/99646653/e3f066a1-ff22-491c-824f-970b23743887">

I have attached the error screenshot for reference.

Thanks.

**Comment by tegioz** [comment]
Hi @mohitthakur3 👋

For issues with the content listed on artifacthub.io it's best to contact the particular project directly. In the links section of the right panel in the package view you usually may find some links that can point you to the project's repository or the maintainers emails. Unfortunately in this case that information wasn't provided by the publisher, so you may need to try to find the source repository searching on the Internet.

Hope this helps 🙂
