### ISSUE TITLE
Add possibility to add some custom labels for ingress

### ISSUE THREAD

**Issue by pmeyer34** [artifacthub/hub#3294]
**Is your feature request related to a problem? Please describe.**
I'm deploying on prem in an openshift cluster. I'm using [ingress sharding](https://docs.openshift.com/container-platform/4.12/networking/ingress-sharding.html#nw-ingress-sharding-route-labels_ingress-sharding). In this use-case, the ingress needs to have some specific labels to be selected by the ingress controller.

**Describe the solution you'd like**
Add an optionnal hub.ingress.extraLabels key in values.yaml, and condionnal addition in the ingress template file.

**Describe alternatives you've considered**
Patching resource after creation.

**Additional context**
I can submit a PR to implement it if you approve the Feature Request.

**Comment by tegioz** [comment]
Hi @pmeyer34 👋

Adding an optional `hub.ingress.extraLabels` entry sounds good, and we'd gladly accept a PR 🙂

**Comment by pmeyer34** [comment]
hi, 
done :) #3295

**Comment by tegioz** [comment]
Closed by #3295
