### ISSUE TITLE
Mismatch Between API Documentation and Actual JSON Response for /packages/helm/{repoName}/{packageName} Endpoint

### ISSUE THREAD

**Issue by KrishnaPhalgun28** [artifacthub/hub#3296]
**Describe the bug**
The API documentation for the /packages/helm/{repoName}/{packageName} endpoint specifies that the data.dependencies field should be an object. However, the actual JSON response returns data.dependencies as an array of objects. A similar issue occurs with the containers_images field.

**To Reproduce**
1. Run the following cURL command:
`curl -X 'GET' \
  'https://artifacthub.io/api/v1/packages/helm/bitnami/mysql' \
  -H 'accept: application/json'
`
2. Examine the JSON response.
3. Notice that the data.dependencies field is an array of objects, not an object as specified in the API documentation.
4. Similarly, observe that the containers_images field is also an array of objects.

**Expected behavior**
Based on the API documentation, I expected the data.dependencies field to be an object and not an array of objects. The same expectation applies to the containers_images field.

**Screenshots**
<img width="748" alt="Screenshot 2023-08-27 at 10 05 32 PM" src="https://github.com/artifacthub/hub/assets/69800896/04789952-59af-4653-a3b2-45f54987e94a">
<img width="1086" alt="Screenshot 2023-08-27 at 10 06 28 PM" src="https://github.com/artifacthub/hub/assets/69800896/ecf721a1-2786-4c15-8bdb-0bed3482533e">
<img width="776" alt="Screenshot 2023-08-27 at 10 06 01 PM" src="https://github.com/artifacthub/hub/assets/69800896/66694f75-4ca5-4c4d-b98a-fd63e17d427f">

**Additional context**
I am using [oapi-codegen](https://github.com/deepmap/oapi-codegen) to generate client code to interact with the API.  The code fails during unmarshalling due to the discrepancy between the API documentation and the actual JSON response.

**Comment by tegioz** [comment]
Hi @KrishnaPhalgun28 👋 

Thanks for reporting this, we'll update the documentation soon 👍

**Comment by unavailable10** [comment]
curl -X 'GET' \   'https://artifacthub.io/api/v1/packages/helm/bitnami/mysql' \   -H 'accept: application/json'

**Comment by KrishnaPhalgun28** [comment]
> curl -X 'GET' \ 'https://artifacthub.io/api/v1/packages/helm/bitnami/mysql' \ -H 'accept: application/json'

Need any help?
