### ISSUE TITLE
Add option for custom labels for workloads

### ISSUE THREAD

**Issue by aku-oanda** [artifacthub/hub#3328]
**Is your feature request related to a problem? Please describe.**
I am deploying Artifact Hub in a Kubernetes cluster with monitoring/policy services which require certain custom labels to exist on all workloads running in the cluster. The helm chart currently doesn't allow for custom labels.

**Describe the solution you'd like**
Optional values in the values.yaml file which would add those labels to the various workloads that are deployed as part of the Helm chart (hub, trivvy, cronjobs, etc.)

This is something I've seen in other helm charts, such as the one for chartmuseum: https://github.com/chartmuseum/charts/blob/6d703ecb482ce0c87901facd2aa49c6664e2271e/src/chartmuseum/templates/deployment.yaml

**Describe alternatives you've considered**
I considered patching the labels in after deployment, but we have a policy engine which flags creation of resources without these labels, and that makes this alternative cumbersome to implement.

**Additional context**
This is somewhat related to a PR to add custom labels for the ingress: https://github.com/artifacthub/hub/pull/3295

I'm also willing to try putting up a PR which adds these custom workload labels if this feature request is welcome.

**Comment by tegioz** [comment]
Hi @aku-oanda 👋

Adding support for custom labels sounds good, we'd gladly accept a PR for this 🙂

**Comment by tegioz** [comment]
Closed by #3331

**Comment by tegioz** [comment]
Thanks @aku-oanda! 🙂

**Comment by aku-oanda** [comment]
Thanks for the quick reviews @tegioz!

I have a question: do you have an idea of when this version of the chart is going to be available for download from official channels? Is this something that will happen when the next version of the app gets released?

**Comment by tegioz** [comment]
No worries!

It usually takes some time (a few weeks sometimes), but we are preparing a new release today (1.16.0) and your changes will be part of it 😉
