### ISSUE TITLE
[ABUSE-REPORT] Repository or package name

### ISSUE THREAD

**Issue by Manikantai** [artifacthub/hub#3330]
while deploying argo workflows throgh bitnami helmcahrts  chart version 5.4.0 my argo job pods are getting deleted after sometime  is there any ttl needs to update in values file ?

**Comment by tegioz** [comment]
Hi @Manikantai 👋

For issues with the content listed on artifacthub.io it's best to contact the particular project directly. In the links section of the right panel in the package view you usually may find some links that can point you to the project's repository or the maintainers emails.

Hope this helps 🙂
