### ISSUE TITLE
Webhook bug report

### ISSUE THREAD

**Issue by m-mohamadi** [artifacthub/hub#3348]
**Issue with Webhook on ArtifactHub Website**

I attempted to send a notification via the webhook on the ArtifactHub website, but I encountered an issue
I have created a specific Microsoft Teams channel to receive notifications from ArtifactHub
I have tested the webhook via curl command and it works perfectly.

I'm going to send notification via webhook of artifacthub but i faced a issue
I have created the specific Microsoft Teams channel to get the notification from artifacthub

in the following i send some screenshot related to issue
![Screenshot from 2023-09-14 11-01-46](https://github.com/artifacthub/hub/assets/106485578/e5b7125a-1899-4966-9cf8-72194bc1f09d)

![1](https://github.com/artifacthub/hub/assets/106485578/ffc1d254-7d3d-43cd-9f3c-856101978155)
![Screenshot from 2023-09-14 11-01-14](https://github.com/artifacthub/hub/assets/106485578/78cd87f7-b1fb-4ca8-8613-409eb9a68508)

In the following screenshot, you can see that I have sent a notification via a curl command, and it worked perfectly
![2](https://github.com/artifacthub/hub/assets/106485578/2964cfd1-d24a-47be-9c09-2d9811ee54c2)

**Comment by tegioz** [comment]
Hi @m-mohamadi 👋

The error you are receiving comes from the service you defined (when the test receives an error from the webhook endpoint, it forwards it to you that way). It looks like your service doesn't like the request's input. Maybe the problem is the surrounding double quotes you used, I would try without them.

**Comment by m-mohamadi** [comment]
> Hi @m-mohamadi 👋
> 
> The error you are receiving comes from the service you defined (when the test receives an error from the webhook endpoint, it forwards it to you that way). It looks like your service doesn't like the request's input. Maybe the problem is the surrounding double quotes you used, I would try without them.

Hi @tegioz,

Thank you for follow my issue.
I have tested with the default payload, and I encountered the same issue as before. In the following, you can see some screenshots.
![Screenshot from 2023-09-14 13-10-33](https://github.com/artifacthub/hub/assets/106485578/722edda2-f36a-4209-8cc9-60e7cb2914a1)
![Screenshot from 2023-09-14 13-10-46](https://github.com/artifacthub/hub/assets/106485578/1ae50d64-86fc-4afc-9b10-b4ac693132b5)

**Comment by tegioz** [comment]
Hi @m-mohamadi 

No worries, happy to help 🙂

It makes sense that you get the same error when using the default payload. In that case, the Microsoft Teams endpoint you set up isn't expecting that payload, so it complains saying that the request is not valid.

Can you give it a try just leaving in the payload the text below?

```json
{"title": "release - security alert", "text": "testing webhook manually via artifacthub"}
```

It's the same you shared initially but without the surrounding double quotes. Don't forget to set the content type to `application/json` as you did in your curl request.

**Comment by m-mohamadi** [comment]
> Hi @m-mohamadi
> 
> No worries, happy to help 🙂
> 
> It makes sense that you get the same error when using the default payload. In that case, the Microsoft Teams endpoint you set up isn't expecting that payload, so it complains saying that the request is not valid.
> 
> Can you give it a try just leaving in the payload the text below?
> 
> ```json
> {"title": "release - security alert", "text": "testing webhook manually via artifacthub"}
> ```
> 
> It's the same you shared initially but without the surrounding double quotes. Don't forget to set the content type to `application/json` as you did in your curl request.

@tegioz 
I tested it with this payload, and it worked perfectly. Thank you so much!

**Comment by m-mohamadi** [comment]
> Hi @m-mohamadi
> 
> No worries, happy to help 🙂
> 
> It makes sense that you get the same error when using the default payload. In that case, the Microsoft Teams endpoint you set up isn't expecting that payload, so it complains saying that the request is not valid.
> 
> Can you give it a try just leaving in the payload the text below?
> 
> ```json
> {"title": "release - security alert", "text": "testing webhook manually via artifacthub"}
> ```
> 
> It's the same you shared initially but without the surrounding double quotes. Don't forget to set the content type to `application/json` as you did in your curl request.

**Comment by tegioz** [comment]
Awesome! 🎉
