### ISSUE TITLE
Support new artifact kind for KCL

### ISSUE THREAD

**Issue by zong-zhe** [artifacthub/hub#3350]
Hello @tegioz , thanks for your help in https://github.com/artifacthub/hub/discussions/3257. 

KCL has been approved and has become a CNCF sandbox project in https://github.com/cncf/sandbox/issues/48. 

Therefore, we hope that AH can support KCL's artifacts kind. Additionally, we think that AH is well-designed, So I want to talk about if it's possible to use AH as a market or registry for KCL's artifacts, similar to crate.io for Rust language or https://pkg.go.dev/ for Go language.

Let me show more detailed information about KCL artifacts and the features AH might support that we can discuss together:

- The artifact that KCL needs to be managed is currently called a `KCL package`. Since the language provides a plugin mechanism, we may add other kinds of KCL artifacts in the future, such as `KCL plugin`, but for now, just `KCL package` is enough.

- Currently, KCL manages packages through its own package manager [kpm](https://github.com/kcl-lang/kpm). And, we need a market or registry for KCL packages. Therefore, we hope to use AH as this market, and kpm can interact with AH through its APIs, just like the relationship between helm and AH.

- The KCL package is a `*.tar`. The contents of one KCL package mainly include all the source code files (*.k) and configuration files of package `kcl.mod` and `kcl.mod.lock`. These two files is similar to `go.mod` and `go.sum` in Go language projects. `kcl.mod` describes some related configurations of the current KCL package, and `kcl.mod.lock` fixes the versions of third-party dependencies. 

- A `README.md` as the kcl package homepage : This is a markdown file located in the root directory of the KCL package. If we use AH, we hope that the homepage of each KCL package can display this `README.md`. Additionally, a KCL package may contain multiple markdown files in the sub directories, and these markdown files may have interconnections.

Lastly, I have a small question:

- Is the email address of an artifacthub account unchangeable ? Because the official email address of KCL may be changed  in the future.

**Comment by tegioz** [comment]
Hi @zong-zhe 👋

Congratulations! 🎉

I'm in the middle of something right now but I'll get back to you very soon so that we can discuss how to proceed 🙂

**Comment by zong-zhe** [comment]
> Hi @zong-zhe 👋
> 
> Congratulations! 🎉
> 
> I'm in the middle of something right now but I'll get back to you very soon so that we can discuss how to proceed 🙂

No problem @tegioz 😄 , take your time. I'll be here when you're ready.

**Comment by zong-zhe** [comment]
Hi, @tegioz ! 🙂
Based on the information you provided, I have attempted to design a workflow for collaboration between KPM and AH. Please take a look and let me know if there are any errors or areas that need improvement.

Firstly, we would like to utilize AH as a marketplace for `KCL package`. We aim for KCL users to be able to discover or publish their packages through AH.

Therefore, there are some points that need attention.

- Users can use "kpm push" to publish KCL packages to AH, and they will be able to see detailed information about the KCL packages in AH.
- AH retrieves and displays detailed information about the package through its metadata in artifacthub-pkg.yml and README.md.
- We will use an account to create a KCL official organization to maintain some KCL packages.


Therefore, here's what I need to do:
* The package uploaded by KPM must contain artifacthub-pkg.yml and README.md files in the root directory of each KCL package. I created a demo using our existing KCL k8s model to show this directory structure [kcl_k8s_demo](https://github.com/zong-zhe/kcl_k8s)
* KPM uses the API provided by AH to upload the package containing the artifacthub-pkg.yml and README.md files to AH.
* Finally, users will be able to see the packages pushed by kpm on AH, along with some detailed information displayed in the artifacthub-pkg.yml and README.md.

There are a question：
- I see that artifacthub-pkg.yml contains custom fields such as `annotations`, can the content of `annotations` also be displayed on the AH page? Because KCL packages are interdependent, I see that there is a `releated packages` section in the page of helm chart, and I also want to try to show the dependencies between KCL packages using the `annotations`.

**Comment by zong-zhe** [comment]
Hi, @tegioz ! 😄 

Thanks for your help before. Based on the clear information you provided, I have attempted to design a workflow for the collaboration between KPM and AH. If there are any errors or areas that need improvement.

1. User publishes a KCL package to AH using KPM.
2. KPM generates the corresponding metadata (mainly includes artifacthub-pkg.yml and README.md) for the package.
3. KPM updates the metadata in the metadata repository. (This is a separate repository dedicated to maintaining metadata for all packages)
4. KPM uploads the package to AH.
5. AH retrieves the metadata from the metadata repository.
6. AH displays the package and its metadata to the users.
Please review the workflow and let me know if there are any mistakes. 

And a small question:
The `annotations` can also display on AH page ? I want to describe the dependencies between KCL packages in this field, just like the `related package` section in helm chart page, or is there any other way to show the `related package`.

**Comment by tegioz** [comment]
Hi @zong-zhe!

No worries, my pleasure 😊

Please note that when we add support for KCL packages, any user or organization would be able to add their KCL repositories from the control panel in the UI. We would also add a new section for KCL in the repositories guide, similar to the ones we have for other kinds.

My point here would be that the AH docs would be recommending to follow the same process that the rest of the artifacts kinds use and that publishers are familiar with. The main reason to go this way is that we have to provide support for it and, if we were recommending users to list their content on AH by using the KCL CLI tool and something wouldn't work as expected for any reason, we wouldn't be able to help 😇

There are some other additional points that you'd need to keep in mind in your workflow:

- Point 4 wouldn't actually be needed, as AH would visit periodically your metadata repository looking for new or updated packages.
- Your organization would appear as the publisher of all the packages in that repository. Some organizations may not like this and may prefer to publish their own content using their name (there are already thousands of organizations in AH that may be willing to publish their KCL packages 😉).
- When something goes wrong processing a package, you as the AH publisher would receive the errors for any of them (both tracking and scanning, if this applies to this case). This may become a problem as the number of packages grows. When each user/org publishes their content directly on AH, they will be notified when something goes wrong on their package and they'd be responsible for taking action, freeing you from that work.
- It may not be possible to assign the official flag to many KCL packages in that repository. One of the requirements is that the publisher is the owner of the underlying software. But in this workflow you may be publishing content owned by others.
- Publishers using this workflow may not be able to leverage all the features configurable from the `artifacthub-pkg.yml` file (or `artifacthub-repo.yml` file), as it would be transparently created for them by you. This may get worse as more features are added to AH and the metadata file grows.
- Similarly, you may need to cover cases like when a publisher wants to update an existing version, remove an old one, or simply stop listing their content on AH. Over time that may be an important burden.

These are just some thoughts that came of the top of my head, but I'm sure I'm leaving some more out 😅 We need to be careful as this approach will probably require more work on your side and you may introduce some AH limitations for your users. My recommendation would be to let each publisher take care of the AH metadata for their packages and have some automation in place to do it for your own packages. That way can focus on making KCL even greater 🚀

If you are happy with the metadata approach I described in my previous comment, we can start working on this soon, maybe even this week. It won't take long, we'll probably have it ready in one day. KCL packages could be listed on AH before KubeCon NA! 🙂

**Comment by tegioz** [comment]
Regarding your last question: you can use the `recommended` field in the metadata file if you'd like. But we can also display information from the annotations in the UI, not a problem :)

**Comment by zong-zhe** [comment]
Hi @tegioz !
Thanks for your suggestions. I will need to discuss with my team before finalizing the solution. Thank you very much for your thoughtful approach. 😊 😊 😊

**Comment by zong-zhe** [comment]
Hi @tegioz ! 😊
Thanks for your help before. We have considered the thoughtful ideas you provided. I would like to continue by adding some additional information.

> * Your organization would appear as the publisher of all the packages in that repository. Some organizations may not like this and may prefer to publish their own content using their name (there are already thousands of organizations in AH that may be willing to publish their KCL packages 😉).
> * When something goes wrong processing a package, you as the AH publisher would receive the errors for any of them (both tracking and scanning, if this applies to this case). This may become a problem as the number of packages grows. When each user/org publishes their content directly on AH, they will be notified when something goes wrong on their package and they'd be responsible for taking action, freeing you from that work.
- We do not intend to control all KCL packages on AH. Our goal is to build an open and free KCL community with the help of AH. Therefore, users can publish their KCL packages on AH in the way they prefer. Since we also publish some KCL packages ourselves, the metadata repository I mentioned above is for the package managed by ourselves, not for all the KCL users. 😆

> * Publishers using this workflow may not be able to leverage all the features configurable from the `artifacthub-pkg.yml` file (or `artifacthub-repo.yml` file), as it would be transparently created for them by you. This may get worse as more features are added to AH and the metadata file grows.

- We do not require all users to use KPM to generate `AH-pkg.yml`. Generating `AH-pkg.yml` using KPM is an optional choice for users. If a user provides their own `AH-pkg.yml` file in the root directory of the KCL package, it will take precedence. If a user does not provide this file, KPM will generate it for them. 😊 

And 

- We have created a [repository](https://github.com/kcl-lang/artifacthub) for AH metadata and uploaded three demos. This repository only contains documentations in markdown and `AH-pkg.yml`, and does not include the source code of KCL. It includes two versions, 1.27 and 1.28, of the `k8s` kcl package and a simple `helloworld`.
- Because the documentation is generated using a tool, it is currently in the form of multiple files nested within each other. The README.md in the root directory serves as the homepage. If AH does not support to display multiple nested documents, we can adjust the documentation to a single file later.

And some small questions:
> Regarding your last question: you can use the recommended field in the metadata file if you'd like. But we can also display information from the annotations in the UI, not a problem :)
- `recommended`, does it refer to [recommendations](https://github.com/kcl-lang/artifacthub/blob/main/helloworld/0.1.0/artifacthub-pkg.yml#L24)? If so, there might be a issue. We would prefer to accurately display the version and the link of the dependencies that the KCL package relies on. Using `recommendations` alone may not meet our requirements. However, this is not a fatal problem, as we can generate these dependency relationships in the README.md.

- If there is any way to showcase the demo from this repository on AH ? Or what do we need to prepare to establish the mechanism between the metadata repository and AH to display the metadata content from the repository in AH. The metadata in the repository may not be fully prepared yet, and we need to see the display on AH to obtain feedback and discuss what additional content to add.

**Comment by tegioz** [comment]
Hi @zong-zhe!

Sure, no worries 🙂

> * We do not intend to control all KCL packages on AH. Our goal is to build an open and free KCL community with the help of AH. Therefore, users can publish their KCL packages on AH in the way they prefer. Since we also publish some KCL packages ourselves, the metadata repository I mentioned above is for the package managed by ourselves, not for all the KCL users. 😆
>
> * We do not require all users to use KPM to generate `AH-pkg.yml`. Generating `AH-pkg.yml` using KPM is an optional choice for users. If a user provides their own `AH-pkg.yml` file in the root directory of the KCL package, it will take precedence. If a user does not provide this file, KPM will generate it for them. 😊

Oh, that was a misunderstanding then 😇 In the point 3 of your workflow:

*"KPM updates the metadata in the metadata repository. (This is a separate repository dedicated to maintaining metadata for all packages)"*

I understood that by KCL you meant the CLI tool, that this functionality would be baked into it, and maybe you meant KCL as the organization/project. If the KCL tool had the ability to push metadata to a central repository, users may think this is what KCL recommends or just do it "by default", without realizing that going that way may lead to some limitations later on.
 
> * We have created a [repository](https://github.com/kcl-lang/artifacthub) for AH metadata and uploaded three demos. This repository only contains documentations in markdown and `AH-pkg.yml`, and does not include the source code of KCL. It includes two versions, 1.27 and 1.28, of the `k8s` kcl package and a simple `helloworld`.

This looks great!

> * Because the documentation is generated using a tool, it is currently in the form of multiple files nested within each other. The README.md in the root directory serves as the homepage. If AH does not support to display multiple nested documents, we can adjust the documentation to a single file later.

👍

> * `recommended`, does it refer to [recommendations](https://github.com/kcl-lang/artifacthub/blob/main/helloworld/0.1.0/artifacthub-pkg.yml#L24)? If so, there might be a issue. We would prefer to accurately display the version and the link of the dependencies that the KCL package relies on. Using `recommendations` alone may not meet our requirements. However, this is not a fatal problem, as we can generate these dependency relationships in the README.md.

Not a problem, we can have a special section for that in the right column of the package detail view (like we do for Tekton pipelines, for example).

> * If there is any way to showcase the demo from this repository on AH ? Or what do we need to prepare to establish the mechanism between the metadata repository and AH to display the metadata content from the repository in AH. The metadata in the repository may not be fully prepared yet, and we need to see the display on AH to obtain feedback and discuss what additional content to add.

First we need to add support for the KCL artifact kind to AH. I think we can do this next week. Once it's done, we'll deploy it and you can experiment with it in staging (https://staging.artifacthub.io/). To do that, you'd need to add your repository to AH from the control panel in the UI.

**Comment by zong-zhe** [comment]
Hi @tegioz ! 😊
I appreciate your support. I am eagerly looking forward to experiencing it.

**Comment by zong-zhe** [comment]
Hi @tegioz ! 😊

I have a small question regarding the permission issue uploading packages to AH.

As we provide KPM as the main method for package uploading, the packages metadata will be displayed in AH (Artifact Hub) after the upload. However, the metadata file is stored in a GitHub repository. So, during the process of using kpm to upload, users need to perform a login operation before pushing. In other words, they need to first execute "kpm login aritfacthub.io" and then "kpm push". Is there any preparation work required to synchronize the permissions between AH and the metadata GitHub repository ?

**Comment by tegioz** [comment]
Hi @zong-zhe! 

This question clarifies a bit the initial misunderstanding 😅 When I thought you'd be appearing as the publisher of all packages pushed through KPM, it was because otherwise you'd need to deal with the permissions situation you're asking about now.

To make something like that work you'd need to:

- Push the metadata content to a GitHub repository, so you'd need users' GitHub credentials to do this on behalf of the user. Users may also need to update existing metadata, or delete a version. You may need to wrap quite a few operations that could be easily done directly on GitHub, and it'd be more transparent if something goes wrong.

- Create a repository in Artifact Hub. To do this, the user must already have an account in AH and, as in the previous step, they'd need to share their AH credentials with you so that KPM could create the repository in AH on their behalf. There are multiple options when a repository is added to AH, like to which organization they would like to add it to (the same user can belong to multiple organizations), the git branch to use, etc. Again you'd need to be wrapping all of this that could also be done easily in the Artifact Hub UI. When the repository is created on AH you'd include on it the GitHub url of the repo, that's how they connect, as repositories listed on <https://artifacthub.io> must be publicly accessible.

Artifact Hub visits repositories periodically (every 30 mins) and if something has changed on it, the repository will be processed and new/updated/deleted packages will be indexed as needed.

Hope this helps! 🙂

Please note that my recommendation would still be to avoid all of this, at least initially, and let users handle it separately 😉

**Comment by zong-zhe** [comment]
Hi @tegioz ! 😊
Thanks for you suggestions. This is helpful. For permissions, I need to discuss the solution with my team. Thanks again. 😊

**Comment by zong-zhe** [comment]
> First we need to add support for the KCL artifact kind to AH. I think we can do this next week. Once it's done, we'll deploy it and you can experiment with it in staging (https://staging.artifacthub.io/). To do that, you'd need to add your repository to AH from the control panel in the UI.

Hi @tegioz ! 😊
If there are any time points or arrangements for this matter? I would like to schedule my next steps accordingly based on these time points.

**Comment by tegioz** [comment]
This is ready @zong-zhe 🙂

You can see it in action in the staging environment, we'll deploy it to production soon.

<https://staging.artifacthub.io/packages/search?kind=20>
<https://staging.artifacthub.io/docs/topics/repositories/kcl-packages/>

Feel free to experiment with your own repository if you'd like 😉

Closed by #3434

<img width="1465" alt="kcl" src="https://github.com/artifacthub/hub/assets/1213902/28192fe0-90b6-4aef-ae80-ef2068572434">

**Comment by tegioz** [comment]
Hi @zong-zhe @Peefy 👋

There is a problem with some KCL modules in Artifact Hub (i.e. [this one](https://artifacthub.io/packages/kcl/kcl-module/actions-runner-controller)). They seem to be using [huge (~3MB) README files](https://github.com/kcl-lang/modules/tree/main/.integration/artifacthub/actions-runner-controller/0.1.0) that are slowing down the page load, specially on devices with slow Internet connections. I don't think those README files provide much value in AH TBH.

Could you please use a reduced version like you're doing in some other packages?

Thanks!

**Comment by Peefy** [comment]
Hi @tegioz. Thank you for your reminder. We will currently clean up and inspect the huge reference file and remove it from AH.

**Comment by tegioz** [comment]
Awesome, thanks @Peefy!

**Comment by tegioz** [comment]
> We will currently clean up and inspect the huge reference file and remove it from AH.

Hi @Peefy! This is a friendly reminder about the issue with the KCL readme files 🙂

**Comment by Peefy** [comment]
Sorry @tegioz I have already deleted a larger readme file in this commit, does it not work? https://github.com/kcl-lang/modules/commit/1e0770ffeca44eae2740bb82b14117ff88e463e4

**Comment by tegioz** [comment]
Sorry about that @Peefy, it was still failing in artifacthub.io and I didn't check the source repository.

It is still failing on our side because existing versions aren't processed again unless the `digest` field in the metadata file changes. You updated the README file but, unless the digest changes or a new version is released, it won't be picked by AH.

Let me try to force an update on our side, it may be easier. I'll let you know how it goes 🙂

**Comment by Peefy** [comment]
@tegioz Make sense! I've updated the rest huge documents in https://github.com/kcl-lang/modules/pull/116

**Comment by tegioz** [comment]
Thanks @Peefy!

Is it possible that some haven't been updated yet? Please see [this one](https://github.com/kcl-lang/modules/tree/main/.integration/artifacthub/aiven-operator/0.1.0) for example.
