### ISSUE TITLE
[OFFICIAL] Official status for the StackRox repository

### ISSUE THREAD

**Issue by Maddosaurus** [artifacthub/hub#3366]
Hey folks!

I'd like to request the official status for the StackRox repository (including both published packages, stackrox-central-services and stackrox-secured-cluster-services).
Regarding the CNCF question: While StackRox itself is not a CNCF project, Red Hat is the publisher, which holds multiple CNCF projects.
As additional information, I have included the product page of ACS, which is Red Hats downstream project that is based on StackRox.
If you need anything else, please let me know!

- **Repository name** *(in `artifacthub.io`)*: StackRox
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://github.com/stackrox/stackrox/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/stackrox/stackrox/
- **Other relevant URLs:** [ACS (Downstream Red Hat product based on StackRox)](https://www.redhat.com/en/technologies/cloud-computing/openshift/advanced-cluster-security-kubernetes)

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Thanks @Maddosaurus, both packages are now marked as official 🙂
