### ISSUE TITLE
[OFFICIAL] NetScaler Helm Charts

### ISSUE THREAD

**Issue by subashd** [artifacthub/hub#3367]
NetScaler Helm Charts

- **Repository name** *(in `artifacthub.io`)*: NetScaler Helm Charts
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL**: https://www.netscaler.com/solutions/cloud-native-and-kubernetes
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** N/A
- **Source code URL** *(if available)*: N/A
- **Other relevant URLs:** https://github.com/citrix/citrix-k8s-ingress-controller, https://github.com/netscaler/netscaler-xds-adaptor/tree/master, https://github.com/citrix/citrix-k8s-node-controller, https://github.com/citrix/citrix-observability-exporter

**Comment by tegioz** [comment]
Done!

**Comment by subashd** [comment]
Thank you @tegioz
