### ISSUE TITLE
https://artifacthub.io website is down.

### ISSUE THREAD

**Issue by KoeusIss** [artifacthub/hub#3368]
**Describe the bug**
I no longer able to access the https://artifacthub.io website, is can't be reached.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tegioz** [comment]
Hi @KoeusIss 👋

<https://artifacthub.io> seems to be up and running. I've just tested it from a couple of different networks and everything was fine. It'd be great if you could also test it from a different network, just in case the site is being blocked on yours for any reason (or that network is experiencing some issues at the moment).

Thanks for reporting it anyway!
