### ISSUE TITLE
Some APIs return error 500

### ISSUE THREAD

**Issue by Marcondiro** [artifacthub/hub#3382]
Hello,
On a clean install of ArtifactHUB some API calls return error 500 (listed below). I also tested the `GET` on the production env and obtained again error 500 so it might be worth to further investigate this.

**Describe the bug**
Error 500 while calling this APIs (with valid token):
`GET /api/v1/orgs/org1/accept-invitation`
`PUT /api/v1/packages/fd18976b-ce52-4f09-8adb-61d78b4c434d/stars`
`DELETE /api/v1/packages/helm/repoName/pkg1/production-usage/$org1`
`POST /api/v1/packages/helm/repoName/pkg1/production-usage/$org1`

**To Reproduce**
For the first one just visit https://artifacthub.io/api/v1/orgs/org1/accept-invitation (after login)

**Expected behavior**
Some HTTP 4xx error

**Comment by tegioz** [comment]
Hi @Marcondiro 👋

Do you mean you think there is a problem with some endpoints or that we should be using more precise http error codes whenever possible?

When those endpoints encounter an error, we try to [inspect the error and return the most appropriate code according to the information we have at that point](https://github.com/artifacthub/hub/blob/0a79ed4af086f7f3c0eab3753dadb8fc06f09616/internal/handlers/helpers/helpers.go#L82-L101). When we can't classify the error with more precision, we return a `500` error as a catch-all response. In those cases the error doesn't contain any information to make sure we don't leak any information we shouldn't.

If you think there is something wrong with those endpoints, you can inspect the details of those `500` errors in the `hub` pod logs. If you find something that isn't working as expected, please let us know and we'll gladly look into it 🙂

As an example, for the accept-invitation request, you may see something like this (provided that was your error as well):

```
11:30AM ERR Exec args=["org1"] cmd=hub err="ERROR: organization membership confirmation failed (SQLSTATE P0001)" module=pgx pid=77843 sql="select confirm_organization_membership($1::uuid, $2::text)"
11:30AM ERR error="ERROR: organization membership confirmation failed (SQLSTATE P0001)" cmd=hub handlers=org method=ConfirmMembership
11:30AM ERR /api/v1/orgs/org1/accept-invitation bytes_in= bytes_out=15 cmd=hub host=127.0.0.1 method=GET port=59802 status=500 took=6.886917
```

**Comment by Marcondiro** [comment]
Hello @tegioz 🙂
As you say error 500 is like a last resort  that you kinda hope to never return.

>Do you mean [...] we should be using more precise http error codes whenever possible?

I thought you might have been interested in knowing these few cases to catch the error and return a `4xx` or to check if there is something bad going on leading to this error. If it's not the case feel free to close the issue 🙂

**Comment by tegioz** [comment]
I agree that some of those errors should probably be `422` instead of `500`. But distinguishing them in many cases would require some additional database queries, and I'd rather not to do that at the moment to favor performance.

Thanks @Marcondiro, I'll close it for now but we appreciate you shared your findings 🙂
