### ISSUE TITLE
[OFFICIAL] oneuptime/oneuptime

### ISSUE THREAD

**Issue by simlarsen** [artifacthub/hub#3383]
- **Repository name** *(in `artifacthub.io`)*: oneuptime/oneuptime (https://artifacthub.io/packages/helm/oneuptime/oneuptime)
- **Official packages** *(leave empty if all packages in the repository are official)*: oneuptime/oneuptime (https://artifacthub.io/packages/helm/oneuptime/oneuptime)
- **Project URL:** https://oneuptime.com
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/OneUptime/oneuptime
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ x ] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [ x ] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [ x ] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!
