### ISSUE TITLE
[OFFICIAL] NetScaler Helm Charts

### ISSUE THREAD

**Issue by subashd** [artifacthub/hub#3392]
Repository name (in artifacthub.io): NetScaler Helm Charts (ID: 58714258-11d4-4228-8676-fffaf0ee005b)
Official packages (leave empty if all packages in the repository are official): ...
Project URL: https://www.netscaler.com/solutions/cloud-native-and-kubernetes
Is the publisher a CNCF project? (graduated, incubating or sandbox): N/A
Source code URL (if available): N/A
Other relevant URLs: https://github.com/netscaler/netscaler-k8s-ingress-controller, https://github.com/netscaler/netscaler-xds-adaptor/tree/master, https://github.com/netscaler/netscaler-k8s-node-controller, https://github.com/netscaler/netscaler-observability-exporter

**Comment by subashd** [comment]
@tegioz Could you please help me here?

**Comment by tegioz** [comment]
Hi @subashd 👋

IIRC we did this recently in #3367. Did you remove the packages and add them again by any chance? When that happens, the official status is removed as well and needs to be reapplied.

**Comment by subashd** [comment]
hi @tegioz ,
Yes we have to delete the old packages and this reapplication for the official status. Our Charts are moved from Citrix Github repo to official NetScaler Repo, due to which I need to reapply.
Could you please help me on this?

**Comment by tegioz** [comment]
Sure, leave it with me 🙂

**Comment by tegioz** [comment]
This is ready @subashd 🙂

Please note that if you need to update your repository url again at some point, you can edit it from the control panel, no need to remove it and add it back 😉

**Comment by subashd** [comment]
Thank you @tegioz  for the help.  👍

**Comment by tegioz** [comment]
No problem! 👋
