### ISSUE TITLE
[OFFICIAL] cert-manager

### ISSUE THREAD

**Issue by inteon** [artifacthub/hub#3394]
The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

We would like to request the `official` status for all charts in our repository.

- **Repository name** *(in `artifacthub.io`)*: cert-manager
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://github.com/cert-manager
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** incubating
- **Source code URL** *(if available)*: N/A
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*
    - the cert-manager Helm chart repo: https://charts.jetstack.io
    - we previously made some of our charts official: https://github.com/artifacthub/hub/issues/1281

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!

**Comment by inteon** [comment]
Thanks @tegioz!
Would it be possible to add the CNCF label too to these charts?

**Comment by tegioz** [comment]
Oh sure, I forgot that one 😅

**Comment by tegioz** [comment]
CNCF label should be ready now 🙂
