### ISSUE TITLE
Allow limited number of users to create Orgs and Repos

### ISSUE THREAD

**Issue by spuranam** [artifacthub/hub#3440]
To provide a high-quality artifact (Helm Charts, Tekton Tasks/Pipelines etc.) for my user base, i would like to restrict the number of users who can create orgs and repos, while allowing users to login create profiles, subscribe to updates notifications etc. I investigated creating a custom authorization policy, but this only allow me to create RBAC policies for the orgs that I own or create. I was wondering if there exists a way to achieve this.

**Comment by tegioz** [comment]
Hi @spuranam 👋

Unfortunately doing exactly that isn't possible in AH, and it's not something we have in our roadmap at the moment.

But you could achieve something similar by [not allowing users to sign up](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=values-schema&path=hub.server.allowUserSignUp) and [connecting AH to your identify provider](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=values-schema&path=hub.server.oauth.oidc). This would allow you to control who would be able to log into your Artifact Hub instance (needed to create orgs, publish repositories, etc). But the problem would be that other users wouldn't be able to create profiles or subscribe to updates notifications like you mentioned, so not sure if this would work for you.
