### ISSUE TITLE
[helm chart] Support `Ingress`' `spec.ingressClassName` field.

### ISSUE THREAD

**Issue by armingerten** [artifacthub/hub#3487]
**Is your feature request related to a problem? Please describe.**
The `kubernetes.io/ingress.class` annotation [was deprecated in Kubernetes 1.18](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation) in favor of using `IngressClass` resources. However, the helm chart for deploying ArtifactHub does not support specifying an `IngressClass` with the `Ingress`' `spec.ingressClassName` field.

**Describe the solution you'd like**
Support for `Ingress`' `spec.ingressClassName` field.

**Comment by tegioz** [comment]
Closed by #3488
