### ISSUE TITLE
The content that button `INSTALL` needs to display does not change synchronously after changing `artifacthub-pkg.yaml`

### ISSUE THREAD

**Issue by zong-zhe** [artifacthub/hub#3489]
**Describe the bug**
The content that button INSTALL needs to display does not change synchronously after changing artifacthub-pkg.yaml

**To Reproduce**

1. Search the KCL modules named 'helloworld'.
2. Go to the version '0.1.1'.
3. Click on 'INSTALL' button.

The result we will see

<img width="1874" alt="截屏2023-11-16 17 59 54" src="https://github.com/artifacthub/hub/assets/68977949/404bef20-ec54-46d8-b8cf-94e036027b64">

But we have changed the atrifacthub-pkg.yaml as below:

https://github.com/kcl-lang/modules/blob/main/.integration/artifacthub/helloworld/0.1.1/artifacthub-pkg.yaml

<img width="398" alt="截屏2023-11-16 18 01 55" src="https://github.com/artifacthub/hub/assets/68977949/9d98db67-da57-4f2f-bb9a-398d7243f433">

**Expected behavior**

The installation commands should be `kcl mod add helloworld:0.1.1` and `kcl mod pull helloworld:0.1.1`

not `kpm add helloworld:0.1.1` and `kpm pull helloworld:0.1.1`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macos ventura 13.6
 - Browser [e.g. chrome, safari] : chrome
 - Version [e.g. 22] 119.0.6045.123 (arm64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tegioz** [comment]
Hi @zong-zhe 👋

Artifact Hub processes packages periodically (every 30 mins) and when a new version is released or when it's updated **and** its digest changes, the new content is indexed and displayed on the UI.

In this case, if you'd like to update the install instructions without releasing a new version, you need to update the `digest` field in the metadata file. Ideally existing versions shouldn't be modified, but there are situations (like this one) where it may be handy. So AH provides this mechanism to force the reindexing of an existing version.

Hope this helps 🙂
