### ISSUE TITLE
loki helm upgrade failed from helm version  2.11.1   to 3.3.3 on eks 1.24 version

### ISSUE THREAD

**Issue by pvilasra** [artifacthub/hub#3519]
**Describe the bug**
Hi Team I will be updating eks version 1.25 for that need to upgrade loki helm chart as pod security policy is getting depricated. but getting me below error. We have ovverrided some of the values.yaml configuration as well

Error: execution error at (loki/templates/validate.yaml:2:4): Top level 'config' is not allowed. Most common configuration sections are exposed under the `loki` section. If you need to override the whole config, provide the configuration as a string that can contain template expressions under `loki.config`. Alternatively, you can provide the configuration as an external secret.
│
│   with module.service.helm_release.loki,
│   on ..\..\..\..\modules\loki\helm.tf line 1, in resource "helm_release" "loki":
│    1: resource "helm_release" "loki" {

**To Reproduce**
Error: execution error at (loki/templates/validate.yaml:2:4): Top level 'config' is not allowed. Most common configuration sections are exposed under the `loki` section. If you need to override the whole config, provide the configuration as a string that can contain template expressions under `loki.config`. Alternatively, you can provide the configuration as an external secret.
│
│   with module.service.helm_release.loki,
│   on ..\..\..\..\modules\loki\helm.tf line 1, in resource "helm_release" "loki":
│    1: resource "helm_release" "loki" {

**Expected behavior**
I want to upgrade the loki helm chart as pod security policy is getting depricated

**Screenshots**
NA

**Desktop (please complete the following information):**
EKS version 1.25

**Additional context**
overridedn yaml files: loki_config.yaml

config:
  auth_enabled: false
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: aws
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
  server:
    http_listen_port: 3100
    grpc_server_max_recv_msg_size: 8388608
    grpc_server_max_send_msg_size: 8388608
  storage_config:
    aws:
      s3: s3://${aws_region}
      bucketnames: ${aws_s3_bucket}
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      shared_store: aws
      cache_location: /data/loki/boltdb-shipper-cache
  chunk_store_config:
    max_look_back_period: 4320h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 4320h
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: aws
  ruler:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/scratch
    alertmanager_url: ${alertmanager_url}
    ring:
      kvstore:
        store: inmemory
    enable_api: true

------------------------------------------------------------------------------------------
loki.yaml

nodeSelector:
  node-role: ${node_selector}

podLabels:
  service: loki
  deployment: ${deployment}
  environment: ${environment}

priorityClassName: "system-cluster-critical"

replicas: 1

resources:
  limits:
    cpu: ${loki_resources.limits.cpu}
    memory: ${loki_resources.limits.memory}
  requests:
    cpu: ${loki_resources.requests.cpu}
    memory: ${loki_resources.requests.memory}

serviceAccount:
  create: true
  annotations:
    "eks.amazonaws.com/role-arn": "${sa_role_arn}"

rbac.pspEnabled: false

serviceMonitor:
  enabled: true
  interval: "30s"
  additionalLabels:
    release: monitoring
    service: loki
    environment: ${environment}
    deployment: ${deployment}
# extraArgs:
#   log.level: debug

readinessProbe:
  initialDelaySeconds: 60

livenessProbe:
  initialDelaySeconds: 60

**Comment by tegioz** [comment]
Hi @pvilasra 👋

For issues with the content listed on artifacthub.io it's best to contact the particular project directly. In the links section of the right panel in the package view you usually may find some links that can point you to the project's repository or the maintainers emails.

Hope this helps 🙂
