### ISSUE TITLE
trivy does not support scanning images with schema v1

### ISSUE THREAD

**Issue by calvinyv** [artifacthub/hub#3523]
**Is your feature request related to a problem? Please describe.**
some image is built based as schema v1, and seems artifacthub use trivy and scan tool which doesn't support this kind of schema
for example: quay.io/k8scsi/livenessprobe:v1.1.0
**Describe the solution you'd like**
option 1: support filter or whitelist on whole repo scan
option 2: add more scan tool besides trivy

**Comment by tegioz** [comment]
Hi @calvinyv 👋 

At the moment we do not have plans to add support for more security scanners.

However, you can already whitelist images both at the repository level (from the control panel, editing the repository) and at the image level. To do it at the image level, you need to define the container images used by your package manually and set the `whitelisted` field to true on those you'd rather not to scan.

Depending on the package kind this may be done differently. In the case of Helm charts, for example, you can define your container images using the `artifacthub.io/images` annotation. For more details please see the [Helm annotations documentation](https://artifacthub.io/docs/topics/annotations/helm/).

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
