### ISSUE TITLE
Help with opensearch-project org transfer.

### ISSUE THREAD

**Issue by prudhvigodithi** [artifacthub/hub#3533]
Hey, myself [prudhvigodithi](https://github.com/prudhvigodithi/) I'm a member of this [opensearch-project org ](https://github.com/opensearch-project). I see we have an org account in the artifcathub https://artifacthub.io/packages/search?ts_query_web=opensearch-project&sort=relevance&page=1, but not sure who are the owners of the org created in the artifcathub. This is becoming a problem to add new repos to this org or create an org with the same name which is not allowed. Can you please help add me (artifcathub ID: prudhvigodithi) as owner of the the [artifcathub opensearch-project org ](https://artifacthub.io/packages/search?ts_query_web=opensearch-project&sort=relevance&page=1)?

I have expected when sign in with github, if we are admins to a github org it would have been listed under the control panel context but dint, looks like the org access should be given from the account it was created.

Seen a similar issue in past https://github.com/artifacthub/hub/issues/1684, hence tagging @mattfarina.

Thank you

**Comment by tegioz** [comment]
Hi @prudhvigodithi 👋

The only member of that organization is @viceice. Maybe he could invite you to it, so that you can invite some other members and add more repositories to Artifact Hub 🙂

**Comment by viceice** [comment]
will do asap

**Comment by prudhvigodithi** [comment]
Thanks @tegioz for the information and thanks @viceice I have just accepted the invitation.

**Comment by prudhvigodithi** [comment]
Hey I have the [artifacthub-repo.yml](https://github.com/opensearch-project/opensearch-k8s-operator/blob/gh-pages/artifacthub-repo.yml) file in right place when I want to claim the repo ownership to https://artifacthub.io/packages/search?ts_query_web=opensearch-project&sort=relevance&page=1, I get the error as follows
![Screenshot 2023-12-06 at 5 05 21 AM](https://github.com/artifacthub/hub/assets/28733332/ea3a3292-d095-47dc-b216-194c5f2a4160)

Can you please check if anything I'm missing with permissions @tegioz @viceice ?

**Comment by viceice** [comment]
The email address in the yaml must match your artifacts.io account too.

**Comment by viceice** [comment]
- https://github.com/opensearch-project/opensearch-k8s-operator/pull/681

**Comment by prudhvigodithi** [comment]
Thanks @viceice before we merge this PR, if we coordinate with https://opster.github.io/opensearch-k8s-operator/ is it possible to transfer from opster to opensearch-project? Just want to retain all the download activity etc. Thanks.

**Comment by viceice** [comment]
yes, then i need to remove it from our org again and opster need to change the url on artifacts hub.

**Comment by prudhvigodithi** [comment]
Also once the opster change the url on artifacts hub can we claim the ownership ?

**Comment by viceice** [comment]
sure, removed. yes than you can transfer

**Comment by tegioz** [comment]
Please let me know if you need any help with the transfers 🙂 It'd be great if you could do the them from the AH control panel, as that way nothing will be lost (users subscriptions, stars, webhooks, etc). You can always invite someone to the organization temporarily so that they can do the transfer, or transfer to a user and then back to the final organization.

**Comment by viceice** [comment]
because this are two different charts inside that repo

**Comment by prudhvigodithi** [comment]
A quick summary:
- I have got the access to the [opensearch-project artifacthub org](https://artifacthub.io/packages/search?ts_query_web=opensearch-project&sort=relevance&page=1).
- Able to transfer the [opensearch-operator helm repo](https://artifacthub.io/packages/helm/opensearch-operator/opensearch-operator) to opensearch-project artifacthub org.

Thanks @viceice and @tegioz for all your help.
