### ISSUE TITLE
Some Docker images are missing from the CONTAINERS IMAGES and SECURITY REPORT sections

### ISSUE THREAD

**Issue by wallrj** [artifacthub/hub#3551]
The [SECURITY REPORT modal for cert-manager's Helm chart](https://artifacthub.io/packages/helm/cert-manager/cert-manager?modal=security-report) doesn't include two of the standard Docker images:

 * ACME Solver image: Which is used in a Pod which cert-manager creates at runtime

https://github.com/cert-manager/cert-manager/blob/37e425c4da3ccd93a764ae06be5ddcf207e20e0d/deploy/charts/cert-manager/values.yaml#L653-L655

 * Startup API Check image: Which is associated with a Job of a post-install hook

https://github.com/cert-manager/cert-manager/blob/37e425c4da3ccd93a764ae06be5ddcf207e20e0d/deploy/charts/cert-manager/values.yaml#L667-L736

It would be useful if there was a way to show these in the ArtifactHub UI too.

**Comment by tegioz** [comment]
Hi @wallrj 👋

By default, Artifact Hub tries to detect the images used by the Chart by doing a dry-run install and extracting them from the generated manifests using some regular expressions. But sometimes this mechanism isn't accurate.

In those cases, you can define the containers images manually using the [artifacthub.io/images annotation](https://artifacthub.io/docs/topics/annotations/helm/). Please note that defining them manually disables the automatic detection, so all images must be listed, not only the ones missing (as you might be interested in removing some in other cases). As soon as you list all the images they'll be scanned and included in the security report as usual.

Hope this helps 🙂
