### ISSUE TITLE
[OFFICIAL] OpenProject Helm Charts

### ISSUE THREAD

**Issue by oliverguenther** [artifacthub/hub#3556]
I'd like to request official status for the `openproject-helm-charts` repository:

- **Repository name** *(in `artifacthub.io`)*: https://artifacthub.io/packages/helm/openproject-helm-charts/openproject
- **Official packages** *(leave empty if all packages in the repository are official)*: (all)
- **Project URL:** https://charts.openproject.org https://github.com/opf/helm-charts
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/opf/helm-charts
- **Other relevant URLs:** 
  - Software homepage: https://www.openproject.org/
  - Software core repository https://github.com/opf/openproject/

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it. (The latter, I'm a user of the openproject organization)
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!
