### ISSUE TITLE
Keycloak service failing

### ISSUE THREAD

**Issue by pvilasra** [artifacthub/hub#3569]
**Describe the bug**
I am using keycloak helm chart version 18.1.1. Deployed on AWS EKS 1.25 version. Suddnely I am getting error in keycloak service pod .

**To Reproduce**
You can install codecentric keycloak helm chart version 18.1.1 on AWS EKS 1.25 version.

**Expected behavior**
Other environment same pod is runngin file but in other environments pod has no restart from long time, 

**Screenshots**
![image](https://github.com/artifacthub/hub/assets/91858230/0d32f317-599a-4696-b6c3-9e96fc76d386)

**Additional context**
How to solve the error:

│ 11:22:55,478 INFO  [org.infinispan.CLUSTER] (ServerService Thread Pool -- 80) ISPN000080: Disconnecting JGroups channel ejb                                                                                                      │
│ 11:22:55,490 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "metrics")]): java.lang.NullPointerException                       │
│     at org.wildfly.extension.metrics@26.0.1.Final//org.wildfly.extension.metrics.MetricsSubsystemAdd$2.execute(MetricsSubsystemAdd.java:91)                                                                                      │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1045)                                                                                    │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:777)                                                                                   │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:466)                                                                                │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1427)                                                                                       │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:550)                                                                                                      │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:554)                                                                                          │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:516)                                                                                          │
│     at org.jboss.as.server@18.0.4.Final//org.jboss.as.server.ServerService.boot(ServerService.java:461)                                                                                                                          │
│     at org.jboss.as.server@18.0.4.Final//org.jboss.as.server.ServerService.boot(ServerService.java:414)                                                                                                                          │
│     at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:455)                                                                                         │
│     at java.base/java.lang.Thread.run(Thread.java:829)                                                                                                                                                                           │
│ 11:22:55,569 ERROR [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0022: Deploy of deployment "keycloak-server.war" was rolled back with no failure message

**Comment by tegioz** [comment]
Hi @pvilasra 👋

For issues with the content listed on artifacthub.io it's best to contact the particular project directly. In the links section of the right panel in the package view you usually may find some links that can point you to the project's repository or the maintainers emails.

Hope this helps 🙂
