### ISSUE TITLE
[OFFICIAL] myip

### ISSUE THREAD

**Issue by jmnote** [artifacthub/hub#3570]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: myip
- **Official packages** *(leave empty if all packages in the repository are official)*: myip
- **Project URL:** https://github.com/kuoss/helm-charts/tree/main/charts/myip
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/kuoss/myip
- **Other relevant URLs:** https://github.com/kuoss/myip/pkgs/container/myip

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @jmnote 👋 

Could you please extend a bit the description? Thanks!

<img width="1036" alt="description" src="https://github.com/artifacthub/hub/assets/1213902/3c044db6-0367-4045-9095-4c026f18a64e">

**Comment by jmnote** [comment]
@tegioz Now updated. Thanks!

![image](https://github.com/artifacthub/hub/assets/2242405/185009e0-47e1-4bae-803f-eee9cb99bb82)

**Comment by tegioz** [comment]
Thanks, `myip` is now marked as official 🙂
