### ISSUE TITLE
[OFFICIAL] Keptn (new Helm repo)

### ISSUE THREAD

**Issue by mowies** [artifacthub/hub#3637]
- **Repository name** *(in `artifacthub.io`)*: https://artifacthub.io/packages/helm/lifecycle-toolkit/keptn
- **Project URL:** https://keptn.sh
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Yes, incubating
- **Source code URL** *(if available)*:
  - Source code: https://github.com/keptn/lifecycle-toolkit
  - Charts repo: https://github.com/keptn/lifecycle-toolkit-charts

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!
