### ISSUE TITLE
[ABUSE-REPORT] TheHive

### ISSUE THREAD

**Issue by nadouani** [artifacthub/hub#3638]
**Describe the problem**

TheHive is a piece of software built by [TheHive Project](https://github.com/TheHive-Project) which is governed by [StrangeBee](https://github.com/StrangeBeeCorp).

We are currently publishing an official Helm Chart for our products. We have found an unofficial chart (https://artifacthub.io/packages/helm/ittrident-oss/thehive) using the name of our product and mentioned as "Related Package" to what we are publishing.

We would like to understand what's possible and what's not in order to:

* protect our brand
* protect our customer as we don't want them to use non official packages

Thank you

**Comment by tegioz** [comment]
Hi @nadouani 👋

This is something fairly common in Artifact Hub, and IMHO it's fine -and something positive in many cases- to provide alternative charts for a piece of software. If you search for some popular packages  you'll notice that there are often multiple options available. If we take `nginx ingress` as an example, you'll find one chart published by the Nginx organization and one published by the Kubernetes organization (both being quite popular).

The other publisher doesn't seem to be claiming they're the owner of the software or impersonating your organization. For cases like this, the best option is to request the official status (which you just did! 😉). This way final users will know which alternative comes from the owner of the software when deciding what package they'd like to use.

Hope this helps 🙂

**Comment by nadouani** [comment]
Hi @tegioz that's fair enough, got it.

Is there a way to tell the other publisher that his chat is using a docker image that is no longer available? Typically, that chart cannot work.

Best

**Comment by tegioz** [comment]
Publishers can include the maintainers' email or links to report an issue in the package (AH displays this info on the UI). But it looks that that package doesn't provide that information yet. Maybe you could file an issue on their GitHub repo: https://github.com/itTrident/helm-charts 🙂

**Comment by nadouani** [comment]
Sounds like a plan, thanks @tegioz
