### ISSUE TITLE
[OFFICIAL] SLE BCI 15 SP5 Base Container Image

### ISSUE THREAD

**Issue by dirkmueller** [artifacthub/hub#3644]
- **Repository name** *(in `artifacthub.io`)*: bci-base
- **Project URL:** https://www.suse.com/products/base-container-images/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):**  no
- **Source code URL** *(if available)*: https://sources.suse.com/SUSE:SLE-15-SP5:Update:CR/sles15-image/?C=M;O=D
- **Other relevant URLs:** https://registry.suse.com/categories/bci/repositories/bci-bci-base-15sp5

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!
