### ISSUE TITLE
Multiple helm charts in OCI

### ISSUE THREAD

**Issue by cwrau** [artifacthub/hub#3645]
**Is your feature request related to a problem? Please describe.**
We maintain and publish multiple helm charts and publish them using oci. 
Sadly artifacthub can only scan a single chart per oci repository. 

**Describe the solution you'd like**
That artifacthub is able to scan multiple charts from a single artifacthub URL. 

**Describe alternatives you've considered**
Otherwise we'd have to publish them via the old index.yaml setup. 

**Additional context**

**Comment by tegioz** [comment]
I'll close this one for now as there isn't much we can do at the moment. But we'll keep an eye on this and as soon as more options are available we'll add support for them 🙂

**Comment by cwrau** [comment]
> I'll close this one for now as there isn't much we can do at the moment. But we'll keep an eye on this and as soon as more options are available we'll add support for them 🙂

Mh, maybe you could add support to a repo to include multiple oci urls?

The repo manager would still have to add all the urls, but at least the end user can find all the charts at a single repo/url? 🤔

**Comment by tegioz** [comment]
Not sure if you mean to keep using the repo `index.yaml` file served from an HTTP server for this purpose, or have this or other similar file stored in an OCI registry (using some standard reference, for example).

If it's the former please see: https://github.com/helm/helm/issues/12322 (it was linked from the other comment I shared 😉). IMHO it wouldn't be ideal to serve the `index.yaml` file one way (i.e. regular HTTP server) and serve the charts from an OCI registry. But that'd be an option if/when it's supported by Helm.

If you mean the later (i.e. having the current or a different repo index file in the OCI registry as well, as I mentioned OLM does for operators), this is something that should probably be defined by Helm first, as they know best how it'd fit with the rest of their tooling and features.

**Comment by cwrau** [comment]
> Not sure if you mean to keep using the repo `index.yaml` file served from an HTTP server for this purpose, or have this or other similar file stored in an OCI registry (using some standard reference, for example).
> 
> If it's the former please see: https://github.com/helm/helm/issues/12322 (it was linked from the other comment I shared 😉). IMHO it wouldn't be ideal to serve the `index.yaml` file one way (i.e. regular HTTP server) and serve the charts from an OCI registry. But that'd be an option if/when it's supported by Helm.
> 
> If you mean the later (i.e. having the current or a different repo index file in the OCI registry as well, as I mentioned OLM does for operators), this is something that should probably be defined by Helm first, as they know best how it'd fit with the rest of their tooling and features.
> 

I meant neither, I wanted to propose to add multiple URL fields in the artifacthub repo settings
