### ISSUE TITLE
[OFFICIAL] TrueCharts Library-Charts

### ISSUE THREAD

**Issue by Ornias1993** [artifacthub/hub#3657]
- **Repository name** *(in `artifacthub.io`)*: TrueCharts Library-Charts
- **Official packages** *(leave empty if all packages in the repository are official)*: common (common-test is excluded in config)
- **Project URL:** https://truecharts.org
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No.
- **Source code URL** *(if available)*: https://github.com/truecharts/library-charts
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**note**
**notes**
- The common-chart is not an application chart, it's an extreme all-encompassing library chart, that can be used to build other helm-charts with. 

- We offer both an official https and OCI version, which have to be seperate artifacthub repositories.

**Comment by cynthia-sg** [comment]
Done!
