### ISSUE TITLE
Official Helm charts not included when filtered "official"

### ISSUE THREAD

**Issue by hpvd** [artifacthub/hub#3660]
Official Helm charts not included when filtered "official"

e.g. Pulsar 

not filtered for "official":
pulsars helm chart is visible

enabling "official" filter:
pulsars helm chart is not visible anymore

see:
https://artifacthub.io/packages/search?kind=0&license=Apache-2.0&ts_query_web=apache&sort=last_updated&page=1

![2024-02-15_18h06_02](https://github.com/artifacthub/hub/assets/5681880/8a44a72f-7a8a-41e6-ad24-157891850430)

![2024-02-15_18h06_44](https://github.com/artifacthub/hub/assets/5681880/eb7b9b67-f26e-4d5b-8d06-1da751fa3502)

**Comment by tegioz** [comment]
Hi @hpvd 👋

The [official status needs to be requested](https://artifacthub.io/docs/topics/repositories/#official-status), as we need to verify that the required conditions are met.

Hope this helps 🙂

**Comment by tegioz** [comment]
No worries!

That is the repository's display name, and it's filled out by publishers. I'd like to think that most publishers will do the right thing and use "official" word in the description when it applies. That chart is probably the official one, so not having restrictions can be beneficial for users in some cases. But yes, I agree it can be misleading as well.

**Comment by hpvd** [comment]
thanks for getting back again :-)

I'm not about abuse of the term `official` - its about motivation!

If you can write `official` in this field, from pov of repository owner, there is no motivation left to get your official status confirmed.
If there is little motivation, the filter for official chart etc can not build up its full great use.
