### ISSUE TITLE
Kubewarden policy marked as unsinged

### ISSUE THREAD

**Issue by jvanz** [artifacthub/hub#3661]
**Describe the bug**
The container resource Kubewarden policy has been signed. But the Artifacthub UI show it as unsigned.

**To Reproduce**
1. Go to https://artifacthub.io/packages/kubewarden/container-resources/container-resources
2. See that the signed flag is disabled.

**Expected behavior**
The policy should be marked as signed. It is signed. 

**Additional context**

I've noticed that in the main Kubewarden page (link shared above) the repository is mark as official. But in the repositories list in the kubewarden control panel, it is **not** mark as official

**Comment by tegioz** [comment]
Hi @jvanz 👋

Is it possible that this is a duplicate of #2922? (which you filed some time ago 😇) Not sure if the workaround suggested was implemented in the end (it looks like the branch used is still `main`), or you found a different solution.

I just did the same I did in that occasion: local test that worked fine and force the repo to be reprocessed on `artifacthub.io`, and the signature was detected correctly. This seems to be a timing thing and it'll happen every now and then until you can fix it on your end.

Regarding your question in the additional context: there are two ways to grant the official status, at the repository level and at the package level. That icon in the control panel refers to the repository level, which we rarely use these days.

**Comment by jvanz** [comment]
Sorry @tegioz , I did not remember the old issue. But yes, yesterday I've double checked the container repository configuration and noticed that the security check flag was disabled. I've enabled it and wait for the next security check. It seems to work. Thus, I'm closing this. :)

Thanks!

**Comment by tegioz** [comment]
No worries!

Please note that versions already processed won't be processed again unless the `digest` changes. This time it was updated because I forced it manually, but otherwise it'd still be broken. If this happens to you again in the future  because of the time gap until the signature is ready, you can fix it on your end by updating the package's digest 🙂
