### ISSUE TITLE
[OFFICIAL] Clabernetes

### ISSUE THREAD

**Issue by hellt** [artifacthub/hub#3667]
👋 
on behalf of Nokia and our subdivision SRL-Labs I would like to apply for the official status to be granted for the `clabernetes` helm chart - https://artifacthub.io/packages/helm/clabernetes/clabernetes - that is sourced from our repo https://github.com/srl-labs/clabernetes and documented at https://c9s.run

**Comment by tegioz** [comment]
Hi @hellt 👋

Could you please create an organization and transfer the package to it (SRL Labs, for example, or whatever you think fits best)? We usually recommend official packages that belong to an organization to be published under that org in Artifact Hub. This is helpful for final users when deciding among multiple options, and allows you to invite other project's members to the organization if you'd like.

Thanks!

**Comment by hellt** [comment]
Thanks @tegioz 
I moved the repository under an org `srl-labs`

https://artifacthub.io/packages/helm/clabernetes/clabernetes

**Comment by tegioz** [comment]
Thanks, done!
