### ISSUE TITLE
Outdated docker-mailserver/docker-mailserver chart

### ISSUE THREAD

**Issue by emouawad** [artifacthub/hub#3676]
**Describe the problem**
- Outdated chart  
- Default Values inaccessible

**Additional context**
Official helm chart repo is updated on: https://github.com/docker-mailserver/docker-mailserver-helm

**Comment by tegioz** [comment]
Hi @emouawad 👋

Could you please ping the publisher of that chart in the repository you linked and ask them to update the repository url from the Artifact Hub control panel? Maybe the chart was moved to a different location, but the reference in Artifact Hub wasn't updated. This is something that publishers can manage directly.

Thanks!

**Comment by tegioz** [comment]
Will close this issue for now. It'd be great if you could ping the publisher to get this fixed @emouawad. Thanks!
