### ISSUE TITLE
Host Tekton StepActions on ArtifactHub

### ISSUE THREAD

**Issue by chitrangpatel** [artifacthub/hub#3677]
Tekton Pipelines introduced `StepActions` in [v0.54.0](https://github.com/tektoncd/pipeline/releases/tag/v0.54.0). We want to provide a catalog of Tekton `StepActions` and host them on ArtifactHub like we do for Tekton `Tasks` and `Pipelines`.

What would be required to enable this in ArtifactHub? I was not involved with setting up Tasks and Pipelines so I'd appreciate any help. 

cc @vdemeester @afrittoli

**Comment by tegioz** [comment]
Hi @chitrangpatel 👋

We'd be happy to add support for Tekton StepActions as a new artifact kind.

Please take a look at the following links to see how Tekton tasks and pipelines repositories work in Artifact Hub:

<https://artifacthub.io/docs/topics/repositories/tekton-tasks/>
<https://artifacthub.io/docs/topics/repositories/tekton-pipelines/>
<https://artifacthub.io/docs/topics/annotations/tekton/>

Is there a Tekton StepActions catalog source repository we can take a look at? (i.e. like <https://github.com/tektoncd/catalog/tree/main/task> and <https://github.com/tektoncd/catalog/tree/main/pipeline>).

**Comment by chitrangpatel** [comment]
Thanks for the quick reply @tegioz . We are in the process of adding `StepActions` to our GitHub catalog. The structure will be identical to that of `Tasks` and `Pipelines`. 

I will reach out again as soon as we have something there.

**Comment by tegioz** [comment]
Awesome, thanks! 👍

**Comment by chitrangpatel** [comment]
Hi @tegioz we now have a StepAction in our Github Catalog: https://github.com/tektoncd/catalog/tree/main/stepaction/git-clone/0.1 

What are the next steps?

**Comment by tegioz** [comment]
Thanks @chitrangpatel 👍

We'll look into it and add support for this new kind. We'll ping you when it's ready 🙂

**Comment by chitrangpatel** [comment]
Thanks @tegioz ! 

Do you have a prospective timeline on this, just so that we can leave some estimates in our tracking issues. Please let me know if we can do anything to help with this.

**Comment by tegioz** [comment]
Yes, we'll probably work on this next week 🙂

**Comment by tegioz** [comment]
This is mostly ready @chitrangpatel!

Quick question: any chance we can have a `description` field in the [StepActionSpec type](https://github.com/tektoncd/pipeline/blob/5222fbeba2ac62f440739651a9c9d381b7244128/pkg/apis/pipeline/v1alpha1/stepaction_types.go#L76), like you have in [PipelineSpec](https://github.com/tektoncd/pipeline/blob/5222fbeba2ac62f440739651a9c9d381b7244128/pkg/apis/pipeline/v1/pipeline_types.go#L108-L111) and [TaskSpec](https://github.com/tektoncd/pipeline/blob/5222fbeba2ac62f440739651a9c9d381b7244128/pkg/apis/pipeline/v1beta1/task_types.go#L115-L118)? That's the description we display on the UI 😇

**Comment by chitrangpatel** [comment]
We do not have that currently. I think we will add it before the next release. Any chance we can go ahead without it and add it once we implement it in the Spec?

**Comment by tegioz** [comment]
Sure, no problem 👍

It'd be great if you could ping us when it's ready and part of a release to improve the StepActions support 🙂

**Comment by chitrangpatel** [comment]
@tegioz I dont see StepActions on https://artifacthub.io/. Did anything go wrong?

**Comment by tegioz** [comment]
Hi @chitrangpatel!

It looks like no StepActions repositories have been published on <https://artifacthub.io> yet. I added one to staging to test everything was working fine, but in production ideally this should be done by the owner of the repository so that the UI displays the correct publisher 🙂

You can do it from the AH control panel (if you do it from the Tekton organization much better). Please let me know if you have any problems!
