### ISSUE TITLE
[OFFICIAL] k8s-ssh

### ISSUE THREAD

**Issue by shlomibendavid** [artifacthub/hub#3680]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: **shlomibendavid**
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** **https://github.com/shlomibendavid/helm-charts**
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** ...
- **Source code URL** *(if available)*: **https://github.com/shlomibendavid/k8s-ssh-src** (private)
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @shlomibendavid 👋

Without having access to the source code repository, we may not be able to verify the ownership of the `k8s-ssh` software. Publishing the source is not a requirement at all, but usually when it's not available the publishing organization provides some other links that can help us with the verification process.

**Comment by shlomibendavid** [comment]
Hi Sergio,

Thanks for your email.
You can verify it from the following URL:
https://github.com/shlomibendavid/helm-charts
In this URL, you can find the package tarball.

BR,
Shlomi Ben-David

**Comment by tegioz** [comment]
Hi!

But that's just the chart :)

Please remember that to mark a chart as official, the publisher must own the software the chart relies on (in this case, the `k8s-ssh` software, which I guess lives in the private repo you linked). In the chart we can only see a reference to a container image, but nothing else that allows us to verify that the software on that image is owned by you.

Hope I've explained myself better this time 😇

**Comment by shlomibendavid** [comment]
Hi Sergio,

There is a simple bash script (entrypoint.sh) in my image that operates.
The image is exposed widely, and you can download it (I'm managing it; a
screenshot is attached):

*docker pull shlomibendavid/k8s-ssh:0304240306*

You can check the script and see that I'm the author.

Hope that it's ok... else... I will appreciate your guidance for other
options.

Thanks in advance,
Shlomi Ben-David

**Comment by tegioz** [comment]
That's ok, thanks, I've just taken a look at it 🙂

The chart is now marked as official, you should see it in a few minutes!
