### ISSUE TITLE
AH linter does not support git-based versioning structure for tekton kinds

### ISSUE THREAD

**Issue by ksimon1** [artifacthub/hub#3691]
**Is your feature request related to a problem? Please describe.**
AH linter contains hardcoded directory-based type of versioning for tekton kinds - https://github.com/artifacthub/hub/blob/master/cmd/ah/lint.go#L386.
According to https://artifacthub.io/docs/topics/repositories/tekton-tasks/, the git-based versioning is "newer and recommended", but ah linter does not supports it.
**Describe the solution you'd like**
AH linter supports both types of versioning.

**Comment by ksimon1** [comment]
I am closing this issue, because the root cause is probably caused by bug https://github.com/artifacthub/hub/issues/3692

**Comment by tegioz** [comment]
Hi again @ksimon1!

> According to https://artifacthub.io/docs/topics/repositories/tekton-tasks/, the git-based versioning is "newer and recommended"

I think we'll update the docs to remove that part. The tasks and pipelines catalogs at <https://github.com/tektoncd/catalog> still use directory-based structure. And I personally prefer that one as well, as IIRC the git-based structure forces you to bump the version of all packages in the same repository at the same time, as the version is taken from the git tag. Please see the issue/comment referenced below for more details.

From https://github.com/artifacthub/hub/issues/2326#issuecomment-1252587793:

> This one is also related to versions. In Artifact Hub, every package (a task or pipeline in this case) must have a version. Given that all tasks in a catalog will share the same version, I understand that sometimes the version for a task will be bumped even though that particular task may not have changed at all. Users in Artifact Hub can subscribe to new releases notifications and, in cases like the one just mentioned, they may be notified about a new package release when nothing actually changed, which could be a bit annoying for users. I've already discussed this concern with @QuanZhang-William in Slack, and he mentioned that you were moving to smaller repos with fewer (or even one) packages per repo, which would definitely help.

**Comment by tegioz** [comment]
> I think we'll update the docs to remove that part.

Self-correction: this was requested by the Tekton team, so we'll leave it as it is 😇

**Comment by ksimon1** [comment]
@tegioz Thanks for the information. I am reopening this issue, because we will be using AH linter for our tasks / pipelines which will be using git based versioning.
