### ISSUE TITLE
Add kubeVersion to `/nova` endpoint

### ISSUE THREAD

**Issue by rbren** [artifacthub/hub#3719]
**Is your feature request related to a problem? Please describe.**
Hi! I'm a maintainer of [nova](https://github.com/FairwindsOps/nova/), a utility for managing helm charts.

A while back Nova was DOSing artifact hub, so y'all were nice enough to create a data dump for us at `/nova`.

We're now looking to add functionality which tells you the kubeVersions compatible with the charts you have installed. But this info isn't currently available in the `/nova` endpoint

**Describe the solution you'd like**
Add `kubeVersion` to the `versions` array

**Describe alternatives you've considered**
We could maybe add a flag that uses the raw endpoints for people who need this functionality. But we want it to be on by default, and regardless we stand the risk of DOSing y'all again

**Additional context**
Here's the current structure of the `/nova` endpoint:
```json
[
    {
        "name": "lmutil",
        "description": "A Helm chart for Kubernetes",
        "latest_version": "0.1.9",
        "logo": "https://logicmonitor.github.io/helm-charts/lm_logo.png",
        "maintainers": [
            {
                "name": "LogicMonitor"
            }
        ],
        "repository": {
            "name": "logicmonitor-helm-charts",
            "url": "https://logicmonitor.github.io/helm-charts",
            "verified": true
        },
        "versions": [
            {
                "pkg": "0.1.1",
                "app": "1.16.0"
            },
            {
                "pkg": "0.1.2",
                "app": "1.16.0"
            },
            {
                "pkg": "0.1.4",
                "app": "1.16.0"
            },
            {
                "pkg": "0.1.5",
                "app": "1.16.0"
            },
            {
                "pkg": "0.1.9",
                "app": "1.16.0"
            }
        ]
    }
]
```

**Comment by tegioz** [comment]
Hi @rbren 👋

Done in #3721 🙂

The new field is named `kube`.

**Comment by rbren** [comment]
That was quick! Thanks a bunch @tegioz
