### ISSUE TITLE
Add support for designs from Meshery

### ISSUE THREAD

**Issue by ctcarrier** [artifacthub/hub#3720]
**Is your feature request related to a problem? Please describe.**
In Meshery, a Design describes all the resources and their properties that you want for a single deployment written in YAML based on Meshery’s declarative syntax.
[Meshery Designs](https://docs.meshery.io/concepts/logical/designs)

**Describe the solution you'd like**
We would like Meshery designs to be supported as an ArtifactHub kind.

**Describe alternatives you've considered**
NA

**Additional context**
This issue is to express interest in this integration from the Meshery side and get the ball rolling. I'm happy to support if there are any action steps necessary.

**Comment by tegioz** [comment]
Hi @ctcarrier 👋

Meshery designs would be a nice addition to Artifact Hub 🙂

Let me explain a bit how Artifact Hub indexes content.

Any organization or user can add repositories of any kind to Artifact Hub. These repositories are polled periodically and metadata is collected from them as needed.

Depending on the repository kind, metadata is extracted one way or another. To keep AH as simple to maintain and extend as possible, we are trying to push our generic tracker as the recommended way to go whenever possible (actually most artifacts kinds supported use it).

This generic tracker relies on a [custom metadata file](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml) and a [flexible directory structure](https://artifacthub.io/docs/topics/repositories/#kubewarden-policies-repositories) that supports one or more packages per repository, including multiple versions per package if needed. Data unique to the artifact kind can be added in the form of [custom annotations](https://artifacthub.io/docs/topics/annotations/keptn/). 

Some examples of how other projects organize the Artifact Hub metadata for their artifacts (they can be quite helpful for inspiration 😇):

- Kubewarden: <https://github.com/kubewarden/allowed-fsgroups-psp-policy>
- Keda: <https://github.com/kedacore/external-scalers/tree/main/artifacthub>
- Keptn: <https://github.com/keptn-contrib/artifacthub>
- Tinkerbell: <https://github.com/tinkerbell/hub/tree/artifacthub-manifests/actions>
- Gatekeeper: <https://github.com/open-policy-agent/gatekeeper-library/tree/master/artifacthub>

Could you please setup one repository with Meshery designs (one or more designs on it, as you prefer) based on the documentation referenced above? It doesn't have some be something final, so it's ok if it isn't perfect (although it'd be great if you could add a minimal README file for each package). Related to this sample repository, do designs use a single `yaml` file or multiple? It could be interesting to reference this file from the AH UI, or even consider displaying its contents at some point. So it'd be great if we could rely on some convention to locate it (i.e. a recommended file name, suffix, prefix, etc).

Please let us know if you have any questions! 🙂

**Comment by aabidsofi19** [comment]
@ctcarrier  @tegioz  is the package metadata needed for every design that needs to be published to artifact hub or  only for the  design kind itself .

**Comment by tegioz** [comment]
For every design published on Artifact Hub @aabidsofi19

**Comment by ctcarrier** [comment]
@tegioz Sample repo with a single design is up here: https://github.com/meshery/schemas/tree/master/artifacthub

**Comment by tegioz** [comment]
Thanks @ctcarrier! We expect to add support for Meshery designs this week 🙂

**Comment by tegioz** [comment]
This is ready @ctcarrier @leecalcote 🙂

You can see it in action in the staging environment, we'll deploy it to production soon.

<https://staging.artifacthub.io/packages/search?kind=24>
<https://staging.artifacthub.io/docs/topics/repositories/meshery-designs/>

We've created [a fork of the repository you shared](https://github.com/tegioz/meshery-schemas) to test it. Feel free to experiment with your own repositories if you'd like.

Closed by #3746
