### ISSUE TITLE
How to upgrade from 20.0.0 to 27.1.2

### ISSUE THREAD

**Issue by shifeichen** [artifacthub/hub#3724]
1.bitnami kafka structure changed, old is default for zookeeper, new is controller
2.when I upgrade it , it displays some error about format
3.I don't know how to set to the old format in new charts.

are there any solutions for this?

**Comment by shifeichen** [comment]
https://github.com/bitnami/containers/tree/main/bitnami/kafka

**Comment by shifeichen** [comment]
![image](https://github.com/artifacthub/hub/assets/33510601/c475be9f-90da-473a-a89f-04458eec7241)

**Comment by tegioz** [comment]
Hi @shifeichen 👋

For issues with the content listed on artifacthub.io it's best to contact the particular project directly. In the links section of the right panel in the package view you usually may find some links that can point you to the project's repository or the maintainers emails.

Hope this helps 🙂
