### ISSUE TITLE
Accidental misspelling of "Meshery" in plural form

### ISSUE THREAD

**Issue by leecalcote** [artifacthub/hub#3757]
**Describe the bug**

The "Meshery Designs" artifact kind is missing a "y" in the plural form of its name.

<img width="722" alt="Screenshot 2024-04-10 at 11 00 38 AM" src="https://github.com/artifacthub/hub/assets/7570704/98d6e95e-a898-488d-a84f-7c14d97666c6">

**Expected behavior**
Should be "Meshery designs" with a "y".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by tegioz** [comment]
Thanks @leecalcote!

Closed by #3777
