### ISSUE TITLE
[OFFICIAL] jaeger and jaeger-operator

### ISSUE THREAD

**Issue by jkowall** [artifacthub/hub#3787]
- **Repository name** *(in `artifacthub.io`)*: jaeger, jaeger-operator
- **Official packages** *(leave empty if all packages in the repository are official)*: jaeger, jaeger-operator
- **Project URL:** https://jaegertracing.io
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):**  Graduated
- **Source code URL** *(if available)*:  https://github.com/jaegertracing
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

As I mentioned we have two repositores we want on Artifact Hub, this is just an attempt to make them official. Thanks for the great support @tegioz and the awesome projects you work on.

**Comment by tegioz** [comment]
Done!
