### ISSUE TITLE
Loki datasource not able to use in grafana  9.5< - default grafana image tag is 10.3.3 - incorrect

### ISSUE THREAD

**Issue by wwojciechp** [artifacthub/hub#3802]
When loki is imported as a data source into Grafana in versions higher than 9.5. the following error is received: 

`parse error at line 1, col 3: syntax error: unexpected IDENTIFIER, expecting = or =~ or !~ or !`

When we run the chart with the flag, the loki is not imported correctly and does not display the data `--set grafana.enabled=true`

Chart version: 2.10.2

https://artifacthub.io/packages/helm/grafana/loki-stack

How to reproduce the problem:

Go to: 

![2024-05-09_21-44](https://github.com/artifacthub/hub/assets/102974359/c4fb6478-f888-4156-ad26-d381ac430918)

Then test connection, in logs we can see:

![2024-05-09_21-45](https://github.com/artifacthub/hub/assets/102974359/74602c3b-c5ec-4a45-a846-697c691c0b09)

When I replaced loki tag to 2.9.8 it works fine, by default loki tag in chart is 2.6.1, this version was released in July 2022, that is pretty old.

**Comment by tegioz** [comment]
Hi @wwojciechp 👋 

For issues with the content listed on [artifacthub.io](http://artifacthub.io/) it's best to contact the particular project directly. In the links section of the right panel in the package view you usually may find some links that can point you to the project's repository or the maintainers emails.

Hope this helps 🙂
