### ISSUE TITLE
Support for GitLab CI pipelines

### ISSUE THREAD

**Issue by d3adb5** [artifacthub/hub#3803]
**Is your feature request related to a problem? Please describe.**
I'd love for Artifact Hub to have support for GitLab CI pipelines as well, so that I wouldn't have to rely on both the GitLab CI Catalog and Artifact Hub to have an easy time going over the tooling in the company I work for.

**Describe the solution you'd like**
Support is added for GitLab CI pipelines, with a way to document inputs, environment variables, etc.

**Describe alternatives you've considered**
Relying on the GitLab CI/CD Catalog on the side.

**Additional context**
In my company we have reusable GitLab CI pipelines that can be used to compose another pipeline or used as-is by projects within the company. I'd love to have a place for these next to the container images and Helm charts we use.

**Comment by tegioz** [comment]
Hi @d3adb5 👋

We are always open to add support for new packages kinds, but please note that Artifact Hub currently only supports vendor neutral artifacts. Everything listed is currently in a foundation and not attached to a single vendor. If/when this is the case for GitLab CI pipelines, we’d be happy to consider it 🙂
