### ISSUE TITLE
[ABUSE-REPORT] CNCF org

### ISSUE THREAD

**Issue by codespearhead** [artifacthub/hub#3820]
**Describe the problem**

[This CNCF organization on ArtifactHub](https://artifacthub.io/packages/helm/cncf/gitlab) is probably a case of brandjacking. There are packages with the name of big open-source projects published by it there

I couldn't find anything about it with Google other than this [GitHub Organization](https://github.com/cncfvip) (here's the [official CNCF GitHub Organization](https://github.com/cncf)), which is virtually empty and describe themselves as the "Cloud Native Computing Foundation VIP Service Team", and [this domain](https://cncf.vip/).

![protential cncf scam gh org](https://github.com/artifacthub/hub/assets/72931357/f15ebaec-e96d-4ed9-a5c0-0b5113497dff)
![protential cncf scam site](https://github.com/artifacthub/hub/assets/72931357/e3d416db-4aad-4d1a-829e-cc35b09efcae)

**Comment by tegioz** [comment]
Thank you very much for reporting this @codespearhead!

The repository published by that organization has been temporarily suspended and the organization has been renamed. We've also reserved the CNCF organization name so that it cannot be taken again.
