### ISSUE TITLE
[OFFICIAL] Tika

### ISSUE THREAD

**Issue by lewismc** [artifacthub/hub#3823]
- **Repository name** *(in `artifacthub.io`)*: tika
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://tika.apache.org
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/apache/tika.git
- **Other relevant URLs:** https://github.com/apache/tika-helm

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ ]The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status. Currently working on this
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by lewismc** [comment]
I’ve added the artifactID to the source repository but it is still not indicating as verified.

**Comment by tegioz** [comment]
Hi @lewismc 👋

The repository metadata file doesn't seem to be ready yet (it should be available at <https://apache.jfrog.io/ui/native/tika/artifacthub-repo.yml>, at the same level as the charts `index.yaml` file). Please see the [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) section of the repositories guide for more details.

Also, could you setup an organization in Artifact Hub (i.e. Apache Tika) and transfer this repository to it? There are some other Apache official repositories like Airflow or Solr that are doing it that way 🙂

Thanks!

**Comment by tegioz** [comment]
Please let us know if you need any help with this @lewismc 🙂

**Comment by lewismc** [comment]
thank you Sergio. I am on vacation and will attend to this when I return on
July 8th. Thanks for your patience.

**Comment by tegioz** [comment]
Will close this issue for now, please feel free to reopen when the repository is ready for review 🙂
