### ISSUE TITLE
[ABUSE-REPORT] Repository or package name

### ISSUE THREAD

**Issue by ep4sh** [artifacthub/hub#3841]
**Describe the problem**
This repository is deprecated. Please remove it / apply deprecation notice

**Additional context**
https://community.grafana.com/t/difference-between-helm-charts-loki-and-loki-stack/87380/3

**Comment by tegioz** [comment]
Hi @ep4sh 👋

Could you please raise an issue in the source repository of the charts you think should be deprecated? We cannot mark as deprecated charts published by other organizations or users, only them can do it.

Thanks! 🙂
