### ISSUE TITLE
[OFFICIAL] `deepgram-self-hosted`

### ISSUE THREAD

**Issue by bd-g** [artifacthub/hub#3847]
- **Repository name**: `deepgram-self-hosted` (Deepgram Self-Hosted)
- **Project URL:** https://artifacthub.io/packages/helm/deepgram-self-hosted/deepgram-self-hosted
- **Is the publisher a CNCF project?:** *No*
- **Source code URL**: https://github.com/deepgram/self-hosted-resources for Helm chart. Source code for containers is closed-source.
- **Other relevant URLs:** Source code repo is hosted in official Deepgram GitHub organization, and links to official <https://deepgram.com> website in several locations.

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @bd-g 👋

Could you please create an organization in Artifact Hub (i.e. Deepgram, or whatever you think fits best) and transfer the repository to it? We usually recommend official packages that belong to an organization to be published under that org in Artifact Hub. This is helpful for final users when deciding among multiple options, and allows you to invite other project's members to the organization if you'd like.

Thanks!

**Comment by bd-g** [comment]
The package is already owned by an organization! 😃 It is under the Deepgram organization on ArtifactHub currently.

**Comment by tegioz** [comment]
Cool! The package is now marked as official 🙂
