### ISSUE TITLE
Encoding issues on all charts

### ISSUE THREAD

**Issue by ChillarAnand** [artifacthub/hub#3886]
**Describe the bug**

Some weird characters are being added at the end of all charts which is causing issue with installations.

<img width="1278" alt="Screenshot 2024-06-21 at 19 34 57" src="https://github.com/artifacthub/hub/assets/4463796/7a0b8049-e3fa-4d1d-8616-af0f13e6443f">

**To Reproduce**

Select any package.
Go to values.
Scroll to bottom.

**Expected behavior**
No weird characters should be there.

Related issue: https://github.com/headlamp-k8s/headlamp/issues/2058

**Comment by tegioz** [comment]
Fixed by #3895

We've just deployed the fix, but it can take up to 24 hours for cached `values.yaml` files to be refreshed.
