### ISSUE TITLE
Add support for Radius Recipe repositories

### ISSUE THREAD

**Issue by willtsai** [artifacthub/hub#3887]
**Is your feature request related to a problem? Please describe.**
[Radius](https://radapp.io/) is a cloud native application platform. It enables developers and IT operators to collaborate on delivering and managing cloud-native applications. One of the key features is Recipes, which allow infrastructure to be preconfigured and packaged that enables a separation of concerns between IT operators and developers by automating infrastructure deployment. Users may leverage community contributed repositories and registries that house Recipes for them to use off the shelf, e.g. [radius-project/recipes](https://github.com/radius-project/recipes). We would like Artifact Hub to support listing of Radius Recipes to help users discover deployment Recipes that they may use.

**Describe the solution you'd like**
Recipes can be written in Terraform (pushed to git repos) or Bicep (published to OCI registries), so we would like to be able to list these in Artifact Hub.

**Describe alternatives you've considered**
So far we've only listed available recipes in the Radius community [recipes](https://github.com/radius-project/recipes) repo, but it would be great to list other recipe repositories in one place. We've considered adding these listings to our documentation, but that is not self-service and thus unsustainable going forward.

**Additional context**

**Comment by tegioz** [comment]
Hi @willtsai 👋

Radius recipes would be a nice addition to Artifact Hub 🙂

We'll look into it and get back to you!
