### ISSUE TITLE
RSS broken

### ISSUE THREAD

**Issue by Aboitier** [artifacthub/hub#3899]
**Describe the bug**
I use the RSS feature from ArtifactHub to be informed about new releases. It is now broken because of a random character at the end of the XML tag.

When I visit the following URL, I get : https://artifacthub.io/api/v1/packages/helm/grafana/promtail/feed/rss

```
Erreur d’analyse XML : mal formé
Emplacement : https://artifacthub.io/api/v1/packages/helm/grafana/promtail/feed/rss
Numéro de ligne 951, Colonne 7 :
</rss>￿
------^
```

**Comment by tegioz** [comment]
Could you please check if it's working for you now @Aboitier?

**Comment by Aboitier** [comment]
Yup it's back on track. Thanks for the quick fix (and the amazing website!)
