### ISSUE TITLE
[OFFICIAL] arvancloud-webhook

### ISSUE THREAD

**Issue by mhkarimi1383** [artifacthub/hub#3912]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: arvancloud-webhook
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://github.com/ParminCloud/arvancloud-certmanager-issuer
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/ParminCloud/arvancloud-certmanager-issuer
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @mhkarimi1383 👋

I'm not sure if the official status applies to this case. For a package named `arvancloud-webhook` to be marked as official, it should be published by the ArvanCloud organization (unless ParminCloud was the owner of ArvanCloud, for which I haven't been able to find any reference).

Hope this makes sense 🙂

**Comment by mhkarimi1383** [comment]
Hi @tegioz 
Thanks
We have only created this project to work with ArvanCloud services
So I think this is not possible, thanks again

**Comment by tegioz** [comment]
I understand, no problem 👍

Thanks for understanding!
