### ISSUE TITLE
Table formatting

### ISSUE THREAD

**Issue by superbeagle** [artifacthub/hub#3917]
**Is your feature request related to a problem? Please describe.**
Depending the the size of a table in a screen of a package, horizontal scroll bars appear and I cannot see all of the information in a single row.

**Describe the solution you'd like**
Is there a way to force the table (configurable) to text wrap (among other options) to avoid having to go to the bottom of the table to scroll left or right and then having to scroll back up to view relevant information. 

**Describe alternatives you've considered**
Perhaps expanding the viewport/window?

**Additional context**
A example screen shot:
![image](https://github.com/artifacthub/hub/assets/6125731/5eb18686-3552-477a-8f65-6375d863b912)

**Comment by superbeagle** [comment]
In this example I would like to word wrap the center column to avoid either the left or right columns from being cut off.

**Comment by tegioz** [comment]
Hi @superbeagle 👋

This is something tricky to fix 😅

Text wrapping should happen automatically whenever *it is possible*. The problem usually is that in one or more columns there is a value that cannot be split automatically (i.e. a large string with no spaces or hyphens -maybe a url or a piece of json-). In those cases, the width of the column is adjusted to the length of that value. When this happens in multiple columns, or a very large value appears in one of the columns, some additional space may be needed and the horizontal scroll appears.

This is something pretty common in other sites as well, like in GitHub:

*(some examples of the same content rendered in Artifact Hub and GitHub)*

- Sample 1: [Artifact Hub](https://artifacthub.io/packages/helm/argo-cd-oci/argo-cd#option-2---redis-ha) - [GitHub](https://github.com/argoproj/argo-helm/blob/511d0d0adcedc61701f6abdbe5a6699b3d2d9e65/charts/argo-cd/README.md#option-2---redis-ha)

- Sample 2: [Artifact Hub](https://artifacthub.io/packages/helm/grafana/grafana#configuration) - [GitHub](https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md#configuration)

The main difference is the font size, but the behavior is quite similar in both cases as you can see. Unfortunately I'm not sure if there is anything we can do on our side to improve this. Leaving spaces in the text whenever possible would be helpful (i.e. in json snippets), but this ultimately depends on publishers and there may be cases where it won't be possible (i.e. some urls).

I hadn't realized how painful could this be when you have to scroll down to the bottom of the table to find the horizontal scroll bar TBH (I use a trackpad and I guess I instinctively move horizontally whenever this happens on any site). IIRC I think it's possible to scroll horizontally with any mouse if you hold down the shift key and move the scroll wheel up and down. I understand this is not the solution you were looking for, but maybe it could help a bit 😇

**Comment by tegioz** [comment]
Will close this issue for now, please feel free to reopen if needed 🙂
