### ISSUE TITLE
[OFFICIAL] OpenCost Helm charts

### ISSUE THREAD

**Issue by mattray** [artifacthub/hub#3919]
Could we please make these "Official" on behalf of the CNCF OpenCost project?

- **Repository name** *OpenCost*
  - https://artifacthub.io/packages/helm/opencost/opencost
  - https://artifacthub.io/packages/helm/opencost-oci/opencost
- https://opencost.io
- Sandbox project
- https://github.com/opencost/opencost-helm-chart/
- https://github.com/opencost/

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Hi @mattray 👋

We've just marked the first one as official. Could you please obtain the verified publisher status for the [second repository](https://artifacthub.io/packages/helm/opencost-oci/opencost) as well?

Thanks!

**Comment by asdfgugus** [comment]
opencost-oci repository is now verified as well! 
<img width="594" alt="image" src="https://github.com/user-attachments/assets/6b4a9b8e-6002-46e8-8247-9388e5712a26">
src: https://artifacthub.io/packages/helm/opencost-oci/opencost
ping @tegioz

**Comment by tegioz** [comment]
It's been marked as official as well 🙂
