### ISSUE TITLE
Tracker process hangs on Docker for Mac (M2)

### ISSUE THREAD

**Issue by cgetzen** [artifacthub/hub#3921]
**Describe the bug**

**To Reproduce**
1. Adjust config logger to debug
2. `docker run -it artifacthub/tracker:v1.19.0`

This also doesn't work in Kubernetes for Mac.

There is no output, so it is hanging before the first line of printing.

**Expected behavior**
Tracker runs on Mac M-series.

**Comment by zzhanabek** [comment]
@cgetzen 
set `DOCKER_DEFAULT_PLATFORM="linux/amd64"` as ENV for your docker

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂

**Comment by cgetzen** [comment]
Confirming that building it locally worked, thanks for the tip!
