### ISSUE TITLE
[OFFICIAL] gocd helm charts

### ISSUE THREAD

**Issue by chadlwilson** [artifacthub/hub#3932]
- **Repository name** *(in `artifacthub.io`)*: `gocd`
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://www.gocd.org/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/gocd/gocd
- **Other relevant URLs:**
    - Helm charts source: https://github.com/gocd/helm-chart 
    - Repo on ArtifactHub: https://artifacthub.io/packages/search?repo=gocd&sort=relevance&page=1
    - Helm install instructions pointing to this repo: https://www.gocd.org/download/#helm
    - Official website source: https://github.com/gocd/www.go.cd/

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by tegioz** [comment]
Done!

**Comment by chadlwilson** [comment]
Thanks, looks good!
