### ISSUE TITLE
Pagination-Total-Count Header Inaccessible in API Response Headers

### ISSUE THREAD

**Issue by vyncent-t** [artifacthub/hub#3933]
Hello!

I am working on a feature for the Headlamp project that filters Helm charts and uses the Pagination-Total-Count response header to manage page navigation in the UI. Recently, although I can see the Pagination-Total-Count header in the Network tab using Google Chrome's inspect tool, I am unable to access it programmatically in my application.

Has there been any recent change in how the Pagination-Total-Count header is exposed in the API responses?

If there has been a change, how can I programmatically access the total count for Helm charts that match the specified parameters? The current facets objects only return the total number of all existing Helm charts, which does not work well for this feature.

**Steps to Reproduce**

- Make a request to the ArtifactHub API with filters for Helm charts.
- Observe the response headers in the Network tab of Google Chrome's inspect tool for the presence of Pagination-Total-Count.
- Attempt to access the Pagination-Total-Count header programmatically.
**Example**

![image](https://github.com/artifacthub/hub/assets/78232183/58c44cbd-0457-4d00-a185-76c9d013898c)

![image](https://github.com/artifacthub/hub/assets/78232183/6967dbab-e0e3-4b8b-bdcc-5a8c0a71e001)

-   **Use Case:** Using the Pagination-Total-Count header to handle page navigation
-   **Observed Behavior:** The Pagination-Total-Count header is visible in the Network tab but is not accessible in the application
-   **Expected Behavior:** The header should be accessible programmatically and provide the total count of Helm charts matching the specified parameters (e.g., kind, CNCF, etc.)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux / Windows
 - Browser: chrome
 - Version: v1.19.0

**Comment by illume** [comment]
This is a CORS issue. Browsers only allow a small set of simple headers by default.

To enable access to `Pagination-Total-Count` from the browser, hub would need to add this header to an allow list:
```
Access-Control-Expose-Headers: Pagination-Total-Count
```

See Access-Control-Expose-Headers docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

**Comment by vyncent-t** [comment]
Apologies for not including the specific URL, the feature I been working on uses an integration endpoint mentioned above, mostly the [packages/search endpoint](https://github.com/artifacthub/hub/issues/3933). 

`https://artifacthub.io/api/v1/packages/search?kind=0&ts_query_web=&sort=relevance&facets=true`

**Comment by illume** [comment]
> Hi! 👋
> 
> Please note that we only have CORS enabled for the endpoints needed to power the [widgets feature](https://artifacthub.io/docs/topics/embedding_artifacts/). The one used to search packages is one of them, for example (I assume this is the one you're using). But most won't work as expected from the browser. It is setup this way intentionally as an additional measure to prevent potential abuse and overload.
> 
> We also have some rate limits in place that vary from time to time depending on usage patterns (we need to make sure artifacthub.io works fine 😉). I would recommend you to take a look at the [integrations endpoints available](https://artifacthub.io/docs/api/), just in case any of them help. They allow you to fetch some information from all charts available in a single request, without running into rate limits problems.
> 
> <img alt="integrations" width="1464" src="https://private-user-images.githubusercontent.com/1213902/347455574-ef6185e9-a94d-468e-83ce-4aa509bcf232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDUzNzIsIm5iZiI6MTcyMDcwNTA3MiwicGF0aCI6Ii8xMjEzOTAyLzM0NzQ1NTU3NC1lZjYxODVlOS1hOTRkLTQ2OGUtODNjZS00YWE1MDliY2YyMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTMzNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjY1NWI1MTQzNWViM2NlZmNjNDMwNGIwYWI2OWIwYTI5YzlhODVkMDU4YTIxMGM5OWU3NjczOTY0Yjc3OWE1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D3FVohjG7ysuB9QIgfzY9C6xWkAQedF8yy1pO3NvAR4">
> Hope this helps 🙂


Hi,

thanks for the info. That is helpful.

We'd ultimately like to reduce load on artifacthub, and use the API in a way that is best. So your guidance is helpful :)

I'm still not clear on the best way for us to use the API to search. I've written some more information, and then below are the ways forward I can see. Perhaps you could let us know your preference for what is the best way for us to proceed for artifacthub?



### more info about Headlamps usage

Headlamp runs as an electron web app, and the requests are made by people running their app.

We need to search more than just helm charts for Headlamp. So far there are artifact hub integrations ongoing with helm/headlamp/inspektor gadget artifact types. With krew/open cost/backstage being likely in the near future. If we were to go the direction of downloading all of the package data we'd need a way to download other types as well. It looks like only 3 types of packages are available for export so far?

Without the search API, downloading all the 14,000 helm packages would probably transfer more than a typical search session of 1-5 pages worth of data. Additionally, without the search API, we would need to reimplement the search API locally.

**Regarding rate limits**. Probably a typical client would make 1-20 search requests in a session. As I mentioned before searching for packages is not something people do frequently. We don't have so many users now, but it's possible that could change in the future. Installing packages/plugins should be a fairly infrequent activity. So I don't expect much load for each client.

An alternative is that we could call the API without the browser using a proxy server. Headlamp has a daemon server process to do tasks like this. So the browser would talk to it, and the headlamp-server would allow the Pagination-Total_Count header (or return the count in its own structure).


### which way is best for artifacthub?

I'd be interested in your guidance of which way would be more acceptable for artifacthub.

1) Add the header to the search route "Access-Control-Expose-Headers: Pagination-Total-Count"
2) Use a proxy server to call the API to access the page count
3) Use an exporter. Which would involve creating a new API to export data other than Helm (which seems to be what you can export so far). It would also mean we'd need to create a search implementation ourselves. Clients would need to download more data to do a search.

Or maybe there's some other way?

**Comment by tegioz** [comment]
Thanks for the context! 🙂

We'd rather not to encourage the use of the API directly from browsers, so we'd prefer not to expose that header or enable CORS for more endpoints at the moment.

If the number of expected requests is low, option **2** would be fine. Search requests can be expensive, and we keep a close eye on them to block / rate limit those that may affect the normal operation of our services. So the problem going this way is that if the tool / feature becomes very popular, or there is some accidental misuse of the API, we may be forced to make some changes that may end up affecting your users. Unfortunately this has already happened a few times ([[1]](https://github.com/FairwindsOps/nova/issues/214#issue-1697276674), [[2]](https://github.com/sstarcher/helm-exporter/pull/66#issuecomment-916836882), [[3]](https://github.com/artifacthub/hub/issues/997)). It's also important to keep in mind that in that case, the proxies will be more likely to be rate limited, as some of the limits are based on the source IP.

Option **3** is usually the best for us, but it may depend on the information you need for each package. The integration endpoints I shared export a minimal subset of data for each package, which is fine, even if it was for all package kinds. But if you need a lot of data for each package this may not be the best way to proceed. I understand this way adds more work on your side, but it's also probably more likely to work reliably over time regardless of the growth.

**Comment by tegioz** [comment]
> But if you need a lot of data for each package this may not be the best way to proceed.

If that's the case, an alternative would be to collect the information you need periodically on your backend using any API endpoints you need, and serve it to your clients the best way you see fit. If you reach any rate limit you can always slow your process down a bit to avoiding hitting it.

Let us know if you need anything else, we'd be happy to help 🙂

**Comment by tegioz** [comment]
Will close this issue for now, please feel free to reopen if needed 🙂
