### ISSUE TITLE
[OFFICIAL] Penpot

### ISSUE THREAD

**Issue by bameda** [artifacthub/hub#3952]
- **Repository name** *(in `artifacthub.io`)*: penpot
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://penpot.app
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/penpot
- **Other relevant URLs:**
  - Helm repository code: https://github.com/penpot/penpot-helm
  - The company behind penpot: https://kaleidos.net/   

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!

**Comment by bameda** [comment]
How fast!! Thank you very much, @cynthia-sg :heart_hands:
