### ISSUE TITLE
[OFFICIAL] MapTiler - MapTiler Server

### ISSUE THREAD

**Issue by MartinMikita** [artifacthub/hub#3985]
- **Repository name** *(in `artifacthub.io`)*: [maptiler](https://artifacthub.io/packages/helm/maptiler/maptiler-server)
- **Official packages**: 
- **Project URL:** https://www.maptiler.com/server/
- **Is the publisher a CNCF project?** no
- **Source code URL** *(if available)*: no
- **Other relevant URLs:** 

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
