### ISSUE TITLE
[OFFICIAL] telepresence-oss

### ISSUE THREAD

**Issue by thallgren** [artifacthub/hub#3986]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: telepresence-oss
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://www.telepresence.io/ and https://github.com/telepresenceio/telepresence
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Yes, telepresence is a CNCF sandbox project
- **Source code URL** *(if available)*: https://github.com/telepresenceio/telepresence
- **Other relevant URLs:** *if there are any other urls that can help us with the verification process, please include them here*

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Hi @thallgren  👋

Could you please create an organization in Artifact Hub (i.e. Telepresence, or whatever you think fits best) and transfer the repository to it? We usually recommend official packages that belong to an organization to be published under that org in Artifact Hub. This is helpful for final users when deciding among multiple options, and allows you to invite other project's members to the organization if you'd like.

Thanks!

**Comment by thallgren** [comment]
Hi @cynthia-sg. I did create a "Telepresence at CNCF" organization earlier. If possible, I'd like that to be used here. I can see it in my control panel, but I'm not able to see it anywhere else (or obtain a link to it).

**Comment by tegioz** [comment]
Hi @thallgren

If you've already created a Telepresence organization in Artifact Hub, you can transfer your repository to it from the control panel.

In the list of repositories in the control panel, you should see a card for each one you have. In the top right corner of the card, you'll find a button with three dots. If you click on it, you should see an option named transfer. In the next step, you should be able to transfer the repository to any organization you are a member of.

In a few minutes the transfer should be complete 🙂

**Comment by thallgren** [comment]
Hi @tegioz , I successfully transfered the telepresence-oss repository to the Telepresence at CNCF organization.

**Comment by tegioz** [comment]
Awesome! The package has been marked as official.

I've noticed that there is [another Telepresence package listed in Artifact Hub](https://artifacthub.io/packages/helm/datawire/telepresence), which looks like if it was the "official" until now. Please note that it's possible to [claim the ownership of a repository](https://artifacthub.io/docs/topics/repositories/#ownership-claim). One of the benefits of doing this over creating a new one is that content like stars, users subscriptions, etc, is preserved. Another benefit is that there are also fewer alternatives for the same package, making it less confusing for users (i.e. now they'll need to pick one option among the one marked as official and the one with more stars, which seems more popular).

If you decide to change course and recover the other one we'll need to assign the official status again. But that's fine, so don't worry 🙂

**Comment by tegioz** [comment]
Thanks for the explanation, makes sense! 👍

It's OK to have multiple options for a given package, sometimes it's needed. I was only concerned with the possibility that there were two copies of the same chart. But it's all clear now 🙂
