### ISSUE TITLE
NetScaler ingress controller version 2.0.6 is not updated in Artifact hub

### ISSUE THREAD

**Issue by subashd** [artifacthub/hub#4001]
### Discussed in https://github.com/artifacthub/hub/discussions/4000

<div type='discussions-op-text'>

<sup>Originally posted by **subashd** August 20, 2024</sup>
HI Team,
We have released NSIC version 2.0.6 helm chart today, but it is not getting updated in the artifacthub.
Could you please help us on this ?

gh-pages: https://github.com/netscaler/netscaler-helm-charts/tree/gh-pages
index.yaml: https://github.com/netscaler/netscaler-helm-charts/blob/gh-pages/index.yaml
Helm Repo: https://github.com/netscaler/netscaler-helm-charts/
</div>

**Comment by tegioz** [comment]
I've just replied in the discussion. Will close this one, no need for both 🙂
