### ISSUE TITLE
[OFFICIAL] ReportPortal

### ISSUE THREAD

**Issue by hlebkanonik** [artifacthub/hub#4036]
In Artifact Hub, the `official` status means that the publisher **owns the software** a package primarily focuses on. If we consider the *example* of a [chart used to install Consul](https://artifacthub.io/packages/helm/hashicorp/consul), to obtain the `official` status the publisher should be the owner of the Consul software (*HashiCorp* in this case), not just the chart. Similarly, a [Tekton task used to perform operations on Google Cloud](https://artifacthub.io/packages/tekton-task/tekton-catalog-tasks/gcloud) would need to be published by *Google* to be marked as `official`. In the case of a MySQL operator, only one published by *MySQL/Oracle* would be considered `official`.

The `official` status can be granted at the **repository or package level**. When it is granted for a repository, all packages available on it will display the `official` badge, so all packages in the repository **must** be official. If only some of the packages in your repository are official, please list them in the `Official packages` field below.

- **Repository name** *(in `artifacthub.io`)*: https://artifacthub.io/packages/helm/reportportal-io/reportportal
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://github.com/reportportal/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/reportportal/service-api, https://github.com/reportportal/service-ui, https://github.com/reportportal/service-index, https://github.com/reportportal/service-jobs, https://github.com/reportportal/service-authorization, https://github.com/reportportal/migrations, https://github.com/reportportal/service-auto-analyzer
- **Other relevant URLs:** https://reportportal.io

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Hi @hlebkanonik ,

all packages must have a README.md file to be granted the official status. Could you please add it?

Therefore, could you please create an organization in Artifact Hub (i.e. Report Portal, or whatever you think fits best) and transfer the repository to it? We usually recommend official packages to be published under an organization in Artifact Hub. This is helpful for final users when deciding among multiple options, and allows you to invite other project's members to the organization if you'd like.

Thanks

**Comment by hlebkanonik** [comment]
Hi! Done.

**Comment by cynthia-sg** [comment]
Done!
