### ISSUE TITLE
[OFFICIAL] paradedb

### ISSUE THREAD

**Issue by philippemnoel** [artifacthub/hub#4048]
Hi everyone. Thank you for considering our project!

- **Repository name** *(in `artifacthub.io`)*: paradedb
- **Official packages** *(leave empty if all packages in the repository are official)*: N/A
- **Project URL:** https://github.com/paradedb/charts
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** No
- **Source code URL** *(if available)*: https://github.com/paradedb/paraededb
- **Other relevant URLs:** paradedb.com, docs.paradedb.com

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
