### ISSUE TITLE
[OFFICIAL] Add container/openproject as official package

### ISSUE THREAD

**Issue by oliverguenther** [artifacthub/hub#4053]
- **Repository name** *(in `artifacthub.io`)*: https://artifacthub.io/packages/container/openproject/openproject
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://openproject.org
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** no
- **Source code URL** *(if available)*: https://github.com/opf/openproject
- **Other relevant URLs:** We initially published only our helm charts, they are already official. https://artifacthub.io/packages/helm/openproject-helm-charts/openproject , we have now improved our display of container images

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
