### ISSUE TITLE
Tracking error getting tags

### ISSUE THREAD

**Issue by pat-s** [artifacthub/hub#4054]
A repo of mine (my first) is showing the following tracking issue:

```
error getting repository remote digest: GET https://codeberg.org/v2/devxy/shinyproxy-helm/tags/list?n=1000: NAME_UNKNOWN: 
```

It is hosted on Codeberg, which is using Forgejo under the hood. I don't think this should be an issue as other assets from Forgejo-based instances are hosted on Artifacthub.

Codeberg does not have a `/v2` endpoint, so I am wondering a bit where this call comes from and why other repos are not erroring. 

The helm package itself lives here: https://codeberg.org/devxy/-/packages/helm/shinyproxy/1.0.0

Any help is appreciated!

**Comment by pat-s** [comment]
Thanks for the help @tegioz!

Yes, I used `oci://codeberg.org/devxy/shinyproxy-helm` but it should in fact be `oci://codeberg.org/devxy/shinyproxy`. 

> I'm not familiar with Codeberg, but it looks like they also provide an OCI registry that you can push your images to (i.e. your Helm charts packages). 

Yes, my helm package is [already published](https://codeberg.org/devxy/-/packages/helm/shinyproxy/1.0.0) there (just again note that it used the wrong name until now). 

https://codeberg.org/api/packages/devxy/helm is an API URL which I would like to avoid. Codeberg provides different "package" types, among them "helm" and "container". Both should be OCI compliant. 

> another user who is publishing some Helm charts on Artifact Hub

Yes, thanks for the pointer. I was aware of it and the user is using the "container" package type. However, I'd like to use the "helm" package type instead of publishing a helm chart as a container. It might however be, that the "helm" type does not reply to the `v2/` API endpoint artifacthub is trying to query.

> most likely indicates the registry couldn't find a repository with that name, maybe because you haven't pushed anything to it yet.

It seems that the "helm" package type doesn't work with the API endpoint artifacthub is trying to query. Using the https variant works though!

And because the https one is not shown in the asset page, I am fine just sticking to this one 👍

**Comment by tegioz** [comment]
Awesome, I'm glad you got it working. And thanks for the explanation! 🙂
