### ISSUE TITLE
[OFFICIAL] favonia/cloudflare-ddns

### ISSUE THREAD

**Issue by favonia** [artifacthub/hub#4078]
- **Repository name**: favonia
- **Official packages**: cloudflare-ddns
- **Project URL:** https://github.com/favonia/cloudflare-ddns
- **Is the publisher a CNCF project?:** No
- **Source code URL** *(if available)*: https://github.com/favonia/cloudflare-ddns

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

Note: for the last requirement, after reading the [source code of Artifact hub](https://github.com/artifacthub/hub/blob/36823bf59afa8d3a1b4187dd093a48a69dcaec3c/internal/tracker/source/generic/generic.go#L222-L229), I believe I am okay with an explicitly specified README file. The file name of my README is not literally `README.md`.

**Comment by favonia** [comment]
That makes sense. Thanks for the checking.

**Comment by tegioz** [comment]
No problem, thanks for understanding!
