### ISSUE TITLE
Access by scanner failing for internal docker registry of jfrog

### ISSUE THREAD

**Issue by martinmlouis** [artifacthub/hub#4114]
**Describe the bug**
I tried a on-prem hosted artifacthub with images stored in a docker registry of jfrog. The scanner is failing with access issues even though specified docker credentials in the values.yaml

creds:
  dockerUsername: "xxxx"
  dockerPassword: "yyyy"

Error details are:

error scanning image [jfrog-platform.35.212.92.161.nip.io/docker-local/nginx:1.16.0](http://jfrog-platform.35.212.92.161.nip.io/docker-local/nginx:1.16.0): error running trivy on image [jfrog-platform.35.212.92.161.nip.io/docker-local/nginx:1.16.0](http://jfrog-platform.35.212.92.161.nip.io/docker-local/nginx:1.16.0): * remote error: GET [https://jfrog-platform.35.212.92.161.nip.io:443/artifactory/api/docker/null/v2/token?scope=repository%3Adocker-local%2Fnginx%3Apull&service=jfrog-platform.35.212.92.161.nip.io%3A443](https://jfrog-platform.35.212.92.161.nip.io/artifactory/api/docker/null/v2/token?scope=repository%3Adocker-local%2Fnginx%3Apull&service=jfrog-platform.35.212.92.161.nip.io%3A443): : Authentication is required (package nginx:0.1.0)

**Expected behavior**
Scanner runs successfully

**Comment by tegioz** [comment]
Hi @martinmlouis 👋

ArtifactHub does not support scanning images on private registries. The docker credentials are only used when pulling images from the Docker Hub, to avoid rate limiting issues.

**Comment by tegioz** [comment]
Will close this issue for now, please feel free to reopen if needed.
