### ISSUE TITLE
Webpage crashes when opening the "Default Values" popup

### ISSUE THREAD

**Issue by hongshaoyang** [artifacthub/hub#4145]
**Describe the bug**
https://artifacthub.io/packages/helm/apache-airflow/airflow?modal=values webpage crashes when opening the "Default Values" popup

**To Reproduce**
1. Go to https://artifacthub.io/packages/helm/apache-airflow/airflow
2. Click on "Default Values" on the right
3. Page crashes

**Expected behavior**
Page does not crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6.7 (22G720)
 - Chrome Version 130.0.6723.70 (Official Build) (arm64)

**Comment by tegioz** [comment]
Hi @hongshaoyang 👋

Thanks for reporting this issue!

We haven't been able to reproduce it so far (using the same browser version in macOS as well). Could you share any details available in the browser console? (errors, etc). Could you also try disabling all your extensions to see if that fixes the problem?

**Comment by tegioz** [comment]
Hi @hongshaoyang

Were you able to reproduce this problem after disabling all your extensions?

**Comment by hongshaoyang** [comment]
Disabling all extensions solved this issue. Thank you.

**Comment by tegioz** [comment]
Awesome, thanks 👍
