### ISSUE TITLE
bug: need to edit organization description for KubeStellar

### ISSUE THREAD

**Issue by clubanderson** [artifacthub/hub#4158]
**Describe the bug**
I created the organization KubeStellar. I added a description and accidentally left of the first letter. I dont see a way to edit it 

**To Reproduce**
1. Go to https://artifacthub.io/control-panel/organizations?page=1 (for me this is KubeStellar)
2. Description is missing the first letter "K"

**Expected behavior**
should be able to edit the description (or an admin can do it)

**Screenshots**
<img width="760" alt="Screenshot 2024-11-20 at 10 46 25 AM" src="https://github.com/user-attachments/assets/c9a8da1e-780f-4411-8316-e80fc2a4747c">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: safari

**Comment by tegioz** [comment]
Hi @clubanderson 👋

You can edit the description of your organization from the control panel (settings tab -> profile). You'll need to set the control panel context to the organization you'd like to edit in the top right corner.

**Comment by clubanderson** [comment]
ok - edited. Thank you.
