### ISSUE TITLE
[OFFICIAL] Federid

### ISSUE THREAD

**Issue by eminwux** [artifacthub/hub#4159]
- **Repository name** *(in `artifacthub.io`)*: federid
- **Official packages** *(leave empty if all packages in the repository are official)*: ...
- **Project URL:** https://federid.io
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** NO
- **Source code URL** *(if available)*: https://github.com/federid/federid

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [ X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X ] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
