### ISSUE TITLE
[OFFICIAL] TRISA Envoy

### ISSUE THREAD

**Issue by bbengfort** [artifacthub/hub#4160]
- **Repository name** *(in `artifacthub.io`)*: [trisacrypto](https://artifacthub.io/packages/helm/trisacrypto/envoy)
- **Official packages** *(leave empty if all packages in the repository are official)*: 
- **Project URL:** https://trisa.dev/
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** NO
- **Source code URL**: [github.com/trisacrypto/envoy](https://github.com/trisacrypto/envoy/)
- **Other relevant URLs:** [trisa.io](https://trisa.io/), [vaspdirectory.net](https://vaspdirectory.net/)

Rotational Labs is a member of the TRISA Working Group and has developed the TRISA protocol and TRISA Envoy Server on behalf of TRISA, a not-for-profit professional working group, as open source software. I am the lead developer and maintainer of these projects. 

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [x] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [x] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [x] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!
