### ISSUE TITLE
[OFFICIAL] Microcks official artifacts

### ISSUE THREAD

**Issue by lbroudoux** [artifacthub/hub#4174]
Hi there!

As the core maintainer of the [Microcks](https://microcks.io) CNCF project, I would like all the artifacts attached to the [`Microcks` org](https://artifacthub.io/packages/search?org=microcks&sort=relevance&page=1) in ArtifactHub to be tagged as `Official` ones.

Thank you very much!

- **Repository name** *(in `artifacthub.io`)*: Microcks
- **Official packages** *(leave empty if all packages in the repository are official)*:
- **Project URL:** https://microcks.io
- **Is the publisher a CNCF project? (graduated, incubating or sandbox):** Yes, CNCF sandbox
- **Source code URL** *(if available)*: https://github.com/microcks + many org repositories
- **Other relevant URLs:** https://www.cncf.io/projects/microcks/

**Before applying for this status, please make sure your repository complies with the following requirements:**

- [X] The repository has already obtained the [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) status.
- [X] The user requesting the status is the publisher of the repository in Artifact Hub, or belongs to the organization publishing it.
- [X] All official packages available in the repository provide a `README.md` file with some documentation that can be displayed on Artifact Hub.

**Comment by cynthia-sg** [comment]
Done!

**Comment by lbroudoux** [comment]
Hi @cynthia-sg, thanks for the update.

I saw it has been applied for the Helm chart (see https://artifacthub.io/packages/helm/microcks/microcks) but not for all the container images attached to the organization (see https://artifacthub.io/packages/container/microcks-image/microcks for example).

Is it possible to propagate the official badge to all our artifacts listed here: https://artifacthub.io/packages/search?org=microcks&sort=relevance&page=1

Also, I noticed that we also have a `CNCF` badge on the Helm chart. Could it be set on other artifacts as well?

Thanks!

**Comment by cynthia-sg** [comment]
Hi @lbroudoux,

could you please verify [this container](https://artifacthub.io/packages/container/microcks-ansible-operator-image/microcks-ansible-operator)?

Thanks.

**Comment by lbroudoux** [comment]
This is now fixed!

**Comment by cynthia-sg** [comment]
Done!
