### ISSUE TITLE
Requesting ownership of the OpenEBS ORG

### ISSUE THREAD

**Issue by tiagolobocastro** [artifacthub/hub#4191]
Hi, the current [OpenEBS maintainers](https://github.com/openebs/community/blob/HEAD/MAINTAINERS) were recently made aware of the [openebs project on artifact hub](https://artifacthub.io/packages/helm/openebs/openebs).
They were hoping we could update it since it's quite out of date.

There's a process in place to claim ownership of a repository (via the website) but there's no process of claiming ownership of an organization.

The existing artifact hub owners are not longer associated with the project, and worst of all with emails which are no longer active.
I was able to reach out to one of them but sadly he could not help for this reason (email not active).

Would it be possible to get this org transferred to current [OpenEBS maintainers](https://github.com/openebs/community/blob/HEAD/MAINTAINERS)?

Thank you

**Comment by tegioz** [comment]
Hi! 👋

@kmova at the moment you're the only member of the OpenEBS organization in Artifact Hub. It'd be great if you could invite @tiagolobocastro to it. Otherwise, do you have any objection to us taking care of this and inviting him?

Thanks!

**Comment by tegioz** [comment]
You've been invited to the OpenEBS organization in Artifact Hub @tiagolobocastro 🙂
