### ISSUE TITLE
Support Docker Compose

### ISSUE THREAD

**Issue by aabouzaid** [artifacthub/hub#4196]
**Is your feature request related to a problem? Please describe.**

As an upstream for some applications, I want to be able to publish Docker Compose on Artifact Hub to make it easier for users to find and install.

Docker Compose is supported by Docker CLI/Desktop and other tools like Podman CLI/Desktop.

**Describe the solution you'd like**

Support Docker Compose in Artifact Hub (or maybe a genetic YAML type).

**Describe alternatives you've considered**

Maybe Docker Compose files could be distributed as [OCI image](https://github.com/opencontainers/image-spec). However, I'm unaware of standard support for that in Docker Compose tools without external tools.

**Additional context**
N/A

**Comment by tegioz** [comment]
Hi @aabouzaid 👋

We are always open to add support for new packages kinds, but please note that Artifact Hub currently only supports vendor neutral artifacts. Everything listed is currently in a foundation and not attached to a single vendor. If/when this is the case for Docker Compose, we’d be happy to consider it 🙂

**Comment by aabouzaid** [comment]
Hi @tegioz :wave: 

Thanks for your reply. +1: 

I feel I don't get the point here :sweat_smile: 
For example, how is this compared to Helm for example? :thinking: 

Also, which `foundation` do you refer to? CNCF?

In all cases, are there any plans at least to provide a generic package regardless of the vendor?

**Comment by gokuldas** [comment]
@tegioz Compose is a [specification](https://compose-spec.io/) with [multiple implementations](https://github.com/compose-spec/compose-spec?tab=readme-ov-file#implementations), even though it's still often referred to as Docker compose. The real [Docker compose](https://github.com/docker/compose) (v2) is the reference implementation of that standard. It seems to be a [community project](https://compose-spec.io/#community), though I don't know what arrangement they have. Does that count?

**Comment by tegioz** [comment]
No worries! 🙂

@aabouzaid the Helm project was donated to the CNCF and it is vendor neutral. Artifact Hub focuses on Cloud Native artifacts, so most kinds supported are associated to projects that are part of the Cloud Native Computing Foundation. But there are some exceptions, like Tekton tasks, pipelines and step actions, provided by the Tekton project (which is part of the Continuous Delivery Foundation).

@gokuldas to add support for a Compose artifact kind, the specification would need to be a CNCF project. There are other [CNCF projects that provide specifications](https://landscape.cncf.io/?group=projects-and-products&view-mode=card&specification=true&project=cncf&classify=category&sort-by=name&sort-direction=asc#app-definition-and-development--streaming-messaging), like CloudEvents or OpenFeature.

[This Docker blog article](https://www.docker.com/blog/donating-docker-distribution-to-the-cncf/) (related to the donation of the Docker Distribution project) raises some very good points of why this requirement is important for the Artifact Hub project 😇

At the moment, we don't have plans to support a generic package kind, and we'll likely focus on artifacts related to CNCF projects (but open to exceptions like the Tekton case mentioned above, which is part of another Linux Foundation project).

Hope this makes sense 🙂

**Comment by aabouzaid** [comment]
@tegioz Clear, thanks for the clarification :+1: 

Would you like me to open a PR to document that?

**Comment by tegioz** [comment]
Thanks, but don't worry, we'll need to discuss this further before documenting it.

Will close this issue for now, feel free to reopen if the situation changes 🙂
