### ISSUE TITLE
helm chart download link changed and actual helm chart is not available

### ISSUE THREAD

**Issue by ashishmahamuni21** [artifacthub/hub#4205]
Helm chart is not able to download, it redirects to the oci://registry-1.docker.io/bitnamicharts/kafka:31.1.1

We are using kustomization to install such helm charts, where till the version 31.0.0, it worked as it downloads the helm chart from the repo: https://charts.bitnami.com/bitnami/kafka-31.0.0.tgz

After the version 31.1.0, the helm chart downloading is redirected to oci://registry-1.docker.io/bitnamicharts/kafka:31.1.0 where the actual Helm chart is not available, rather if i download it manually from https://charts.bitnami.com/bitnami/kafka-31.1.0.tgz, it worked :)

But due to kustomization, downloading the helm chart manually every time is not feasible.

**Comment by tegioz** [comment]
Hi @ashishmahamuni21 👋

Please see: <https://github.com/artifacthub/hub/issues/4172#issuecomment-2520421480>
