### ISSUE TITLE
Cannot add artifacthub-pkg.yml to OCI helm chart

### ISSUE THREAD

**Issue by MartinLoeper** [artifacthub/hub#4206]
**Describe the bug**
I try to add the `artifacthub-pkg.yml` but cannot make it work no matter what I try.
Is this supported? I am asking since it is not described in the [docs](https://artifacthub.io/docs/topics/repositories/helm-charts/).

I would like to customize my helm chart's artifact hub metadata. The chart is hosted on harbor via OCI.

**To Reproduce**
1. create helm chart containing `artifacthub-pkg.yml`
2. package and upload to harbor as oci
3. metadata from `artifacthub-pkg.yml` is not rendered on the artifact hub UI page for my chart

I was able to make both other features work: signing the helm chart and attaching `artifacthub-repo.yml` (verified publisher).

**Comment by MartinLoeper** [comment]
nevermind, looks like we are supposed to provide that metadata using [annotations in the Chart.yml file](https://artifacthub.io/docs/topics/annotations/helm/). So basically artifact hub sources all the metadata about the package from the Chart.yml file for OCI images.

**Comment by tegioz** [comment]
Hi @MartinLoeper 👋

Yes, in the case of Helm charts, Artifact Hub collects the metadata it needs from the repository's `index.yml` file, the chart's  `Chart.yml` file and some other files from the chart archive (i.e. json schema, values, etc). This applies to Helm charts hosted on OCI registries and plain http servers.

**Comment by MartinLoeper** [comment]
Thanks for giving an even more specific answer to my question @tegioz. That makes total sense now to me =)
