### ISSUE TITLE
Perform chart testing

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#535]
The chart used and shipped could have more extensive testing. For this I was thinking of the [chart testing](https://github.com/helm/chart-testing) project. This would enable us to add more typical CI testing to the chart, too.

I've been, also, wondering if the chart as a separate repo would make this easier.

**Comment by tegioz** [comment]
Thanks @mattfarina, that makes sense, I will look into it.

About having the chart as a separate repo: one thing I like about having it in the same one is that it makes it easier to keep the application code and the chart used to deploy it in sync.

**Comment by mattfarina** [comment]
@tegioz I was just wondering not saying it should be done. Everything is a trade-off.

**Comment by tegioz** [comment]
The part I meant to say I would look into it was the chart testing @mattfarina. The other comment was just to continue the conversation you brought up 😉

**Comment by scottrigby** [comment]
1. If we either move the chart to a separate git repo in the artifacthub gh org, or even move the hub github pages setting to a branch other than the main one, we can use the [@helm/chart-releaser-action](https://github.com/helm/chart-releaser-action) GitHub Action to automate the helm repo.
2. If we keep structure as-is, we can still use the [helm/chart-releaser](https://github.com/helm/chart-releaser) project, just with a custom script.

For either option we can also use the [@helm/chart-testing-action](https://github.com/helm/chart-testing-action) to wrap the chart-testing project @mattfarina mentioned above. Here's an demo repo to see how they work together: https://github.com/helm/charts-repo-actions-demo

Whichever option you decide I'm make a PR if it helps.

**Comment by tegioz** [comment]
Yes, that would help @scottrigby, thanks 👍

I'd prefer keeping the structure as it is for now if possible.
