### ISSUE TITLE
Enhancment: Add Support for OLM Catalog Index Image operator catalogs

### ISSUE THREAD

**Issue by cdjohnson** [artifacthub/hub#544]
Operator Lifecycle Manager is transitioning from a Git source-based approach at a OLM catalog to a container image approach.

IBM, for example, is hosting all of it's IBM Cloud Pak certified operators in one common catalog:
https://github.com/IBM/cloud-pak/blob/master/reference/operator-catalog-enablement.md

In an OLM-Enabled Kubernetes cluster, a customer can simply create a `CatalogSource` resource pointing to the Catalog Index Image, and the data is consumed by OLM and presented to the customer for use in the OpenShift GUI.

See the [operator-registry](https://github.com/operator-framework/operator-registry) git project for details on how the catalog index is built and used which includes the grpc APIs used to interact with the registry.

Two projects I'm aware of have cosumers for the catalogs:
1.  The [OLM package-server](https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/package-server) digests the catalogs into a unified view, converting the operators into `PackageManifest` resources.
1.  The OCP console UI also interacts with it, but I'm not sure how.  It "may" interact with the `PackageManifest` API.

**Comment by tegioz** [comment]
Hi @cdjohnson 

#852 has just been deployed. For more information please see: https://github.com/artifacthub/hub/blob/master/docs/repositories.md#olm-oci-experimental-support

You can now add your operators catalog if you wish so :) Please let me know if you run into any problems.
