### ISSUE TITLE
Verified publisher

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#550]
Please note that this is related somehow to #542, but it describes a different issue.

At the moment, any user or organization can add a repository, regardless if they own or have control over that content. The content in this case could be for example a Helm chart to deploy an application, not the application itself.

So I could, for example, add the Jetstack charts repository (https://charts.jetstack.io) which contains the cert-manager charts. I would appear as the publisher, potentially confusing users and maybe preventing the creators of that content to publish it themselves.

I think it's OK to allow this, as it may be helpful to have more content available sooner. But maybe we could mark repositories/packages which have been published by their owners with a special flag (something like `Verified publisher` ?).

I think we could achieve this in an automated way. We could have some sort of verification code for each organization and user (they wouldn't be able to change it). That code should be provided as part of the packages metadata, which may vary depending on the package kind. In a Helm chart, it could be an annotation, for example. This would require write access to the repo, which would prove ownership. When the trackers run, they would check if the provided code matches with the code of the org or user who added the repo, setting the `Verified publisher` flag accordingly. The code can be publicly visible, it wouldn't matter.

Users would still be able to fork a repo or copy the content to one they own and make it look like a verified one though. But in those cases at least the URL would be different and end users could see who is behind the content provided.

So not really sure how important this problem can be eventually or even if an extra flag (in addition to a potential `Official` one as discussed in #542) can introduce more confusion. What you do think @mattfarina ?

**Comment by mattfarina** [comment]
I like this idea. Something similar to what GitHub does. The difference from "official" makes sense. I like features like this that can be easily automated.
