### ISSUE TITLE
Project name is misleading

### ISSUE THREAD

**Issue by jzelinskie** [artifacthub/hub#551]
I'm sure there's been discussion and time lost to this topic in the past.
I find it misleading to call this project Artifact Hub when the content in question is not [yet] at all related to the [OCI Artifact] specification.

[OCI Artifact]: https://github.com/opencontainers/artifacts

**Comment by dankohn** [comment]
I came up with the name so I'll respond. We were thinking of Artifact in the more general sense, as described in https://en.wikipedia.org/wiki/Artifact_(software_development). The project has never been focused on OCI Artifacts or we would have called it OCIArtifactHub.

I'm closing the issue but please feel to discuss further here.
