### ISSUE TITLE
Add support for OPA policies repositories

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#554]
Related to #531

**Comment by tegioz** [comment]
We'll add support for `OPA policies` repos soon @swade1987. Please take a look at #531 and feel free to comment.

Would it be a problem for you to reorganize the policies files in your repo? We were thinking on a structure similar to [this one](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators), but we are definitely open to anything.

More docs will be coming soon, as the convention for the policies file inside each version folder, etc, so don't worry if everything is not completely clear yet.

Related to https://github.com/swade1987/deprek8ion/issues/17

**Comment by garethahealy** [comment]
@tegioz are you suggesting the structure would be:

```
policy-name
-> version
---> policy.rego
```

Currently, we (https://github.com/redhat-cop/rego-policies) follow what konstraint/gatekeeper do:
- https://github.com/plexsystems/konstraint/blob/main/docs/constraint_creation.md#resource-naming

**Comment by tegioz** [comment]
Hi @garethahealy 

I was, yes, but the first draft we're working on is slightly different, a bit more flexible. Let me take a look at your repo and check how it fits what we have now. We're definitely open to any suggestions, so feedback is very welcome. We expect to have an initial implementation soon and then we can iterate over it as needed.

Thanks!

**Comment by swade1987** [comment]
Epic thanks @tegioz 🚀

**Comment by tegioz** [comment]
@swade1987 @garethahealy 

If everything goes well we'll probably deploy a first implementation later today to staging. It'd be great if you can add your repositories once its done. We can check then how they look like and discuss potential improvements.

To add your repositories, you'd need to add the Artifact Hub metadata file(s) to your repo. Once that's done, you can log into Artifact Hub and add the repository, which can belong to your user or an organization you can quickly create from the control panel. Hopefully that part is easy and intuitive (please let us know otherwise).

### About the metadata file(s) and repository structure

I'll write here a short summary, but we'll document this properly soon. 

Each package version needs a metadata file. The metadata file delimits the start of the package version. All `rego` policies files, regardless of the directories structure from that point, will be considered part of the package. So you are free to decide how to structure your repos into one or multiple packages, and how your policies files are structured in directories as well.

I've created a sample metadata file for each of your repos.

In your case, @swade1987, it looks like a single package may be a good fit. So adding the metadata file in the policies directory would do the trick. If you only want to support a version at a time, the only thing you need to do is to keep updating the metadata file with new content, bumping the version when you change it. However, if you want to support multiple versions at a time, you'll probably need to create a directory for each version inside the policies folder, each of them with its own metadata file.

https://github.com/tegioz/deprek8ion/blob/master/policies/artifacthub.yaml

In your case, @garethahealy, I'm not sure how many packages you'd like to create or how would you like to name them, as you have a lot of policies files. Having a single package is fine too if you prefer it that way (the sample metadata file assumes a single package).

https://github.com/tegioz/rego-policies/blob/master/policy/artifacthub.yaml

Please feel free to use the samples as a base. Once your repos have the metadata files set up and you have added them to Artifact Hub from the control panel, the OPA tracker will check for changes periodically, updating Artifact Hub's database as needed.

I'll let you know once we've deployed to staging.

Thanks for your help!

**Comment by tegioz** [comment]
Support for OPA policies repositories has been deployed to staging @swade1987 @garethahealy. Please give it a try when you have a chance and let us know if you run into any issue.

https://staging.artifacthub.io

Thanks!

**Comment by swade1987** [comment]
I'll give it a go at some point this week and report back 😀

**Comment by garethahealy** [comment]
@tegioz ; i've pushed ours to staging:
- https://staging.artifacthub.io/packages/opa/redhat-cop-rego-policies/redhat-cop-rego-policies

First impression. We have several `lib` policies which are just helper methods. Not sure if they should be hidden/excluded/put to the bottom of the page, since they are not usable on their own.

**Comment by tegioz** [comment]
> @tegioz ; i've pushed ours to staging:
> 
> * https://staging.artifacthub.io/packages/opa/redhat-cop-rego-policies/redhat-cop-rego-policies

Thanks @garethahealy! That looks nice :)

> 
> First impression. We have several `lib` policies which are just helper methods. Not sure if they should be hidden/excluded/put to the bottom of the page, since they are not usable on their own.

Good point. Maybe we can have an entry in the `artifacthub.yaml` file to ignore some patterns (similar to .gitignore, etc). We'll add support for this soon.

If you want to add a logo at some point, you can use the `logoPath` field in the `artifacthub.yaml` file (more details [here](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub.yaml)).

**One note about updates:** a package version already indexed won't be indexed again unless the content of the `digest` field changes. This is mainly to avoid processing all packages and their available versions over and over again. So if you want to make changes to an existing version, you need to change the digest to something different. Otherwise you can just bump the version. Sorry this is not better documented yet, we'll work on that soon. In this particular case, I can force your package to be reindexed though.

**Comment by tegioz** [comment]
I think it'd also be nice if each of the policy files had a minimal description. We could display it in the box, giving the user some more details about what that particular policy file is about. Suggestions where to place this are welcome @garethahealy  @swade1987 :) Maybe a special comment at the top of each policy file?

**Comment by garethahealy** [comment]
re: a description / special comment. we use `konstraint` for our docs:
- https://github.com/redhat-cop/rego-policies/blob/master/policy/combine/namespace-has-networkpolicy/src.rego#L5-L12
- https://github.com/plexsystems/konstraint/blob/main/docs/cli/konstraint_doc.md

Would be nice if you followed that 👍 

CC @jpreese

**Comment by tegioz** [comment]
Thanks @garethahealy , I will look into it 👍 

I've just committed a change that should allow you to exclude the `lib` path. Adding the following code snippet to your `artifacthub.yaml` file should do the trick:

```yaml
ignore:
  - lib
```

**Comment by jpreese** [comment]
@garethahealy thanks for the ping, this is awesome!

Please let myself or @jalseth know if anything needs to be done on our end to help out with this initiative.

**Comment by tegioz** [comment]
OPA policies support has been deployed to production @garethahealy. Please feel free to add your repo when you have a chance :)
