### ISSUE TITLE
OLM tracker should be more flexible with the packages structure expected

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#568]
At the moment, the repository URL provided is expected to have a directory for each package available in the repo and, inside it, each of the versions in a different directory. It was done this way to follow the structure of the [Operator Framework community operators repository](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators).

However, many repositories may only contain one package, and users can provide the full path to it. This is the case of the [Ditto Operator repository](https://github.com/ctron/ditto-operator/olm/ditto-operator-bundle), which isn't being indexed properly at the moment. A quick workaround for this case is to remove the last part of the path in the url. But the OLM tracker should be able to handle cases like this out of the box. 

CC: @ctron

**Comment by ctron** [comment]
Fixed it on my side … thanks for the follow up!

**Comment by tegioz** [comment]
Awesome, thanks! 

I can see your package in Artifact Hub now: https://artifacthub.io/packages/olm/ditto-operator/ditto-operator

I'll deploy a fix for this soon so that it doesn't happen again 👍
