### ISSUE TITLE
Notifications inbox

### ISSUE THREAD

**Issue by scottrigby** [artifacthub/hub#597]
Similar to [GitHub notifications](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications) inbox at https://github.com/notifications

**Comment by tegioz** [comment]
Repositories tracking errors are shown in the UI, but only those raised during the last tracker execution. Past errors are not accessible from the UI, as well as errors that come and go, which may be a problem in some cases.

![errors](https://user-images.githubusercontent.com/1213902/91027736-c0f4a800-e5fc-11ea-8355-55aacf34176b.png)

These tracking errors, like new packages releases, are just *events*, which sometimes may trigger *notifications* (depending on users subscriptions, etc). Eventually there might be more interesting events to keep track of, like security alerts in packages the users are subscribed to, or some of the content they've published has been flagged as inappropriate or insecure. And I understand that handling these events from the email may not work for some people.

So, even though I think it's not something high priority, I think it's a good idea that could improve users experience. I don't think it'd need to be something as complete and powerful as Github notifications, probably something much simpler would be already helpful. So I suggested @scottrigby to create the issue to track the interest on it over time :)

**Comment by tegioz** [comment]
I think we can close this one for now as we haven't seen much interest on it, please feel free to reopen if needed. Thanks!
