### ISSUE TITLE
Org member roles

### ISSUE THREAD

**Issue by scottrigby** [artifacthub/hub#603]
Currently all org members have the same role. Once invited, any new member essentially owns the org, remove other members including the person who created the org, and even delete the org.

What roles would be useful? Some ideas (permissions are progressive from `member` -> `admin` -> `owner`, and new perms for each level up are underlined):
- **owner**
    - <ins>org: can delete</ins>
    - org: can edit settings
    - repo: can delete
    - repo: can transfer
    - repo: can edit
    - repo: can add new
    - member: can remove
    - member: can manage roles
    - member: can invite with role
    - member: can leave org (as owner, must either transfer ownership to new member or delete org to do this)
- **admin**
    - <ins>org: can edit settings</ins>
    - <ins>repo: can delete</ins>
    - <ins>repo: can transfer</ins>
    - repo: can edit
    - repo: can add new
    - <ins>member: can remove (except owner)</ins>
    - <ins>member: can manage roles</ins>
    - <ins>member: can invite with role</ins>
    - member: can leave org
- **member**
    - repo: can edit
    - repo: can add new
    - member: can leave org

Sketch also assumes only one owner, for simplicity.

**Comment by tegioz** [comment]
Please note that at the moment it isn't possible to delete an organization and the last member of it isn't allowed to leave it either.

**Comment by scottrigby** [comment]
**Update from Slack:** agree it's good to keep this as simple as possible for as long as possible, as long as it doesn't lock-out future features we can imaging could be nice later on like the above. For now, there are multiple owners. Related: https://github.com/artifacthub/hub/issues/586

Should we keep this issue open as a future feature idea or close it?

**Comment by tegioz** [comment]
I think we should keep it as a future idea and keep the discussion centralised here as more related stuff or ideas come up.
