### ISSUE TITLE
Add krew-index support

### ISSUE THREAD

**Issue by kvaps** [artifacthub/hub#619]
[Krew](https://github.com/kvaps/krew-index/) is plugin manager for kubectl

Example repos:

- https://github.com/kubernetes-sigs/krew-index/
- https://github.com/kvaps/krew-index/

cc @ahmetb

**Comment by mattfarina** [comment]
Related... https://github.com/helm/hub/issues/377

**Comment by scottrigby** [comment]
Part of me thinks Artifact Hub could aggregate ALL THE CNCF THINGS. But the other part wonders if Artifact Hub may prefer not to expand its scope from aggregating info about distributed "packages and configurations" to now also include "tools and extensions". Do we have in mind any practical pros and cons from end user and maintainer perspectives?

**Comment by tegioz** [comment]
You can now add your own index repository to Artifact Hub @kvaps. For more information, please see: https://artifacthub.io/docs/topics/repositories/#krew-kubectl-plugins-repositories.

**Comment by kvaps** [comment]
Awesome, thank you!

[![Artifact HUB](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/kvaps-krew)](https://artifacthub.io/packages/search?repo=kvaps-krew)
