### ISSUE TITLE
[feat] Add Charts API

### ISSUE THREAD

**Issue by rimusz** [artifacthub/hub#640]
Add Charts API to get a list of helm repos in Artifact hub.

**Comment by mattfarina** [comment]
I wonder how this will scale up. Imagine the case of 1,000 repos. Or more. It reminds me of the catalog API in OCI distributions (container repos) that has not scaled well.

I wonder if this would be ok for a V1 API or if there is some nuanced detail that might make it scale better.

**Comment by tegioz** [comment]
There is already an API endpoint to get all repositories:

https://artifacthub.github.io/hub/api/#/Repositories/get_repositories

The kind for Helm repos is `0` (more details in the API docs schema). The url is missing in the docs but it should be there (will fix that soon).

We have some internal APIs for this, so we could expose the `GetByKind` one easily to avoid fetching all of them:

https://github.com/artifacthub/hub/blob/8f2122d97cb29f5ef7b8b7aec55841609e754742/internal/hub/repo.go#L102-L106

Regarding scaling up, we could add some pagination. The only endpoint with pagination support at the moment is the packages `search` one, but eventually some more will need it (like this one). In the meantime we can have this endpoint responses cached for longer than the default API cache time, which is 5 mins. New repos are not added that often, so we can cache more aggressively. At the moment, it takes `~3 ms` for that endpoint to complete returning ~300 repos.

**Comment by tegioz** [comment]
We've added a new API endpoint to get repositories by kind @rimusz.

https://artifacthub.github.io/hub/api/#/Repositories/get_repositories___helm___falco___opa___olm__

**Comment by rimusz** [comment]
thanks a lot @tegioz for the quick one release 👍

**Comment by tegioz** [comment]
Hi @rimusz 👋 

We are consolidating some repositories API endpoints and some of the current ones won't be available soon. Among them it's the one we added to get repositories by kind, which is going to be replaced by a new repositories `search` endpoint that allows fetching repositories filtering by multiple criteria (like the repository kind, for example) with pagination support. This will probably be deployed tomorrow, as soon as #1382 is ready.

Sorry for the short notice and any inconvenience this may cause. We are getting ready to release version `1.0.0` soon, and we'd rather introduce any needed breaking changes as soon as possible.
