### ISSUE TITLE
mark prometheus org and prometheus-community repo official

### ISSUE THREAD

**Issue by scottrigby** [artifacthub/hub#642]
The https://github.com/prometheus-community github org is owned by Prometheus: is owned by prometheus: https://prometheus.io/community/ This is tied to the "prometheus" Org in Artifact Hub:
- https://artifacthub.io/packages/search?page=1&org=prometheus

The https://github.com/prometheus-community/helm-charts repo is officially supported by the prometheus community
- https://artifacthub.io/packages/search?page=1&repo=prometheus-community

Per https://cloud-native.slack.com/archives/C0103CTR3RB/p1599567376028300 (https://github.com/artifacthub/hub/issues/542) there's not yet an official application process. Are issues like this a good way forward for now? In the last dev call I seem to remember we discussed this github issues as our default non-automated processes for things that can be public, like this.

**Comment by tegioz** [comment]
Done! 👍 

The `official` flag is only set at the repository level at the moment.

Yes, I think using issues like this is a good way forward for now. Among other things, maybe we could require the `Verified Publisher` flag to be set before being able to apply for `Official`.

**Comment by scottrigby** [comment]
I was thinking the same about verification being a required first step 👍
