### ISSUE TITLE
Trying to sign up with identical passwords containing symbols throws a 'Passwords don't match' error

### ISSUE THREAD

**Issue by SamuAlfageme** [artifacthub/hub#650]
I was just trying to sign up for https://artifacthub.io/ and fired up my password manager of choice, generated a long and full of entropy password (`H$J9zGU9WjUYQQfq&uP@CoUS$hXHoXhR%5vywYbHi4yopfYh2qKRp$`) and used it on the login form. It then complained 'Passwords don't match' so I blamed my copy-paste abilities, cleaned the two boxes and tried again:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/93144815-2d8a3080-f6eb-11ea-864e-a37de67a6ea2.png"/>
</p>

And just to rule out the length as responsible, I have tested with a way smaller pass (8 chars) with some `^` and `&`s on it and got the same result, so I'm guessing there must be something fishy with that form's validation.

**Comment by cynthia-sg** [comment]
Thanks for the catch @SamuAlfageme

**Comment by SamuAlfageme** [comment]
@cynthia-sg woah, that was a fast fix! Thanks you guys, keep up the good work!

**Comment by tegioz** [comment]
We'll deploy it to prod in ~15 mins ;) Thanks!
