### ISSUE TITLE
How does one become verified publisher?

### ISSUE THREAD

**Issue by tamalsaha** [artifacthub/hub#723]

**Comment by tegioz** [comment]
Hi @tamalsaha 

You need to add a [metadata file](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) to the repository including the ID listed in the control panel. For more information please take a look at the [repositories guide -verified publisher section-](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#verified-publisher). 

Please let us know if you have any problem setting it up.

**Comment by tamalsaha** [comment]
Thanks, @tegioz ! I can't add a repository in my case because the name already exists.

![can't-add-repo](https://user-images.githubusercontent.com/94814/95578453-c2c9cd80-09e8-11eb-8b47-14aeb0f49441.png)

**Comment by tegioz** [comment]
No worries :)

If that repository is yours, you can claim its ownership. Please check:

https://github.com/helm/hub#claiming-your-repo-in-the-artifact-hub
https://github.com/artifacthub/hub/blob/master/docs/repositories.md#ownership-claim

**Comment by tegioz** [comment]
You can even create an organization and transfer the repository to it ;)

**Comment by tamalsaha** [comment]
I tried to claim ownership but that fails because the repo does not have artifacthub-repo.yml file. I can't create that file because I don't know the `repositorID` for `appscode`. Is there a way to do it myself?

**Comment by tamalsaha** [comment]
![Artifact-Hub](https://user-images.githubusercontent.com/94814/95579334-4932df00-09ea-11eb-8bfe-c4af82acc70c.png)

**Comment by tegioz** [comment]
Yes, you'll have to do it in two steps. You can omit the `repositoryID` field in the first run and only set the `owners`. Once it's yours, you'll see it in the control panel and you'll be able to set the verified publisher flag as well.

This could be clearer in the docs, sorry about that. Will improve them soon :)

**Comment by tamalsaha** [comment]
Thanks! It worked.
