### ISSUE TITLE
Installation instructions not Helmv3-compatible

### ISSUE THREAD

**Issue by makkes** [artifacthub/hub#725]
I just noticed the Helm install commands issued by Artifact Hub aren’t v3-compatible, e.g.
```
helm install helm-stable/hackmd --version 2.0.0
```
has to be
```
helm install hackmd helm-stable/hackmd --version 2.0.0
```

This was discussed [on Slack](https://cloud-native.slack.com/archives/C0103CTR3RB/p1602243876038800) and these are the two simplest ways to solve this:

1. Show two tabs in the dialog, one for v2 and another one for v3
1. Switch to v3 completely

**Comment by scottrigby** [comment]
Yes it should default to Helm 3 command. From `helm install -h` usage: `helm install [NAME] [CHART] [flags]`. However for the next month (until 13 Nov 2020) Helm 2 will still be supported. If possible, there could also be a tab for Helm 2 until then?

Perhaps also follow the CLI usage pattern and add `[flags]` so users know this is a sample command (not necessarily meant for cut and paste), as well as a link to the command doc so users know what options there are? Example:

### Helm 3
```md
$ helm install [RELEASE_NAME] repo-name/chart-name [flags]
```
_See [helm install](https://helm.sh/docs/helm/helm_install/) for command documentation._

### Helm 2

```console
$ helm install --name [RELEASE_NAME] repo-name/chart-name [flags]
```
_See [helm install](https://v2.helm.sh/docs/helm/#helm-install) for command documentation._

**Comment by makkes** [comment]
Thanks @cynthia-sg!!
