### ISSUE TITLE
Add PromCat support

### ISSUE THREAD

**Issue by ebcarty** [artifacthub/hub#727]
Prometheus Catalog ([PromCat](http://promcat.io/)) is a resource catalog of exporters for Prometheus Monitoring.

Example apps...
- https://promcat.io/apps/elasticsearch
- https://promcat.io/apps/postgresql
- https://promcat.io/apps/harbor

related to:  #619

**Comment by tegioz** [comment]
Hi @ebcarty 👋 

Sorry for the very late response 😓

We are always open to add support for new packages kinds, but please note that Artifact Hub currently only supports vendor neutral artifacts. Everything listed is currently in a foundation and not attached to a single vendor. If/when this is the case, we’d be happy to consider it 🙂
