### ISSUE TITLE
Reference docs based on values.schema.json

### ISSUE THREAD

**Issue by mik-laj** [artifacthub/hub#755]
Hello,

In the Apache Airflow project, we are working on automatically generated reference documentation based on the [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) file. This file usually contains the complete structure and data types, but may also contain a description for each field. JSON is not a very user-friendly format, and we wanted to make this information more user-friendly.

I would be happy if you could share your opinion on this feature, and in the long run we can integrate it into your project. For now, please consider this as a new feature requests for Arifacts Hub.

Best regards,
Kamil Breguła

**Comment by RichiCoder1** [comment]
Was just about to request this myself! This would be great to support, if only to encourage making this the standard as helm values are inconsistently documented at best.

**Comment by kaxil** [comment]
I agree, having them in json makes it easier to automatically generate docs

**Comment by tegioz** [comment]
This is a great idea, thanks!

We'll think a bit more about this to see how we can leverage the use of the `values.schema.json` file in Artifact Hub to encourage users adding it to their Helm charts.

**Comment by mik-laj** [comment]
Related issue: https://github.com/apache/airflow/issues/11077

**Comment by tegioz** [comment]
Thanks for sharing the related issue @mik-laj.

@cynthia-sg and I were thinking that we should be able to build something directly on the UI to display a documented `values.yaml` file based on the content of the `values.schema.json`. We have a couple of ideas we'd like to experiment with first to check if they are a good approach. We'll keep you posted 🙂

**Comment by tegioz** [comment]
<img width="1627" alt="schema1" src="https://user-images.githubusercontent.com/1213902/97011455-fd824880-1546-11eb-8b35-f08307b0b82b.png">

Built from: https://github.com/artifacthub/hub/blob/master/charts/artifact-hub/values.schema.json

Info on the right panel can be expanded for more details.

**Comment by kaxil** [comment]
that looks good @tegioz , thanks

**Comment by mik-laj** [comment]
It's more amazing than I could have ever imagined.

**Comment by mik-laj** [comment]
Can you add a button that generating a JMESPath for each key? I wish I could easily press a button to get a value that I can use in `helm --set`

**Comment by tegioz** [comment]
> Can you add a button that generating a JMESPath for each key? I wish I could easily press a button to get a value that I can use in `helm --set`

We'll add this button next week @mik-laj ;)

**Comment by tegioz** [comment]
Deployed! You can take a look at it live in the Artifact Hub package: https://artifacthub.io/packages/helm/artifact-hub/artifact-hub

**Comment by kaxil** [comment]
that was quick :D

**Comment by tegioz** [comment]
Thank you all, this was a great idea! Hopefully it'll encourage publishers to write schemas for their charts :)

**Comment by kaxil** [comment]
> Thank you all, this was a great idea! Hopefully it'll encourage publishers to write schemas for their charts :)

If there is a best practises / guidelines docs for Publishers, we should add this to it

**Comment by mik-laj** [comment]
@kaxil See: https://github.com/helm/helm-www/issues/903
