### ISSUE TITLE
Changelog Link/Docs

### ISSUE THREAD

**Issue by RichiCoder1** [artifacthub/hub#760]
There's not really a way/convention to view the changelog for most charts, and most charts only document major breaking changes. This can make evaluating upgrades difficult, especially in chart monorepos. It'd be great if Artifact Hub could bless a method or set of methods for a chart publisher to surface a changelog.

Not sure how best this could be accomplished, especially since packing the changelog into the chart itself might not fit into most publishers' flow. Maybe and configurable/templated URL that Artifact Hub can render to link to the appropriate Git tag or GitHub release?

Made in the same spirit of #755

**Comment by mik-laj** [comment]
Have you created a [helm/helm ](https://github.com/helm/helm)  or [helm/chart](https://github.com/helm/charts/) ticket about this problem? I think maybe we could find some best practices that other projects could also use.

I think maybe best practises can be added to [https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md](REVIEW_GUIDELINES.md]) or [best practises](https://helm.sh/docs/chart_best_practices/conventions/) on Helm WWW.

**Comment by tegioz** [comment]
Related: https://github.com/helm/helm/issues/7515
