### ISSUE TITLE
Feature Request | LDAP integration support for on-prem installation

### ISSUE THREAD

**Issue by avinash-0-singh** [artifacthub/hub#769]
On-prem installation capability of artifacthub.io makes it great tool. Wanted to onboard existing ldap users. It would be great if we can have support for SSO via Ldap.

**Comment by tegioz** [comment]
Hi @avinash-0-singh 

We've just added [experimental support for OpenID connect](https://github.com/artifacthub/hub/pull/1000). Using an OpenID connect provider like [Dex](https://dexidp.io) and its [LDAP connector](https://dexidp.io/docs/connectors/ldap/) you should be able to log into Artifact Hub using LDAP accounts.

**Comment by tegioz** [comment]
I'll close this one for now @avinash-0-singh as I think we should be covered with the OpenID connect support. Please feel free to reopen if needed.
