### ISSUE TITLE
Support basic auth

### ISSUE THREAD

**Issue by woodcockjosh** [artifacthub/hub#773]
Please support basic authentication in url of helm chart at a minimum

For example: `https://myuser:mypassword@myhelmchartrepo.mydomain.com`

Right now if we try to add a private chart repository we get an error saying that the url is invalid.

**Comment by tegioz** [comment]
I was wondering if we should include the repo basic auth credentials in the install instructions displayed on the UI (`--username ...`), or if users of those private repos will get them separately. I understand this feature request is for a private Artifact Hub deployment, not to be used in `artifacthub.io`.

<img width="824" alt="install" src="https://user-images.githubusercontent.com/1213902/96832256-c32d8400-143e-11eb-9d1c-f3d857db6b46.png">

**Comment by tegioz** [comment]
We should probably make sure we don't allow private repos to be listed on `artifacthub.io`, so this feature should be configurable.

**Comment by woodcockjosh** [comment]
AFKAIK the only way to install helm charts in a private repo is to include the credentials in the url of the repository in thee Chart.yaml. Hopefully helm will add a better solution soon but for now we should at least not give a url validation error when trying to add username and password to the url in artifact hub. (at least for repositories other than artifacthub.io.

**Comment by tegioz** [comment]
I think you can provide the basic auth credentials when adding the repo. That's why I was wondering if, when provided, we should display them in the install instructions as well.

```sh
$ helm repo add --help 
add a chart repository

Usage:
  helm repo add [NAME] [URL] [flags]

Flags:
      ...
      --password string            chart repository password
      --username string            chart repository username
```

**Comment by woodcockjosh** [comment]
Right but artifacthub cannot access those charts

**Comment by tegioz** [comment]
This should be ready @woodcockjosh. Please take a look at the [repositories guide](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#private-repositories) for more details.

This change is not part of any release yet, so if you want to use it right now, you'll need you build your own images. We'll probably release a new version next week though.

**Comment by woodcockjosh** [comment]
Looks good! Thanks!
