### ISSUE TITLE
Request: Allow more width in responsive size for chart README content.

### ISSUE THREAD

**Issue by jgreat** [artifacthub/hub#778]
The new artifacthub site looks great!

There is a nitpick I have with the documentation (README) section. Its the same one I have with the old hub.helm.sh and github.com README sections.  Since the size of the documentation is space only expands so far it almost always truncates the width on the configuration options tables. With charts that have a lot of options (what public chart doesn't have a lot of options) the horizontal scroll bar ends up at the bottom of the full documentation section. This make navigation of the options pretty painful and I would argue that the configuration options table is the most important and most used part of the documentation.

I would love to see the site allow more width to accommodate wide format displays. If a user has the space let them use it.

(so much unused space 3440x1440 monitor.) 
![image](https://user-images.githubusercontent.com/5324639/96923568-18858780-1477-11eb-8cb6-5d137036d9d1.png)

**Comment by tegioz** [comment]
Thanks @jgreat! We'll try to improve that a bit 👍

**Comment by tegioz** [comment]
Hi @jgreat 

This change has just been deployed to production. We've optimized the UI for larger resolution screens. Hopefully tables will look nicer now in your monitor :)

<img width="2074" alt="large1" src="https://user-images.githubusercontent.com/1213902/98370862-8a46ff00-203b-11eb-89e3-1eb641e984c0.png">

<img width="2074" alt="large2" src="https://user-images.githubusercontent.com/1213902/98370874-90d57680-203b-11eb-9b8f-331e75e5dea1.png">
