### ISSUE TITLE
Question: How to generate open api spec

### ISSUE THREAD

**Issue by WLun001** [artifacthub/hub#783]
I like the hub, been using it for awhile. 

Here is my question, not related to the project itself. 

I noticed that https://artifacthub.github.io/hub/api/ uses Open API 3.0
How does the https://github.com/artifacthub/hub/blob/master/docs/api/openapi.yaml generated? Looking at the code I can't find any clues. 

Currently looks like no Go library that support Swagger spec 3.0

**Comment by tegioz** [comment]
Hi @WLun001 👋 

The `openapi.yaml` file is maintained manually, not automatically generated.
