### ISSUE TITLE
Direct link to values schema reference

### ISSUE THREAD

**Issue by mik-laj** [artifacthub/hub#784]
Hello,

ArtifactsHub has a great new feature - [auto-generated reference documentation](https://github.com/artifacthub/hub/issues/755) for values.yaml file. This is fantastic, but..., I miss the possibility of creating a direct link to the documentation so that I can add this link to the README.md file or send it to a friend.

Best regards,
Kamil Breguła

**Comment by tegioz** [comment]
https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=values-schema

**Comment by mik-laj** [comment]
Unfortunately, it doesn't work on Android devices. Can you check it out?

**Comment by tegioz** [comment]
The schema values modal is not displayed on mobile devices at the moment. Not all content of the site is available for mobile devices. Sometimes some views don't fit nicely on small screens as they are, and a new dedicated design would be needed. Other times it may not make much sense to display that much information on a mobile device, and some information is left out.

**Comment by mik-laj** [comment]
In that case, a message would be useful. Currently, the scrollbar locks but the window modal does not appear. This is very confusing for users.

**Comment by tegioz** [comment]
Oh, I see what you mean now. This is a bug indeed. The correct behaviour was to display the package view, omitting the modal. We'll fix it tomorrow morning, leave it with us 👍
