### ISSUE TITLE
Button for copying a JMESPath in the rvalues schema reference

### ISSUE THREAD

**Issue by mik-laj** [artifacthub/hub#785]
Hello,

ArtifactsHub has a great new feature - [auto-generated reference documentation](https://github.com/artifacthub/hub/issues/755) for values.yaml file. This is fantastic, but.... Can you add a button that generating a JMESPath for each key? I wish I could easily press a button to get a value that I can use in `helm --set`

Best regards,

**Comment by tegioz** [comment]
<img width="618" alt="Screen Shot 2020-10-26 at 18 12 18" src="https://user-images.githubusercontent.com/1213902/97205112-4a6c5600-17b7-11eb-87b4-d0fa812b55ed.png">
