### ISSUE TITLE
error loading chart: scheme not supported

### ISSUE THREAD

**Issue by hansehe** [artifacthub/hub#836]
Hi, 

I'm getting a strange error for my helm repository during update. It happened after I added a new chart version, and the repository will not list the new chart version due to the problem.

The error I'm getting is:
```
error loading chart (graphql-gateway-0.1.0.tgz): scheme not supported (package: graphql-gateway version: 0.1.0)
error loading chart (graphql-gateway-0.1.1.tgz): scheme not supported (package: graphql-gateway version: 0.1.1)
```

Link to the helm repository on artifacthub:
- https://artifacthub.io/packages/helm/graphql-gateway/graphql-gateway

Link to the helm repository:
- https://github.com/hansehe/graphql-gateway/tree/master/helm/charts

**Comment by tegioz** [comment]
Hi @hansehe 

Thanks for reporting this. I introduced this issue on Friday, sorry about that.

I've just pushed a fix, will deploy it to prod shortly.

**Comment by tegioz** [comment]
Deployed to production @hansehe. Your charts have just been processed correctly.

**Comment by hansehe** [comment]
Thanks! 👍
