### ISSUE TITLE
Add links for direct downloads for the given charts

### ISSUE THREAD

**Issue by Akasurde** [artifacthub/hub#839]
Helm can download and install chart from the direct URL.

```
/usr/local/bin/helm --namespace=monitoring upgrade -i --reset-values test https://github.com/grafana/helm-charts/releases/download/grafana-5.6.0/grafana-5.6.0.tgz
```

Please add a direct download URL value in INSTALL modal page or somewhere else.

<img width="818" alt="Screenshot 2020-11-10 at 12 33 36" src="https://user-images.githubusercontent.com/633765/98640953-fafa5e00-2350-11eb-9227-de371bef1a3c.png">

**Comment by tegioz** [comment]
This is done @Akasurde, it'll be deployed to production later on today.

<img width="1060" alt="download_link" src="https://user-images.githubusercontent.com/1213902/98799761-d31dff80-240f-11eb-922a-e27a5f13201b.png">

**Comment by Akasurde** [comment]
Oh! sweet. Thanks for the quick fix.
