### ISSUE TITLE
artifacthub.github.io does not exist.

### ISSUE THREAD

**Issue by cronventis** [artifacthub/hub#844]
When following the readme on how to install this Chart, the url does not exist:

https://github.com/artifacthub/hub/blob/master/charts/artifact-hub/README.md
https://artifacthub.github.io/hub/chart

```bash
$ helm repo add artifact-hub https://artifacthub.github.io/hub/chart
```

**Comment by tegioz** [comment]
Hi @cronventis 

The URL seems to be fine, and I've just tried adding the repo with the command you provided and it worked fine for me.

Could you provide some more details?

That chart is served using Github Pages, like the [documentation](https://artifacthub.github.io/hub/api/).

**Comment by cronventis** [comment]
Mhm... I thought that https://artifacthub.github.io/hub/chart should work in the browser? Maybe I'm just wrong :)

**Comment by tegioz** [comment]
That url is not really meant to be used in the browser directly, just by Helm. But said that, we'll add something to it so that it doesn't show a 404 error :) Please note that this is not required and you may find more charts repositories that behave like this.
