### ISSUE TITLE
Official badge for HPE storage

### ISSUE THREAD

**Issue by datamattsson** [artifacthub/hub#845]
I'm one of the contributors to the HPE storage Helm charts at https://github.com/hpe-storage/co-deployments. I've performed the steps to become a verified publisher and now seeking the official badge. What is the process?

**Comment by tegioz** [comment]
Hi @datamattsson 

Unfortunately we haven't defined the process formally yet. But requesting it using a Github issue works for now.

The requirements are that the user or organization publishing the repository actually owns the software deployed by the packages available on it. I think everything looks good in this case, so your repository has just been marked as official.
