### ISSUE TITLE
It's not possible to edit or delete organization

### ISSUE THREAD

**Issue by aabouzaid** [artifacthub/hub#849]
Hello,

In: https://artifacthub.io/control-panel/organizations
I've added an organization to my account, however, I'm not able to neither delete nor delete it.
I didn't use the org in any activities yet (e.g. claim ownership or so)

So what can I do in case I want to delete the org or at least edit it?

**Comment by aabouzaid** [comment]
Hi @tegioz
Thanks a lot for your reply.

I think that's enough, I didn't realize the "Control panel context" part. I can edit and invite other members to the org and remove the other user. (I logged in with the personal account instead of the company account and the org was owned by personal account).

Thanks again.

**Comment by tegioz** [comment]
No worries. Awesome, that sounds great 👍
