### ISSUE TITLE
Security report is confusing

### ISSUE THREAD

**Issue by sagikazarmark** [artifacthub/hub#850]
I created a helm chart for [SFTPGo](https://github.com/drakkan/sftpgo) and published it in a repository on Artifact Hub:

https://artifacthub.io/packages/helm/sagikazarmark/sftpgo/0.0.7

There are two flavors of images published for SFTPGo:

- Debian based
- Alpine based

Both images are added to the chart as [annotations](https://github.com/artifacthub/hub/blob/07a31e33d94136549b8f8dd11705fe6892b866c6/docs/helm_annotations.md) in `Chart.yaml`.

As one could expect, the Debian version is full of packages with reported security vulnerabilities whereas the Alpine version is all green.

When looking at the Security report, it's a little bit confusing though, because it shows all those red signs and without a few clicks it's not immediately obvious that there are alternative images which should be "safe" to use.

Publishing images for multiple distributions is a common practice and the "default" is often Debian and not Alpine, so it's even more important to share that information. I don't have any ideas how to do that though, I just wanted to raise an issue about it.

Here are some screenshots that show what I tried to describe above:

![Screenshot 2020-11-12 at 19 54 46](https://user-images.githubusercontent.com/1226384/98983896-c093eb00-2521-11eb-96aa-9bf875f5992f.png)
![Screenshot 2020-11-12 at 19 55 03](https://user-images.githubusercontent.com/1226384/98983906-c25dae80-2521-11eb-945c-eba19de07a78.png)
![Screenshot 2020-11-12 at 19 55 10](https://user-images.githubusercontent.com/1226384/98983918-c38edb80-2521-11eb-8ac2-f24acd6cbf75.png)

**Comment by tegioz** [comment]
Hi @sagikazarmark 

Thank for you the feedback. We are definitely open to make any changes needed to improve it 🙂 

What do you think about the following screenshot?

![security_report](https://user-images.githubusercontent.com/1213902/99061538-0395a300-25a2-11eb-9d99-18dc30b313d5.jpeg)

Changes introduced would be:

- Added table with vulnerabilities summary per image at the top
- Vulnerabilities details per image appear now collapsed, and users can expand each of them manually for more details
- The security rating badge now opens the package with the security report modal open, taking the user directly to the security details

Improving the security rating badge or the summary may be a bit trickier. Summarizing something as complex as a security report in such a small piece of information is not easy. Any ideas to improve any of them are welcome.

**Comment by sagikazarmark** [comment]
@tegioz the new screenshot looks great, thanks!

The security badge could maybe say

```
128 vulnerabilities found
(in 2 images)
```

Or an information icon next to the summary text saying the same in a popup, pointing to the full report for details.

**Comment by tegioz** [comment]
> @tegioz the new screenshot looks great, thanks!

Awesome, we'll finish and deploy it soon 👍 

> 
> The security badge could maybe say
> 
> ```
> 128 vulnerabilities found
> (in 2 images)
> ```

This can lead to a very large badge that may not be as meaningful. 1 critical vulnerability is not the same as 10 of low severity, for example. That's why we tried to summarize it with a letter, similar to what other badges do.

Just to double check we are on the same page, this is what we call the badge:

<img width="802" alt="badge" src="https://user-images.githubusercontent.com/1213902/99066914-0dbb9f80-25aa-11eb-9427-b77bc9aa8ecb.png">

And this is the summary:

<img width="305" alt="summary" src="https://user-images.githubusercontent.com/1213902/99067046-4a879680-25aa-11eb-87bd-e172f2cb58be.png">

Adding the number of images in the summary sounds good, that wouldn't be a problem.

> 
> Or an information icon next to the summary text saying the same in a popup, pointing to the full report for details.

This will happen now when clicking on the badge itself, the full report will be displayed. This should allow the user to check the details in a single step.

**Comment by sagikazarmark** [comment]
Sorry, I meant adding it to the summary, not the badge itself.

**Comment by tegioz** [comment]
Ok, cool, no problem.

**Comment by tegioz** [comment]
Just in case this also helps @sagikazarmark: #864

**Comment by sagikazarmark** [comment]
@tegioz thanks! Although I'm not sure I understand that feature. Why would I want to "hide" if the default image has vulnerabilities? 😄

**Comment by tegioz** [comment]
> @tegioz thanks! Although I'm not sure I understand that feature. Why would I want to "hide" if the default image has vulnerabilities? 😄

It may not apply to your case, but in some situations you may be certain that some or all of the vulnerabilities detected are not related to your application or won't have any impact on it. You may also have listed some optional images with severe security issues, which may mislead users regarding the overall security of your package. In those cases, you can whitelist some of them.

In Helm packages, at the moment, images need to be declared explicitly in the annotations. But in others, like OLM operators, this is not the case as images are detected automatically, and publishers didn't have a way to opt-out of the security report for all or some images.

**Comment by sagikazarmark** [comment]
Thanks for the explanation! Makes sense
