### ISSUE TITLE
Official badge for Camunda BPM

### ISSUE THREAD

**Issue by aabouzaid** [artifacthub/hub#851]
Hello,

As I understand, it's not possible to create the official badge automatically.

So could you please add an official badge to Camunda org/repo?
https://artifacthub.io/packages/search?page=1&org=camunda
https://github.com/camunda/camunda-helm

Thank you.

**Comment by tegioz** [comment]
Done!

**Comment by aabouzaid** [comment]
Thanks a lot :+1:

**Comment by aabouzaid** [comment]
@tegioz so eventually the project has been moved to the community, so could you please remove the official badge.

**Comment by tegioz** [comment]
Sure, thanks for letting us know 👍
