### ISSUE TITLE
Add OLM CSV relatedImages scanning

### ISSUE THREAD

**Issue by cdjohnson** [artifacthub/hub#857]
The Operator Lifecycle Manager ClusterServiceVersion now contains a section:  `relatedImages` that includes references to all Operand images that the Operator may install. 

The operator typically doesn't do all that much by itself, so scanning the controller by itself is not that useful.  

See the OLM design spec for details:
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/contributors/design-proposals/related-images.md

See the OpenShift documentation for an example on how the CSV can describe these images:
https://docs.openshift.com/container-platform/4.6/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs

Note:  the `relatedImages` section in the specification does is not part of the operator-framework GO Schema Library and must be parsed through other means:
https://kubernetes.slack.com/archives/C0181L6JYQ2/p1605191726124900

**Comment by tegioz** [comment]
#860 has just been deployed. Related images available in OLM are now tracked. They'll be displayed in the package detail view and scanned for security vulnerabilities. Please note that images stored in private registries won't be scanned.
