### ISSUE TITLE
Official Badge for Klustair

### ISSUE THREAD

**Issue by mms-gianni** [artifacthub/hub#872]
Hi there

I'm the Dev of Klustair and published the Klustair Helm chart recently.

Since there is no other process for now of getting the official Badge, I'm opening this ticket. 

https://artifacthub.io/packages/helm/klustair/klustair 
https://github.com/klustair/klustair-helm 
http://www.klustair.com 

Thank you

**Comment by tegioz** [comment]
Done!

Your package looks great on Artifact Hub, nice work with the schema and the changelog 🥇

A couple of tips just in case you didn't know: using the [artifacthub.io/links annotation](https://artifacthub.io/docs/topics/annotations/helm/) you can override the names of the source links in the `Chart.yaml` file, to make them look nicer. Also, if you use a tag other than `latest` in your images, they'll be scanned for security vulnerabilities and a security report will be generated for your package. For more details please see: https://artifacthub.io/docs/topics/security_report/.

**Comment by mms-gianni** [comment]
Thank you for your lightning fast approval and tips.

I will implement them with my next version.
