### ISSUE TITLE
Add ability to hide a repository

### ISSUE THREAD

**Issue by cdjohnson** [artifacthub/hub#877]
I would like to be able to claim ownership of a repository and temporarily hide it to prevent others from registering the repository.

There are a couple of use cases:
1.  The repository isn't quite ready to show up in artifacthub yet.
2.  The repository has operators that are not designed to be discoverable without some other context (e.g. it's not designed to be public)

**Comment by tegioz** [comment]
This should help @cdjohnson. We'll deploy it tomorrow.

<img width="627" alt="disabled" src="https://user-images.githubusercontent.com/1213902/100271568-fa211900-2f59-11eb-95b4-c4995eb9351f.png">

**Comment by cdjohnson** [comment]
Perfect.  This is exactly what i was looking for
