### ISSUE TITLE
Cannot add another user to an organization

### ISSUE THREAD

**Issue by joestringer** [artifacthub/hub#878]
I have created the "Cilium" organization on Artifact Hub, and now I would like to invite a co-maintainer (@aanm with the same username on AH) to the organization, but the dialogue box states that the user cannot be found.

I tried using both the username directly, and also tried using the email corresponding to that account. Neither worked.

**Comment by tegioz** [comment]
Hi @joestringer 

Thanks for reporting this 👍🏻 It is a regression I [introduced recently](https://github.com/artifacthub/hub/pull/832). 

I've just deployed the fix, it should be working fine now.
