### ISSUE TITLE
Helm redirect to a specific version

### ISSUE THREAD

**Issue by mattfarina** [artifacthub/hub#883]
Over on https://github.com/helm/hub/issues/482 it was noted that Helm redirects on artifact hub for specific versions do not work. For example, https://hub.helm.sh/charts/ibm-charts/ibm-odm-dev/20.2.0 is a 404 page but https://hub.helm.sh/charts/ibm-charts/ibm-odm-dev/ works.

There are some people who have linked, in their documentation, to specific versions and are now getting a 404.

Would it be possible to do the version redirect?

**Comment by tegioz** [comment]
It's done @mattfarina, should be working now.
