### ISSUE TITLE
Official badge for sumologic

### ISSUE THREAD

**Issue by kkujawa-sumo** [artifacthub/hub#884]
I would like to ask for official badge for [sumologic](https://artifacthub.io/packages/helm/sumologic/sumologic).
Repository: https://github.com/SumoLogic/sumologic-kubernetes-collection, [artifacthub-repo.yml](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/gh-pages/artifacthub-repo.yml)

**Comment by tegioz** [comment]
Done!

**Comment by kkujawa-sumo** [comment]
Thank you!

**Comment by cynthia-sg** [comment]
Hi @kasia-kujawa,

We've had to remove the "official" label from this package as we noticed that the owner is not the Sumo Logic organization, like this [one](https://artifacthub.io/packages/helm/tailing-sidecar-operator/tailing-sidecar-operator).

In Artifact Hub, we typically recommend that official packages be published under an organization when possible, as in this case. Sumo Logic can claim ownership by following these [steps](https://artifacthub.io/docs/topics/repositories/#ownership-claim).

If you have any questions or need help with this, please don't hesitate to reach out.

Thanks.
