### ISSUE TITLE
artifacthub not loading in firefox 

### ISSUE THREAD

**Issue by buddudevelopers** [artifacthub/hub#913]
its not loading in firefox but loads in edge browser. Maybe a certificate related issue. [img] [https://ibb.co/PNznnj8](url)

**Comment by tegioz** [comment]
Hi @buddudevelopers 

I've just tested it with Firefox 83 on MacOS and it loads fine for me. I can't see any problem with the certificate either.

There are a number of reasons that could be causing this issue on your side as well, like browser extensions, firewalls, proxies, vpns, etc.

**Comment by tegioz** [comment]
I'll close this one for now, please reopen if needed.
