### ISSUE TITLE
Official badge for Datadog Helm charts

### ISSUE THREAD

**Issue by vboulineau** [artifacthub/hub#920]
Hello,

As we've added the [artifacthub-repo.yml](https://github.com/DataDog/helm-charts/blob/gh-pages/artifacthub-repo.yml), we would like to have the `Official` badge on all Helm charts hosted in this repository:
https://artifacthub.io/packages/search?page=1&repo=datadog

Best,
Vincent

**Comment by tegioz** [comment]
Done!
