### ISSUE TITLE
defaultDeployment/service/type configuration is not working

### ISSUE THREAD

**Issue by eduardoroliveira** [artifacthub/hub#921]
Problem:
=======
Changing the defaultDeployment/service/type to LoadBalancer is not effective, the service is still created as ClusterIP.

Suggested Solution:
==============
Fix the chart to use the value specified in values configuration.

**Comment by tegioz** [comment]
Hi @eduardoroliveira 

The [hub service](https://github.com/artifacthub/hub/blob/d62375b7d3ef865ee244590bc67021107c626a33/charts/artifact-hub/templates/hub_service.yaml) seems to be using the service type value passed to the chart:

```
$ helm install hub --set hub.service.type=LoadBalancer artifact-hub/artifact-hub

$ kubectl get svc hub
NAME   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
hub    LoadBalancer   10.108.218.199   <pending>     80:30345/TCP   46s
```

Whether a load balancer is created or not will depend on the cloud provider your cluster runs on. Please note that the chart also provides an [ingress](https://github.com/artifacthub/hub/blob/d62375b7d3ef865ee244590bc67021107c626a33/charts/artifact-hub/templates/hub_ingress.yaml) to expose the service.

**Comment by tegioz** [comment]
I'll close this one for now, please reopen if needed.
