### ISSUE TITLE
Support for values schema that leverage combining keywords

### ISSUE THREAD

**Issue by eshepelyuk** [artifacthub/hub#946]
### Context

[Slack thread](https://cloud-native.slack.com/archives/C0103CTR3RB/p1607427243041100)

### The problem 

Currently, schemas using [combining keywords](https://json-schema.org/understanding-json-schema/reference/combining.html) are not supported, and not displayed properly in values view of web UI.
Although such schemas are valid and pass `helm lint` from CLI, the display is broken.

### Examples

* [schema](https://github.com/eshepelyuk/cmak-operator/blob/master/values.schema.json#L95)
* values reference displayed as empty
![image](https://user-images.githubusercontent.com/1279477/101490006-66444980-396a-11eb-98f0-caa2760e926e.png)

### Solution 

ArtifactHub should support all of `combining keywords` and display values schemas properly.

**Comment by tegioz** [comment]
We'll deploy it tomorrow morning @eshepelyuk, we'll let you know when it's done 😉

**Comment by eshepelyuk** [comment]
Thnx a lot !

**Comment by tegioz** [comment]
Deployed!

**Comment by eshepelyuk** [comment]
Amazing !!!
