### ISSUE TITLE
Swap colors of the star/unstar icon 

### ISSUE THREAD

**Issue by shuuji3** [artifacthub/hub#948]
**Problem**

On the package page (i.e. [argo/argo-cd](https://artifacthub.io/packages/helm/argo/argo-cd)) of the Artifact Hub, there is a "Star" button which has a star icon. But I feel the colors of star are not intuitive.

Because on many websites including here, the bordered star represents that the star is not selected yet and the filled one represents the star has already been selected and if we click that it means to unstar. Another example is the one in the shopping site, 5 stars are shown by 5 filled stars but not vice-versa.

**Screenshots of buttons**

GitHub:
![Screenshot from 2020-12-09 02-06-46](https://user-images.githubusercontent.com/1425259/101518388-31b1ab80-39c5-11eb-8af6-fa0e512aa69c.png)![Screenshot from 2020-12-09 02-06-37](https://user-images.githubusercontent.com/1425259/101518391-32e2d880-39c5-11eb-85a3-0dd9a7d75156.png)

Artifact Hub:
![Screenshot from 2020-12-09 02-06-09](https://user-images.githubusercontent.com/1425259/101518392-32e2d880-39c5-11eb-9e58-7fd554f2e3e1.png)![Screenshot from 2020-12-09 02-05-59](https://user-images.githubusercontent.com/1425259/101518394-337b6f00-39c5-11eb-9abd-de476b9d7388.png)

**Solution**

Swap the white-filled star with the white-bordered one.

If it is OK to swap stars, I'd like to try to create PR. :slightly_smiling_face:

**Comment by tegioz** [comment]
Hi @shuuji3 

Swapping stars sounds good to me, makes sense. Please feel free to create a PR for it 🙂 

Thanks!

**Comment by shuuji3** [comment]
@tegioz Thank you! I'm going to submit a PR later.

**Comment by shuuji3** [comment]
I've just created the PR #970
