### ISSUE TITLE
Support for ignoring certain Charts form being published to Atifacthub

### ISSUE THREAD

**Issue by onedr0p** [artifacthub/hub#974]
Hi! 👋 

It would be nice if we had a field we could set to ignore publishing to artifacthub for certian charts.

Use case is we have a common chart which should not be installed locally 

https://github.com/k8s-at-home/charts/tree/master/charts/common

But it shows up on artifacthub.

Maybe a new field like `publish: false` in [artifacthub-pkg.yml](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml) would be awesome. Default would be `publish: true`

**Comment by bjw-s** [comment]
+1, something like this could really come in handy.
Another approach (instead of a field in `artifacthub-pkg.yml`) could be through adding a new annotation to Helm charts?

**Comment by tegioz** [comment]
Hi 👋 

This sounds like a nice addition 👍 

For Helm and OLM packages, I'd prefer using a special `artifacthub.io/...` annotation (https://artifacthub.io/docs/topics/annotations/helm/). For Falco and OPA, a new field in the package metadata file would fit better.

Thanks, will take care of this soon.

**Comment by onedr0p** [comment]
Thanks and no rush! `artifacthub.io/...` annotation is great as well.

**Comment by tegioz** [comment]
In the end I've used a slightly different approach. The problem with using the `artifacthub-pkg.yml` file or the annotations is that the new field would have to be set per package version, as each of them is indexed independently. This could make this feature not easy to work with as modifying existing versions is not ideal and may not be trivial.

So instead I've prepared it so that it's configured at the repository level, in the [artifacthub-repo.yml](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) file, using a new field named `ignore`. You can exclude all versions of one or more packages, a specific one, or even use a regular expression that suits your needs.

Hope this helps. Please let me know if something doesn't work as expected.

P.D.: It's not deployed to production yet, I'll let you know as soon as it is.

**Comment by tegioz** [comment]
Deployed! Please note that repositories are not processed again unless something has changed on them since the last time they were processed: new version added, etc.

**Comment by onedr0p** [comment]
Thanks @tegioz we have updated our `artifacthub-repo.yml`! Will let you know if we run into any problems.

**Comment by tegioz** [comment]
```
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.1.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.5.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.0.1
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.0.5
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.4.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.7.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.6.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.6.2
3:30PM DBG unregistering package cmd=tracker kind=helm name=plex-media-server repo=k8s-at-home v=0.2.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=plex-media-server repo=k8s-at-home v=0.0.3
3:30PM DBG unregistering package cmd=tracker kind=helm name=plex-media-server repo=k8s-at-home v=0.0.2
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.3.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=plex-media-server repo=k8s-at-home v=0.1.1
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.2.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.0.2
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.5.1
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.0.0
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.0.4
3:30PM DBG unregistering package cmd=tracker kind=helm name=plex-media-server repo=k8s-at-home v=0.0.1
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.6.1
3:30PM DBG unregistering package cmd=tracker kind=helm name=common repo=k8s-at-home v=1.0.3
```

🙂

**Comment by onedr0p** [comment]
Stop hacking us 😆  Looks great!
