### ISSUE TITLE
Improve the UI design

### ISSUE THREAD

**Issue by kangshung** [artifacthub/hub#996]
While using the website on the split screen, the UI becomes very unintuitive no matter how much space you give it:

- unresizable white space below "RELATED PACKAGES"
- barely scrollable (horizontally) wide content 
- the scrolling bar at the end just does not fit well

All of these are shown here:

![blank-space-horizontal-scrolling](https://user-images.githubusercontent.com/47540509/103480188-276fab00-4dd3-11eb-8609-87b12c93e6de.gif)

Maybe adding an option to hide the right panel would be a good idea.

Also, after choosing "Show more..." below "CHART VERSIONS" for some charts it takes ages to scroll down to click the Github link, and the only way is to click "Show less..." at the bottom. IMO, this button should be added at the top to save some frustration.

![show-more](https://user-images.githubusercontent.com/47540509/103480625-9b12b780-4dd5-11eb-9bf4-d61f5ebcc664.gif)

**Comment by tegioz** [comment]
Thank you for your feedback @kangshung, we'll look into it 🙂

**Comment by tegioz** [comment]
Hi @kangshung 

When the number of available versions is large, they are now displayed in a separate modal:

<img width="1318" alt="Screen Shot 2021-01-28 at 16 21 28" src="https://user-images.githubusercontent.com/1213902/106159364-fd689900-6184-11eb-9f91-1f20dc217b49.png">
