### ISSUE TITLE
New endpoint for Harbor replication adapter

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#997]
Harbor is working on a new replication adapter to synchronize content from Artifact Hub. In the [current implementation](https://github.com/goharbor/harbor/tree/master/src/replication/adapter/artifacthub), a summary of all packages available is fetched, and then, each of the packages that matches the filter configured in Harbor is fetched individually to get the package content url.

Depending on the filter used, this can lead to a lot of requests, causing some rate limiting problems on the Harbor side, as Artifact Hub has some API usage limits. Eventually it may also cause some problems for Artifact Hub when more users start synchronizing content too often.

Based on this, we are planning to add a new endpoint that will allow getting a summary dump of the available content in Artifact Hub in a single request. This dump will contain a list of the available packages and versions, with some minimal details about them, like the repository name, version and content url. The content of this dump is expected to be refreshed hourly, so it can be pre-generated and cached accordingly.

Related to: goharbor/harbor#13365 and goharbor/harbor#13244

Thanks for raising the rate limiting issue and the nice chat @mmpei 🙂

**Comment by tegioz** [comment]
Deployed! The new endpoint documentation is available [here](https://artifacthub.github.io/hub/api/#/Integrations/get_harborReplication). Please let me know if you find any issue @mmpei.

**Comment by mmpei** [comment]
Thank you. It really helps us a lot. I have modified the implement using this new API, and now the replication between two endpoints flys. @tegioz
By the way, this feature will be released in Harbor v2.2.0.

**Comment by tegioz** [comment]
Thanks @mmpei, that sounds great 🙂

**Comment by joeltraber** [comment]
The new adapter has a fix URL for the endpoint. How can I replicate a private helm repo? or another public one .. serving on a different URL?
![helmhubadapter](https://user-images.githubusercontent.com/5963149/204507133-42d14434-ad0a-44da-ba46-cf48ee1d3511.png)

**Comment by tegioz** [comment]
Hi @joeltraber 👋 

Unfortunately we can't help with this, but maybe you can ask the question in the Harbor Slack (or discussions in their GitHub repo) and someone from their community may be able to help 🙂
